//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSDictionary, NSMutableArray, NSMutableData, NSMutableDictionary, NSMutableSet, NSNumber, NSProgress, NSString, NSURL, NSURLResponse, NSURLSession, NSURLSessionUploadTask, SDAirDropFileZipper, SDAirDropPeerMetric, SDBonjourResolver, SDStatusMonitor, SDXPCHelperConnection;
@protocol OS_dispatch_queue, OS_os_transaction, SDAirDropClientDelegate;

@interface SDAirDropClient : NSObject
{
    MISSING_TYPE *_askResponse;	// 8 = 0x8
    NSURLSessionUploadTask *_askTask;	// 16 = 0x10
    _Bool _cancelled;	// 24 = 0x18
    NSString *_clientBundleID;	// 32 = 0x20
    NSString *_connectionKey;	// 40 = 0x28
    _Bool _conversionNotified;	// 48 = 0x30
    _Bool _conversionObserver;	// 49 = 0x31
    NSProgress *_conversionProgress;	// 56 = 0x38
    _Bool _discover;	// 64 = 0x40
    NSURLResponse *_discoverResponse;	// 72 = 0x48
    NSURLSessionUploadTask *_discoverTask;	// 80 = 0x50
    int _failCount;	// 88 = 0x58
    struct CGImage *_fileIcon;	// 96 = 0x60
    NSMutableArray *_fileURLs;	// 104 = 0x68
    NSMutableDictionary *_fileURLToConversionNeeded;	// 112 = 0x70
    NSMutableSet *_generatedFiles;	// 120 = 0x78
    struct __SecIdentity *_identity;	// 128 = 0x80
    NSArray *_items;	// 136 = 0x88
    long long _lastEvent;	// 144 = 0x90
    NSMutableArray *_mediaFormatConversionDestinations;	// 152 = 0x98
    SDAirDropPeerMetric *_metric;	// 160 = 0xa0
    SDStatusMonitor *_monitor;	// 168 = 0xa8
    NSMutableArray *_otherStuff;	// 176 = 0xb0
    _Bool _p2pRetained;	// 184 = 0xb8
    struct __SFNode *_person;	// 192 = 0xc0
    _Bool _personAdded;	// 200 = 0xc8
    unsigned int _powerAssertionID;	// 204 = 0xcc
    NSProgress *_progress;	// 208 = 0xd0
    NSMutableDictionary *_properties;	// 216 = 0xd8
    _Bool _providedStream;	// 224 = 0xe0
    NSObject<OS_dispatch_queue> *_queue;	// 232 = 0xe8
    _Bool _queueSuspended;	// 240 = 0xf0
    NSMutableData *_receiverData;	// 248 = 0xf8
    _Bool _receiverSupportsDVZip;	// 256 = 0x100
    SDBonjourResolver *_resolver;	// 264 = 0x108
    NSNumber *_sendingLivePhotoJPEGs;	// 272 = 0x110
    struct __SecTrust *_serverTrust;	// 280 = 0x118
    NSURL *_serverURL;	// 288 = 0x120
    NSURLSession *_session;	// 296 = 0x128
    _Bool _shouldPublishProgress;	// 304 = 0x130
    struct CGImage *_smallFileIcon;	// 312 = 0x138
    double _startTime;	// 320 = 0x140
    NSURL *_tmpDirectoryToCleanUp;	// 328 = 0x148
    NSObject<OS_os_transaction> *_transaction;	// 336 = 0x150
    _Bool _transactionStarted;	// 344 = 0x158
    NSProgress *_transferProgress;	// 352 = 0x160
    _Bool _uploadFinished;	// 360 = 0x168
    NSURLResponse *_uploadResponse;	// 368 = 0x170
    NSURLSessionUploadTask *_uploadTask;	// 376 = 0x178
    NSMutableArray *_weblocURLs;	// 384 = 0x180
    SDXPCHelperConnection *_xpcHelperConnection;	// 392 = 0x188
    SDAirDropFileZipper *_zipper;	// 400 = 0x190
    _Bool _zipperFinished;	// 408 = 0x198
    int _clientPid;	// 412 = 0x19c
    NSDictionary *_discoveryMetrics;	// 416 = 0x1a0
    id <SDAirDropClientDelegate> _delegate;	// 424 = 0x1a8
    CDStruct_4c969caf _auditToken;	// 432 = 0x1b0
}

- (void).cxx_destruct;	// IMP=0x002000000004b905
@property __weak id <SDAirDropClientDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool shouldPublishProgress; // @synthesize shouldPublishProgress=_shouldPublishProgress;
@property(copy) NSDictionary *discoveryMetrics; // @synthesize discoveryMetrics=_discoveryMetrics;
@property(copy) NSString *clientBundleID; // @synthesize clientBundleID=_clientBundleID;
@property int clientPid; // @synthesize clientPid=_clientPid;
@property CDStruct_4c969caf auditToken; // @synthesize auditToken=_auditToken;
- (void)donateTransferInteractionToDuet;	// IMP=0x001000000004b80d
- (_Bool)receiverDeviceModelNameSuggestsMacPlatform;	// IMP=0x001000000004b794
- (id)receiverMediaCapabilities;	// IMP=0x001000000004b694
- (void)convertMediaItemsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000004b689
- (void)generatePreviewForFileURL:(id)arg1;	// IMP=0x001000000004b683
- (void)invalidate;	// IMP=0x001000000004b14a
@property(readonly) NSString *personID;
- (_Bool)send;	// IMP=0x001000000004af61
- (void)resolve;	// IMP=0x001000000004ae21
- (void)activate;	// IMP=0x001000000004a8bf
- (void)startSending;	// IMP=0x001000000004a314
- (id)tmpDirectory;	// IMP=0x001000000004a17d
- (void)cancelSendingClassroom;	// IMP=0x001000000004a0ca
- (void)startSendingClassroom;	// IMP=0x0010000000049e95
- (void)startPublishingProgress;	// IMP=0x0010000000049c50
- (void)removeFileIconsFromProperties;	// IMP=0x0010000000049b5c
- (void)appendFileURL:(id)arg1 withBase:(id)arg2 toItems:(id)arg3;	// IMP=0x001000000004976d
- (void)validateAirDropItemsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000004911a
- (_Bool)splitOutFileURLs;	// IMP=0x0010000000048cf8
- (id)realPathURL:(struct __CFURL *)arg1;	// IMP=0x0010000000048ae8
- (id)webURLFromInternetLocationFile:(id)arg1;	// IMP=0x0010000000048a31
- (id)internetLocationFile:(struct __CFURL *)arg1;	// IMP=0x00100000000488a3
- (id)temporaryWeblocURL:(struct __CFURL *)arg1;	// IMP=0x00100000000486be
- (void)startZipping;	// IMP=0x00100000000485b1
- (void)sendRequest:(id)arg1;	// IMP=0x0010000000047ed6
- (id)discoverBodyDataInFormat:(long long)arg1;	// IMP=0x0010000000047e70
- (id)askBodyDataInFormat:(long long)arg1;	// IMP=0x0010000000047ba3
- (id)askRequestClientBundleID;	// IMP=0x0010000000047ad6
- (void)addHashesAndValidationRecordToRequest:(id)arg1;	// IMP=0x0010000000047a13
- (void)bonjourResolverDidChange:(id)arg1;	// IMP=0x00100000000475cc
- (void)fileZipper:(id)arg1 event:(long long)arg2 withProperty:(void *)arg3;	// IMP=0x001000000004743d
- (void)URLSession:(id)arg1 task:(id)arg2 needNewBodyStream:(CDUnknownBlockType)arg3;	// IMP=0x0010000000047304
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000046e0c
- (void)URLSession:(id)arg1 task:(id)arg2 didFinishCollectingMetrics:(id)arg3;	// IMP=0x00100000000469d3
@property(readonly) struct __SecTrust *secTrustRef;
- (void)logInterfaceUsedForSending:(id)arg1;	// IMP=0x0010000000046978
- (void)releasePeerToPeerIfPossible:(id)arg1;	// IMP=0x00100000000468f6
- (_Bool)connectionOverP2P:(struct __CFData *)arg1;	// IMP=0x00100000000466c2
- (struct __SecKey *)copyReceiverPublicKey;	// IMP=0x00100000000465b6
- (void)evaluateReceiverTrust:(struct __SecTrust *)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000046426
- (void)didFail:(id)arg1;	// IMP=0x0010000000046188
- (_Bool)shouldCancelTransferForError:(id)arg1;	// IMP=0x001000000004609a
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x0010000000045f9f
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;	// IMP=0x0010000000045f0f
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;	// IMP=0x0010000000045e6d
- (void)didFinishLoading;	// IMP=0x0010000000045c5a
- (void)retryRequestForError:(id)arg1;	// IMP=0x0010000000045aaf
- (void)finishOperation;	// IMP=0x00100000000456b6
- (void)notifyClientOfBytesCopied:(id)arg1 timeRemaining:(id)arg2;	// IMP=0x001000000004556a
- (_Bool)parseDiscoverResponse:(struct __CFError **)arg1;	// IMP=0x00100000000453ba
- (_Bool)parseAskResponse:(struct __CFError **)arg1;	// IMP=0x0010000000045259
- (void)storeStringValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x00100000000451c2
- (void)storeDataValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x001000000004512b
- (void)storePropertyValue:(void *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0010000000045030
- (void)setProperty:(id)arg1 forKey:(id)arg2;	// IMP=0x0010000000045017
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0010000000044ac4
- (void)setSpotlightMetadata:(id)arg1;	// IMP=0x0010000000044abe
- (id)whereFromInfo;	// IMP=0x0010000000044a19
- (void)didFinishSendingAskBodyData;	// IMP=0x00100000000449dd
- (void)didStartSendingAskBodyData;	// IMP=0x001000000004494a
- (void)postNotificationForTransferStatus:(long long)arg1 progress:(double)arg2;	// IMP=0x0010000000044944
- (void)notifyClientForEvent:(long long)arg1 withProperty:(void *)arg2;	// IMP=0x001000000004402a
- (void)releaseIdleSleepAssertion;	// IMP=0x0010000000043f06
- (double)getTransferSize;	// IMP=0x0010000000043e9e
- (double)getTransferRate;	// IMP=0x0010000000043e06
- (void)createSession;	// IMP=0x0010000000043b2b
- (_Bool)requireAWDL;	// IMP=0x0010000000043ae9
- (void)removeObservers;	// IMP=0x0010000000043a96
- (void)addObservers;	// IMP=0x0010000000043a0d
- (void)wirelessPowerChanged:(id)arg1;	// IMP=0x00100000000439aa
- (void)systemWillSleep:(id)arg1;	// IMP=0x0010000000043964
- (void)dealloc;	// IMP=0x001000000004385b
- (id)initWithPerson:(struct __SFNode *)arg1 items:(id)arg2 forDiscovery:(_Bool)arg3;	// IMP=0x00100000000433f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

