//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandlerCalendarEvents
{
}

- (void)updatePossibleActions;	// IMP=0x0040000000095120
- (id)suitableContentsDescription;	// IMP=0x0010000000094f92
- (long long)transferTypes;	// IMP=0x0010000000094f5f
- (_Bool)canHandleTransfer;	// IMP=0x0010000000094f4a
- (id)initWithTransfer:(id)arg1;	// IMP=0x0010000000094f14

@end

