//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandlerVoiceMemos
{
}

- (void)updatePossibleActions;	// IMP=0x002000000009a7be
- (id)suitableContentsDescription;	// IMP=0x001000000009a630
- (long long)transferTypes;	// IMP=0x001000000009a5fb
- (_Bool)canHandleTransfer;	// IMP=0x001000000009a551
@property(readonly, nonatomic) _Bool canHandleTransferRegardlessOfBundleID;
- (id)initWithTransfer:(id)arg1;	// IMP=0x001000000009a30d

@end

