//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandleriCloudFamilyLinks
{
}

- (id)cancelActionTitleToAccompanyActions:(id)arg1;	// IMP=0x00400000000d77b7
- (id)singleItemActionTitle;	// IMP=0x00100000000d77a6
- (id)suitableContentsDescription;	// IMP=0x00100000000d76f1
- (id)suitableContentsTitle;	// IMP=0x00100000000d76e0
- (long long)transferTypes;	// IMP=0x00100000000d76ac
- (_Bool)canHandleTransfer;	// IMP=0x00100000000d76a4
- (id)initWithTransfer:(id)arg1;	// IMP=0x00100000000d766e

@end

