//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class SDAirDropHandleriCloudDrive;

@interface SDAirDropHandlerUnsupportedType
{
    SDAirDropHandleriCloudDrive *_icloudDriveHandler;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000000e456
- (void)triggerAppStoreSearch;	// IMP=0x001000000000e247
- (void)updatePossibleActions;	// IMP=0x001000000000df59
- (id)suitableContentsDescription;	// IMP=0x001000000000de3e
- (_Bool)canHandleTransfer;	// IMP=0x001000000000ddb6
- (id)initWithTransfer:(id)arg1;	// IMP=0x001000000000dcde

@end

