//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData;

@interface SDAutoUnlockRegistrationLockSession
{
    NSData *_requestData;	// 8 = 0x8
    long long _state;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000018f6bc
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) NSData *requestData; // @synthesize requestData=_requestData;
- (void)transport:(id)arg1 didReceiveMessageACKForIdentifier:(id)arg2;	// IMP=0x001000000018f66f
- (void)transport:(id)arg1 didReceivePayload:(id)arg2 type:(unsigned short)arg3 deviceID:(id)arg4;	// IMP=0x001000000018f4cb
- (void)handleFinalize:(id)arg1;	// IMP=0x001000000018f03e
- (void)handleInitialResponse:(id)arg1;	// IMP=0x001000000018ea16
- (void)sendInitialRequest;	// IMP=0x001000000018e7c8
- (void)onQueue_start;	// IMP=0x001000000018e707
- (void)start;	// IMP=0x001000000018e680
- (id)initWithDevice:(id)arg1 sessionID:(id)arg2;	// IMP=0x001000000018e63d

@end

