//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC10LinkDaemon8Registry : NSObject
{
    MISSING_TYPE *applicationSource;	// 8 = 0x8
    MISSING_TYPE *indexingQueue;	// 48 = 0x30
    MISSING_TYPE *autoShortcutsFetcher;	// 56 = 0x38
    MISSING_TYPE *batchedNotifier;	// 64 = 0x40
    MISSING_TYPE *ready;	// 72 = 0x48
    MISSING_TYPE *;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x00400000000600a0
- (id)init;	// IMP=0x0010000000060040

@end

