//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSAsset, CSAttSiriController, CSAttSiriEndpointerNode, CSAttSiriSSRNode, CSAttSiriUresNode, CSAudioProcessWaitingBuffer, CSAudioRecordContext, CSConnectionListener, CSEndpointDelayReporter, CSOSTransaction, CSPlainAudioFileWriter, CoreEmbeddedSpeechRecognizer, LBLocalSpeechRecognitionSettings, NSArray, NSString, NSUUID;
@protocol OS_dispatch_queue;

@interface CSAttSiriAsrNode : NSObject
{
    _Bool _isReady;	// 8 = 0x8
    _Bool _speechHasAcceptedResultCandidate;	// 9 = 0x9
    _Bool _shouldProcessAudio;	// 10 = 0xa
    _Bool _isFileLoggingEnabled;	// 11 = 0xb
    _Bool _didDetectedEndpoint;	// 12 = 0xc
    _Bool _shouldStopProcessASROnEndpoint;	// 13 = 0xd
    _Bool _disableEndpointer;	// 14 = 0xe
    unsigned int _activeChannel;	// 16 = 0x10
    unsigned long long _type;	// 24 = 0x18
    NSArray *_requiredNodes;	// 32 = 0x20
    CSAttSiriController *_attSiriController;	// 40 = 0x28
    NSString *_mhId;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_targetQueue;	// 56 = 0x38
    CSAttSiriEndpointerNode *_endpointerNode;	// 64 = 0x40
    CSAttSiriUresNode *_uresNode;	// 72 = 0x48
    CSAttSiriSSRNode *_ssrNode;	// 80 = 0x50
    NSObject<OS_dispatch_queue> *_localSpeechRecognizerQueue;	// 88 = 0x58
    CoreEmbeddedSpeechRecognizer *_interactiveLocalSpeechRecognizer;	// 96 = 0x60
    CoreEmbeddedSpeechRecognizer *_presetLocalSpeechRecognizer;	// 104 = 0x68
    NSString *_localSpeechRecognizerTaskString;	// 112 = 0x70
    unsigned long long _localSpeechRecognizerState;	// 120 = 0x78
    CSAudioProcessWaitingBuffer *_audioWaitingBuffer;	// 128 = 0x80
    double _localSpeechRecognizerDeliverAudioDuration;	// 136 = 0x88
    NSString *_language;	// 144 = 0x90
    NSString *_requestId;	// 152 = 0x98
    unsigned long long _eagerResultId;	// 160 = 0xa0
    LBLocalSpeechRecognitionSettings *_speechRecognitionSettings;	// 168 = 0xa8
    CSAudioRecordContext *_recordContext;	// 176 = 0xb0
    long long _endpointMode;	// 184 = 0xb8
    CSOSTransaction *_asrResultDeliveryTransaction;	// 192 = 0xc0
    CSOSTransaction *_recordingTransaction;	// 200 = 0xc8
    NSString *_siriSessionUUID;	// 208 = 0xd0
    NSUUID *_recordingToken;	// 216 = 0xd8
    unsigned long long _voiceTriggerFireMachTime;	// 224 = 0xe0
    CSPlainAudioFileWriter *_audioFileWriter;	// 232 = 0xe8
    double _endpointStartTimeInSec;	// 240 = 0xf0
    unsigned long long _audioSampleCountToSkip;	// 248 = 0xf8
    double _detectedEndpointTime;	// 256 = 0x100
    double _lastEndpointHintDuration;	// 264 = 0x108
    long long _lastEndpointHintRCId;	// 272 = 0x110
    unsigned long long _lastEndpointEagerResultTime;	// 280 = 0x118
    NSArray *_lastEndpointHintFeatures;	// 288 = 0x120
    CSEndpointDelayReporter *_endpointDelayReporter;	// 296 = 0x128
    unsigned long long _recordingStartTime;	// 304 = 0x130
    unsigned long long _firstPartialResultTime;	// 312 = 0x138
    double _timeToSpeakFirstWord;	// 320 = 0x140
    CSConnectionListener *_localSRBridgeListener;	// 328 = 0x148
}

+ (long long)endpointModeFromEndpointMetrics:(id)arg1;	// IMP=0x0020000000096a96
- (void).cxx_destruct;	// IMP=0x002000000009799a
@property(retain, nonatomic) CSConnectionListener *localSRBridgeListener; // @synthesize localSRBridgeListener=_localSRBridgeListener;
@property(nonatomic) double timeToSpeakFirstWord; // @synthesize timeToSpeakFirstWord=_timeToSpeakFirstWord;
@property(nonatomic) unsigned long long firstPartialResultTime; // @synthesize firstPartialResultTime=_firstPartialResultTime;
@property(nonatomic) unsigned long long recordingStartTime; // @synthesize recordingStartTime=_recordingStartTime;
@property(retain, nonatomic) CSEndpointDelayReporter *endpointDelayReporter; // @synthesize endpointDelayReporter=_endpointDelayReporter;
@property(nonatomic) _Bool disableEndpointer; // @synthesize disableEndpointer=_disableEndpointer;
@property(retain, nonatomic) NSArray *lastEndpointHintFeatures; // @synthesize lastEndpointHintFeatures=_lastEndpointHintFeatures;
@property(nonatomic) unsigned long long lastEndpointEagerResultTime; // @synthesize lastEndpointEagerResultTime=_lastEndpointEagerResultTime;
@property(nonatomic) long long lastEndpointHintRCId; // @synthesize lastEndpointHintRCId=_lastEndpointHintRCId;
@property(nonatomic) double lastEndpointHintDuration; // @synthesize lastEndpointHintDuration=_lastEndpointHintDuration;
@property(nonatomic) _Bool shouldStopProcessASROnEndpoint; // @synthesize shouldStopProcessASROnEndpoint=_shouldStopProcessASROnEndpoint;
@property(nonatomic) double detectedEndpointTime; // @synthesize detectedEndpointTime=_detectedEndpointTime;
@property(nonatomic) _Bool didDetectedEndpoint; // @synthesize didDetectedEndpoint=_didDetectedEndpoint;
@property(nonatomic) unsigned long long audioSampleCountToSkip; // @synthesize audioSampleCountToSkip=_audioSampleCountToSkip;
@property(nonatomic) double endpointStartTimeInSec; // @synthesize endpointStartTimeInSec=_endpointStartTimeInSec;
@property(nonatomic) _Bool isFileLoggingEnabled; // @synthesize isFileLoggingEnabled=_isFileLoggingEnabled;
@property(retain, nonatomic) CSPlainAudioFileWriter *audioFileWriter; // @synthesize audioFileWriter=_audioFileWriter;
@property(nonatomic) unsigned long long voiceTriggerFireMachTime; // @synthesize voiceTriggerFireMachTime=_voiceTriggerFireMachTime;
@property(retain, nonatomic) NSUUID *recordingToken; // @synthesize recordingToken=_recordingToken;
@property(retain, nonatomic) NSString *siriSessionUUID; // @synthesize siriSessionUUID=_siriSessionUUID;
@property(retain, nonatomic) CSOSTransaction *recordingTransaction; // @synthesize recordingTransaction=_recordingTransaction;
@property(retain, nonatomic) CSOSTransaction *asrResultDeliveryTransaction; // @synthesize asrResultDeliveryTransaction=_asrResultDeliveryTransaction;
@property(nonatomic) long long endpointMode; // @synthesize endpointMode=_endpointMode;
@property(nonatomic) _Bool shouldProcessAudio; // @synthesize shouldProcessAudio=_shouldProcessAudio;
@property(retain, nonatomic) CSAudioRecordContext *recordContext; // @synthesize recordContext=_recordContext;
@property(retain, nonatomic) LBLocalSpeechRecognitionSettings *speechRecognitionSettings; // @synthesize speechRecognitionSettings=_speechRecognitionSettings;
@property(nonatomic) _Bool speechHasAcceptedResultCandidate; // @synthesize speechHasAcceptedResultCandidate=_speechHasAcceptedResultCandidate;
@property(nonatomic) unsigned long long eagerResultId; // @synthesize eagerResultId=_eagerResultId;
@property(retain, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(nonatomic) unsigned int activeChannel; // @synthesize activeChannel=_activeChannel;
@property(nonatomic) double localSpeechRecognizerDeliverAudioDuration; // @synthesize localSpeechRecognizerDeliverAudioDuration=_localSpeechRecognizerDeliverAudioDuration;
@property(retain, nonatomic) CSAudioProcessWaitingBuffer *audioWaitingBuffer; // @synthesize audioWaitingBuffer=_audioWaitingBuffer;
@property(nonatomic) unsigned long long localSpeechRecognizerState; // @synthesize localSpeechRecognizerState=_localSpeechRecognizerState;
@property(retain, nonatomic) NSString *localSpeechRecognizerTaskString; // @synthesize localSpeechRecognizerTaskString=_localSpeechRecognizerTaskString;
@property(retain, nonatomic) CoreEmbeddedSpeechRecognizer *presetLocalSpeechRecognizer; // @synthesize presetLocalSpeechRecognizer=_presetLocalSpeechRecognizer;
@property(retain, nonatomic) CoreEmbeddedSpeechRecognizer *interactiveLocalSpeechRecognizer; // @synthesize interactiveLocalSpeechRecognizer=_interactiveLocalSpeechRecognizer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *localSpeechRecognizerQueue; // @synthesize localSpeechRecognizerQueue=_localSpeechRecognizerQueue;
@property(nonatomic, setter=registerSSRNode:) __weak CSAttSiriSSRNode *ssrNode; // @synthesize ssrNode=_ssrNode;
@property(nonatomic, setter=registerUresNode:) __weak CSAttSiriUresNode *uresNode; // @synthesize uresNode=_uresNode;
@property(nonatomic, setter=registerEndpointerNode:) __weak CSAttSiriEndpointerNode *endpointerNode; // @synthesize endpointerNode=_endpointerNode;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *targetQueue; // @synthesize targetQueue=_targetQueue;
@property(retain, nonatomic) NSString *mhId; // @synthesize mhId=_mhId;
@property(nonatomic) __weak CSAttSiriController *attSiriController; // @synthesize attSiriController=_attSiriController;
@property(nonatomic) _Bool isReady; // @synthesize isReady=_isReady;
@property(retain, nonatomic) NSArray *requiredNodes; // @synthesize requiredNodes=_requiredNodes;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (void)_setupRecognizerStateForMagusAsrNode;	// IMP=0x00100000000974cc
- (void)_markTimeToFirstWordMetric;	// IMP=0x00100000000972b3
- (id)_fetchRecognizerLanguageWithSiriLanguage:(id)arg1 UILanguage:(id)arg2 taskString:(id)arg3;	// IMP=0x001000000009717a
- (double)_getFirstTokenSilenceStartTimeFromSpeechPackage:(id)arg1;	// IMP=0x001000000009705f
- (double)_getProcessedAudioDurationFromSpeechPackage:(id)arg1;	// IMP=0x0010000000096f36
- (double)_getUserSpeakingEndedTimeFromSpeechPackage:(id)arg1;	// IMP=0x0010000000096e0d
- (id)_stateToString:(unsigned long long)arg1;	// IMP=0x0010000000096dee
- (void)_setLocalSpeechRecognizerState:(unsigned long long)arg1;	// IMP=0x0010000000096cd2
- (void)_clearAudioProcessWaitingBufferIfNeeded;	// IMP=0x0010000000096c80
- (id)_getAsrInputoriginFromContext:(id)arg1;	// IMP=0x0010000000096c00
- (id)_fetchInputOriginWithRecordContext:(id)arg1;	// IMP=0x0010000000096ac5
- (unsigned long long)fetchCurrentState;	// IMP=0x0010000000096740
- (void)localSpeechRecognizer:(id)arg1 didSelectRecognitionModelWithModelProperties:(id)arg2;	// IMP=0x00100000000965f5
- (void)localSpeechRecognizer:(id)arg1 didProduceEndpointFeaturesWithWordCount:(long long)arg2 trailingSilenceDuration:(long long)arg3 eosLikelihood:(double)arg4 pauseCounts:(id)arg5 silencePosterior:(double)arg6 processedAudioDurationInMilliseconds:(long long)arg7;	// IMP=0x00100000000963b1
- (void)localSpeechRecognizer:(id)arg1 didCompletionRecognitionWithStatistics:(id)arg2 error:(id)arg3;	// IMP=0x0010000000095d7a
- (void)_handleDidRecognizedSpeechPackageForEagerRecognitionCandidate:(id)arg1 requestId:(id)arg2 rcId:(unsigned long long)arg3 metadata:(id)arg4;	// IMP=0x00100000000959e0
- (void)_handleDidRecognizedFinalSpeechPackage:(id)arg1 requestId:(id)arg2 metadata:(id)arg3;	// IMP=0x0010000000095752
- (void)localSpeechRecognizer:(id)arg1 didRecognizePackage:(id)arg2 withMetadata:(id)arg3;	// IMP=0x0010000000095499
- (void)localSpeechRecognizer:(id)arg1 didRecognizePackage:(id)arg2;	// IMP=0x0010000000095234
- (void)localSpeechRecognizer:(id)arg1 didRecognizeFinalResultCandidatePackage:(id)arg2;	// IMP=0x0010000000094ff7
- (void)_handleShouldAcceptEagerResultWithRequestId:(id)arg1 rcId:(unsigned long long)arg2 duration:(double)arg3 shouldAccept:(_Bool)arg4 featuresToLog:(id)arg5;	// IMP=0x0010000000094dcd
- (void)_queryShouldAcceptEagerResultForDuration:(double)arg1 requestId:(id)arg2 rcId:(unsigned long long)arg3;	// IMP=0x0010000000094ae8
- (void)localSpeechRecognizer:(id)arg1 didRecognizeRawEagerRecognitionCandidate:(id)arg2;	// IMP=0x0010000000094ae2
- (void)localSpeechRecognizer:(id)arg1 didProcessAudioDuration:(double)arg2;	// IMP=0x00100000000948d9
- (void)localSpeechRecognizer:(id)arg1 didRecognizeTokens:(id)arg2 withMetadata:(id)arg3;	// IMP=0x00100000000945c0
- (void)localSpeechRecognizer:(id)arg1 didRecognizeTokens:(id)arg2;	// IMP=0x0010000000094332
- (void)_resetLocalSpeechRecognizerParameters;	// IMP=0x0010000000094313
- (void)_invalidateLocalSpeechRecognizer:(_Bool)arg1;	// IMP=0x00100000000942b5
- (id)_interactiveLocalSpeechRecognizer;	// IMP=0x00100000000941a7
- (void)_releaseRecordingTransactionIfNeededWithToken:(id)arg1;	// IMP=0x0010000000094041
- (void)_scheduleRecordingTransactionReleaseTimer;	// IMP=0x0010000000093ea0
- (void)_handleStopSpeechRecognitionTaskIfNeeded:(_Bool)arg1;	// IMP=0x0010000000093c59
- (void)_processAudioChunk:(id)arg1;	// IMP=0x001000000009391a
- (void)_startLocalSpeechRecognizerIfNeeded;	// IMP=0x0010000000092901
- (_Bool)_shouldDisableLocalSpeechRecognizerWithOption:(id)arg1 audioRecordContext:(id)arg2;	// IMP=0x0010000000092813
- (void)_stopPreviousRecognitionTaskIfNeededWithNewRequestId:(id)arg1;	// IMP=0x0010000000092723
- (void)prepareToStartSpeechRequestWithStartStreamOption:(id)arg1 audioRecordContext:(id)arg2 voiceTriggerInfo:(id)arg3;	// IMP=0x0010000000092419
- (void)_preheatWithLanguage:(id)arg1 preheatSource:(unsigned long long)arg2;	// IMP=0x0010000000092289
- (void)_preheatWithLanguage:(id)arg1 preheatSource:(unsigned long long)arg2 shouldDownloadMissingAsset:(_Bool)arg3;	// IMP=0x0010000000092200
- (void)preheatWithLanguage:(id)arg1 shouldDownloadMissingAsset:(_Bool)arg2;	// IMP=0x0010000000092145
- (void)start;	// IMP=0x0010000000091deb
- (void)_clearEndpointHint;	// IMP=0x0010000000091dbb
- (void)_enforceEndpointHintWithRequestId:(id)arg1 rcId:(unsigned long long)arg2 shouldAccept:(_Bool)arg3 featuresToLog:(id)arg4;	// IMP=0x0010000000091a7c
- (void)attSiriNode:(id)arg1 didDetectStartpointAtTime:(double)arg2;	// IMP=0x0010000000091a76
- (void)attSiriNode:(id)arg1 didDetectHardEndpointAtTime:(double)arg2 withMetrics:(id)arg3;	// IMP=0x0010000000091815
- (void)attSiriAudioSrcNodeDidStop:(id)arg1;	// IMP=0x0010000000091731
- (void)attSiriAudioSrcNodeLPCMRecordBufferAvailable:(id)arg1 audioChunk:(id)arg2;	// IMP=0x0010000000091540
- (void)attSiriAudioSrcNodeDidStartRecording:(id)arg1 successfully:(_Bool)arg2 error:(id)arg3;	// IMP=0x00100000000914a5
- (oneway void)sendSpeechCorrectionInfo:(id)arg1 interactionIdentifier:(id)arg2;	// IMP=0x000000000009137e
- (oneway void)resetCacheAndCompileAllAssets;	// IMP=0x0010000000091348
- (oneway void)resumeLocalRecognitionWithRequestId:(id)arg1 prefixText:(id)arg2 postfixText:(id)arg3 selectedText:(id)arg4;	// IMP=0x0010000000091165
- (oneway void)pauseLocalSpeechRecognitionForRequestId:(id)arg1;	// IMP=0x0010000000091040
- (oneway void)disableLocalSpeechRecognitionForRequestId:(id)arg1;	// IMP=0x0010000000090e30
- (oneway void)stopDeliverLocalSpeechRecognitionWithReason:(unsigned long long)arg1 requestId:(id)arg2;	// IMP=0x0010000000090be8
- (void)_startDeliverLocalSpeechRecognitionResultsWithRequestId:(id)arg1;	// IMP=0x0010000000090888
- (oneway void)startDeliverLocalSpeechRecognitionResultsWithSettings:(id)arg1;	// IMP=0x0010000000090612
- (oneway void)preheatLocalSpeechRecognitionWithLanguage:(id)arg1 source:(unsigned long long)arg2;	// IMP=0x00100000000904d9
- (void)_handleStopDeliverLocalSpeechRecognition;	// IMP=0x0010000000090482
- (void)_setRecordingStartTimeWithStartStreamOption:(id)arg1 audioRecordContext:(id)arg2 voiceTriggerInfo:(id)arg3;	// IMP=0x0010000000090321
- (void)_adjustEndpointStartTimeWithVoiceTriggerEvent:(id)arg1;	// IMP=0x001000000008feda
- (void)removeReceiver:(id)arg1;	// IMP=0x001000000008fce8
- (void)addReceiver:(id)arg1;	// IMP=0x001000000008fce2
- (void)stopWithReason:(unsigned long long)arg1;	// IMP=0x001000000008fb9d
- (void)stop;	// IMP=0x001000000008fb89
- (void)pause;	// IMP=0x001000000008fb83
- (id)initWithAttSiriController:(id)arg1 localSpeechRecognizer:(id)arg2 isFileLoggingEnabled:(_Bool)arg3;	// IMP=0x001000000008f9f9
- (id)initWithAttSiriController:(id)arg1;	// IMP=0x001000000008f968

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) CSAsset *prefetchedAsset;
@property(readonly) Class superclass;

@end

