//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSAudioCircularBuffer, NSString;

@interface CSAudioProcessWaitingBuffer : NSObject
{
    CSAudioCircularBuffer *_circularBuffer;	// 8 = 0x8
    NSString *_siriSessionUUID;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000008f940
@property(readonly, nonatomic) NSString *siriSessionUUID; // @synthesize siriSessionUUID=_siriSessionUUID;
@property(readonly, nonatomic) CSAudioCircularBuffer *circularBuffer; // @synthesize circularBuffer=_circularBuffer;
- (id)fetchAudioFromCircularBuffer;	// IMP=0x001000000008f885
- (void)addAudioChunk:(id)arg1;	// IMP=0x001000000008f7e2
- (void)dealloc;	// IMP=0x001000000008f73e
- (id)initWithSiriSessionUUID:(id)arg1;	// IMP=0x001000000008f5fb

@end

