//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CSScreenLockMonitor
{
}

+ (id)sharedInstance;	// IMP=0x004000000009c632
- (_Bool)isScreenLocked;	// IMP=0x000000000009c648
- (id)init;	// IMP=0x001000000009c63a

@end

