//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CSTrialAssetDownloadMonitor, NSString;

@interface CSSpeakerRecognitionAssetDownloadMonitor
{
    int _notifyToken;	// 8 = 0x8
    unsigned long long _lastUpdatedAssetType;	// 16 = 0x10
    CSTrialAssetDownloadMonitor *_trialAssetMonitor;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x0020000000009bc1
- (void).cxx_destruct;	// IMP=0x002000000000a0e9
@property(retain, nonatomic) CSTrialAssetDownloadMonitor *trialAssetMonitor; // @synthesize trialAssetMonitor=_trialAssetMonitor;
- (void)trialAssetDownloadMonitorDelegate:(id)arg1 didInstallNewAsset:(_Bool)arg2 assetType:(unsigned long long)arg3;	// IMP=0x001000000000a040
- (void)_notifyObserver:(id)arg1;	// IMP=0x0010000000009fdb
- (void)_didInstalledNewAsset;	// IMP=0x0010000000009efb
- (void)_stopMonitoring;	// IMP=0x0010000000009e58
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x0010000000009d26
- (const char *)_notificationKey;	// IMP=0x0010000000009d19
- (id)init;	// IMP=0x0010000000009c16

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

