//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CSSyncKeywordAnalyzerQuasarResult : NSObject
{
    double _triggerConfidence;	// 8 = 0x8
}

@property(nonatomic) double triggerConfidence; // @synthesize triggerConfidence=_triggerConfidence;
- (id)description;	// IMP=0x0010000000003501
- (id)initWithConfidence:(double)arg1;	// IMP=0x00100000000034be

@end

