//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol IDSDaemonMIGInterfaceDelegate, IDSXPCConnectionProtocol;

@interface IDSDaemonMIGInterface : NSObject
{
    id <IDSXPCConnectionProtocol> _server;	// 8 = 0x8
    int _notifyToken;	// 16 = 0x10
    id <IDSXPCConnectionProtocol> _serverSim2Host;	// 24 = 0x18
    id _delegate;	// 32 = 0x20
    _Bool _shuttingDown;	// 40 = 0x28
    _Bool _shuttingDownSim2Host;	// 41 = 0x29
}

+ (id)sharedInstance;	// IMP=0x00400000001e7870
- (void).cxx_destruct;	// IMP=0x00200000001e8fd0
@property __weak id <IDSDaemonMIGInterfaceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)shutDownSim2HostServer;	// IMP=0x00100000001e8f10
- (void)launchSim2HostServer;	// IMP=0x00100000001e8f00
- (void)denyIncomingGrantRequests;	// IMP=0x00100000001e8e80
- (void)acceptIncomingGrantRequests;	// IMP=0x00100000001e8d90
- (void)__setupServer;	// IMP=0x00100000001e7930

@end

