//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <FTServices/FTIDSMessage.h>

@class NSArray;

@interface IDSGetDependentRegistrationMessage : FTIDSMessage
{
    NSArray *_responseRegistrations;	// 232 = 0xe8
}

- (void).cxx_destruct;	// IMP=0x0020000000740b70
@property(copy) NSArray *responseRegistrations; // @synthesize responseRegistrations=_responseRegistrations;
- (void)handleResponseDictionary:(id)arg1;	// IMP=0x00100000007409f0
- (_Bool)requiresPushTokenKeys;	// IMP=0x00100000007409d0
- (id)messageBody;	// IMP=0x0010000000740890
- (id)requiredKeys;	// IMP=0x0010000000740830
- (id)bagKey;	// IMP=0x00100000007407f0
- (double)anisetteHeadersTimeout;	// IMP=0x00100000007407d0
- (int)maxTimeoutRetries;	// IMP=0x00100000007407b0
- (_Bool)wantsExtraTimeoutRetry;	// IMP=0x0010000000740790
- (long long)responseCommand;	// IMP=0x0010000000740770
- (long long)command;	// IMP=0x0010000000740750
- (_Bool)wantsBinaryPush;	// IMP=0x0010000000740730
- (_Bool)wantsCompressedBody;	// IMP=0x0010000000740710
- (_Bool)wantsHTTPHeaders;	// IMP=0x00100000007406f0
- (_Bool)wantsBagKey;	// IMP=0x00100000007406d0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000007405d0
- (id)init;	// IMP=0x00100000007404a0

@end

