//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface IDSGroupSessionMultiplexer : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00400000001950f0
- (_Bool)unregisterMultiplexerTransport:(id)arg1;	// IMP=0x0040000000195150
- (_Bool)registerMultiplexerTransport:(id)arg1;	// IMP=0x0010000000195100

@end

