//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface IDSProtoApplicationKeyEntry : PBCodable
{
    int _keyIndex;	// 8 = 0x8
    NSData *_publicIdentity;	// 16 = 0x10
    struct {
        unsigned int keyIndex:1;
    } _has;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000006fd5f0
@property(retain, nonatomic) NSData *publicIdentity; // @synthesize publicIdentity=_publicIdentity;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000006fd4c0
- (unsigned long long)hash;	// IMP=0x00100000006fd3f0
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000006fd220
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000006fd110
- (void)copyTo:(id)arg1;	// IMP=0x00100000006fd040
- (void)writeTo:(id)arg1;	// IMP=0x00100000006fcf90
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000006fcf30
- (id)dictionaryRepresentation;	// IMP=0x00100000006fc6c0
- (id)description;	// IMP=0x00100000006fc5f0
@property(readonly, nonatomic) _Bool hasPublicIdentity;
- (int)StringAsKeyIndex:(id)arg1;	// IMP=0x00100000006fc4d0
- (id)keyIndexAsString:(int)arg1;	// IMP=0x00100000006fc420
@property(nonatomic) _Bool hasKeyIndex;
@property(nonatomic) int keyIndex; // @synthesize keyIndex=_keyIndex;

@end

