//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;
@protocol IDSTemporaryPhoneUserExpirationManagerDelegate;

@interface IDSTemporaryPhoneUserExpirationManager : NSObject
{
    struct os_unfair_lock_s _usersToTimersLock;	// 8 = 0x8
    id <IDSTemporaryPhoneUserExpirationManagerDelegate> _delegate;	// 16 = 0x10
    NSMutableDictionary *_usersToTimers;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000001781e0
@property(retain, nonatomic) NSMutableDictionary *usersToTimers; // @synthesize usersToTimers=_usersToTimers;
@property(nonatomic) struct os_unfair_lock_s usersToTimersLock; // @synthesize usersToTimersLock=_usersToTimersLock;
@property(nonatomic) __weak id <IDSTemporaryPhoneUserExpirationManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)userStore:(id)arg1 didRemoveAuthenticationCertificateForUser:(id)arg2;	// IMP=0x0010000000178080
- (void)userStore:(id)arg1 didAddAuthenticationCertificate:(id)arg2 forUser:(id)arg3;	// IMP=0x0010000000177ff0
- (void)userStore:(id)arg1 didRemoveUser:(id)arg2 withAuthenticationCertificate:(id)arg3;	// IMP=0x0010000000177f50
- (void)userStore:(id)arg1 didUpdateUser:(id)arg2;	// IMP=0x0010000000177ed0
- (void)userStore:(id)arg1 didAddUser:(id)arg2;	// IMP=0x0010000000177e50
- (void)_expireTimer:(id)arg1;	// IMP=0x0010000000177a50
- (void)_cancelExpirationTimerForUser:(id)arg1;	// IMP=0x0010000000177830
- (void)_kickoffExpirationTimerForInfo:(id)arg1;	// IMP=0x0010000000177360
- (void)_attemptToKickoffExpirationTimerForUser:(id)arg1;	// IMP=0x0010000000177250
- (id)initWithUserStore:(id)arg1 delegate:(id)arg2;	// IMP=0x0010000000176eb0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

