//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSPhoneUser, NSDate, NSString;

@interface IDSTemporaryPhoneUser : NSObject
{
    _Bool _hasBeenProvisioned;	// 8 = 0x8
    _Bool _finishedRegistration;	// 9 = 0x9
    _Bool _hasNotifiedSuccess;	// 10 = 0xa
    NSDate *_expirationDate;	// 16 = 0x10
    IDSPhoneUser *_phoneUser;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000212370
- (void).cxx_destruct;	// IMP=0x0020000000212bc0
@property(retain, nonatomic) IDSPhoneUser *phoneUser; // @synthesize phoneUser=_phoneUser;
@property(nonatomic) _Bool hasNotifiedSuccess; // @synthesize hasNotifiedSuccess=_hasNotifiedSuccess;
@property(nonatomic) _Bool finishedRegistration; // @synthesize finishedRegistration=_finishedRegistration;
@property(nonatomic) _Bool hasBeenProvisioned; // @synthesize hasBeenProvisioned=_hasBeenProvisioned;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000212790
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000002125d0
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000212390
- (_Bool)isIdenticalToUser:(id)arg1;	// IMP=0x0010000000212190
- (_Bool)isEqualToUser:(id)arg1;	// IMP=0x0010000000212130
- (_Bool)isEqualToTemporaryPhoneUser:(id)arg1;	// IMP=0x0010000000211fa0
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000211f00
@property(readonly) unsigned long long hash;
- (_Bool)shouldReplace:(id)arg1;	// IMP=0x0010000000211e50
@property(readonly, nonatomic) NSString *labelID;
@property(readonly, nonatomic) NSString *networkCode;
@property(readonly, nonatomic) NSString *countryCode;
@property(readonly, nonatomic) NSString *phoneNumber;
- (id)storageIdentifier;	// IMP=0x0010000000211b40
- (id)unprefixedIdentifier;	// IMP=0x0010000000211ad0
- (id)realmPrefixedIdentifier;	// IMP=0x0010000000211a60
- (long long)realm;	// IMP=0x0010000000211a40
- (id)uniqueIdentifier;	// IMP=0x00100000002118f0
- (id)temporaryPhoneUserWithNotifiedSuccess;	// IMP=0x0010000000211870
- (id)temporaryPhoneUserWithFinishedRegistration;	// IMP=0x00100000002117f0
- (id)temporaryPhoneUserWithUpdatedExpirationDate:(id)arg1;	// IMP=0x0010000000211720
- (id)initWithPhoneUser:(id)arg1 expirationDate:(id)arg2 finishedRegistration:(_Bool)arg3;	// IMP=0x0010000000211610
- (id)initWithPhoneUser:(id)arg1;	// IMP=0x0010000000211540

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

