//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOSQLiteDB, NSString;

@interface GEOAnalyticsPipelinePersistence : NSObject
{
    GEOSQLiteDB *_db;	// 8 = 0x8
    _Bool _shadowEnabled;	// 16 = 0x10
    NSString *_dbFilePath;	// 24 = 0x18
    _Bool _firstAuthComplete;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x00200000000241ee
- (void).cxx_destruct;	// IMP=0x00100000000281ab
- (void)processMapsAppDeletion;	// IMP=0x001000000002806e
- (void)clearAllData;	// IMP=0x0010000000027fd8
- (void)clearPendingLogMsgElemsForBatchUploadWithBatchId:(unsigned long long)arg1;	// IMP=0x0010000000027e2d
- (void)clearExpiredLogMsgsWithResultBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000027833
- (void)selectDailySettingsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000273b7
- (void)selectDailyCountsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000026e63
- (void)selectCurCollViewsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000026959
- (void)selectLogMsgsForBatchUploadWithBatchId:(unsigned long long)arg1 visitorBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000026416
- (id)selectBatchIdsForBatchUpload;	// IMP=0x0010000000026216
- (void)storeLogMsgElems:(id)arg1;	// IMP=0x0010000000025e13
- (void)_writeRRLogElem:(id)arg1;	// IMP=0x0010000000025c7e
- (void)_writeDailySettingsElem:(id)arg1;	// IMP=0x0010000000025a94
- (void)_writeCuratedCollectionElem:(id)arg1;	// IMP=0x0010000000025628
- (void)_writeDailyCountElem:(id)arg1;	// IMP=0x00100000000251ef
- (void)_writeLogMsgQueueElem:(id)arg1;	// IMP=0x0010000000024e47
- (long long)_analyticsCount;	// IMP=0x0010000000024d27
- (void)tearDown;	// IMP=0x0010000000024cba
- (void)dealloc;	// IMP=0x0010000000024c7c
- (void)_setupEvalStmtsOnDb:(id)arg1;	// IMP=0x0010000000024b1e
- (void)_configureDatabase;	// IMP=0x001000000002447b
@property(readonly, nonatomic) _Bool evalModeEnabled;
- (void)protectedDataDidBecomeAvailable:(id)arg1;	// IMP=0x0010000000024460
@property(nonatomic) _Bool firstAuthComplete;
- (id)initWithDBFilePath:(id)arg1;	// IMP=0x00100000000242eb
- (id)init;	// IMP=0x0010000000024243
- (void)showEvalDataWithVisitorBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000029664
- (void)flushEvalData;	// IMP=0x00100000000295c0
- (void)setEvalMode:(_Bool)arg1;	// IMP=0x0010000000029523

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

