//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOSQLiteDB, NSArray, NSMutableDictionary, NSMutableOrderedSet;
@protocol GEOPDPlaceCacheManifestInfoProviding, GEOPDPlaceCacheSchedulingDelegate, OS_dispatch_source;

@interface GEOPDPlaceCache : NSObject
{
    GEOSQLiteDB *_db;	// 8 = 0x8
    id <GEOPDPlaceCacheSchedulingDelegate> _schedulingDelegate;	// 16 = 0x10
    id <GEOPDPlaceCacheManifestInfoProviding> _manifestInfoProvider;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_cleanupTimer;	// 32 = 0x20
    NSMutableDictionary *_accessTimesDict;	// 40 = 0x28
    NSMutableOrderedSet *_recentlySeenPlaceHashes;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000013d43
@property(readonly, nonatomic) NSArray *serviceVersions;
- (void)cancelCleanupBlockSchedule;	// IMP=0x0010000000013be9
- (void)runCleanupBlock:(CDUnknownBlockType)arg1 inSecondsFromNow:(long long)arg2;	// IMP=0x00100000000139fe
- (long long)currentTime;	// IMP=0x00100000000139df
- (id)internalSerialQueue;	// IMP=0x00100000000139c9
- (void)iterateAllHandleKeysWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000013925
- (void)iterateAllPhoneKeysWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000013881
- (void)iterateAllBasemapIdKeysWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000137dd
- (void)iterateAllMUIDKeysWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000013739
- (void)iterateAllKeysWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000001371f
- (void)_iterateAllKeysFilteringCacheKeyWithPredicate:(id)arg1 entryBlock:(CDUnknownBlockType)arg2 finishedBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000013437
- (void)iterateHandlePlacesWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000013393
- (void)iteratePhonePlacesWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000132ef
- (void)iterateBasemapIdPlacesWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000001324b
- (void)iterateMUIDPlacesWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000131a7
- (void)iterateAllPlacesWithBlock:(CDUnknownBlockType)arg1 finishedBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000001318d
- (void)_iterateAllPlacesFilteringCacheKeyWithPredicate:(id)arg1 entryBlock:(CDUnknownBlockType)arg2 finishedBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000012e24
- (void)close;	// IMP=0x0010000000012db7
- (void)_evictPlaceWithHash:(id)arg1;	// IMP=0x0010000000012b3c
- (void)periodicCleanupAndAccessTimeUpdate;	// IMP=0x0010000000012519
- (void)scheduleCleanup;	// IMP=0x001000000001240f
- (void)enqueueAccessTimeUpdateForCacheKey:(id)arg1 accessTime:(long long)arg2;	// IMP=0x001000000001228a
- (void)evictAllEntries;	// IMP=0x00100000000120de
- (void)deletePhoneNumberMapping;	// IMP=0x0010000000011f51
- (unsigned long long)_shrinkBySize:(unsigned long long)arg1;	// IMP=0x0010000000011d70
- (unsigned long long)shrinkBySizeSync:(unsigned long long)arg1;	// IMP=0x0010000000011c20
- (void)shrinkBySize:(unsigned long long)arg1 finished:(CDUnknownBlockType)arg2;	// IMP=0x001000000001199b
- (unsigned long long)_calculateFreeableSpace;	// IMP=0x0010000000011874
- (unsigned long long)calculateFreeableSpaceSync;	// IMP=0x0010000000011733
- (void)calculateFreeableSpaceWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000001156a
- (id)lookupIdentifierByPhoneNumber:(id)arg1;	// IMP=0x0010000000010fd8
- (void)lookupPlaceByHandle:(id)arg1 allowExpired:(_Bool)arg2 resultBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000010be8
- (void)lookupPlaceByIdentifier:(id)arg1 allowExpired:(_Bool)arg2 resultBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000010588
- (void)lookupPlaceByPhoneNumber:(id)arg1 allowExpired:(_Bool)arg2 resultBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000010187
- (void)lookupPlaceByRequest:(id)arg1 allowExpired:(_Bool)arg2 resultBlock:(CDUnknownBlockType)arg3;	// IMP=0x001000000000fbf9
- (void)_lookupPlaceByRequestKey:(id)arg1 allowExpiredPlace:(_Bool)arg2 resultBlock:(CDUnknownBlockType)arg3;	// IMP=0x001000000000f5d1
- (void)storePlace:(id)arg1 forRequest:(id)arg2 completionQueue:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000000ef93
- (void)storePlace:(id)arg1 forRequest:(id)arg2;	// IMP=0x001000000000eec2
- (void)trackPlace:(id)arg1 completionQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000000e9fd
- (void)trackPlace:(id)arg1;	// IMP=0x001000000000e947
- (id)_cacheKeyForHandle:(id)arg1;	// IMP=0x001000000000e88b
- (id)_cacheKeysForPlace:(id)arg1 request:(id)arg2;	// IMP=0x001000000000e4ea
- (void)_storePlace:(id)arg1 withHash:(id)arg2 forRequestKeys:(id)arg3;	// IMP=0x001000000000d868
- (_Bool)_meetsManifestVersionPolicyForPlace:(id)arg1;	// IMP=0x001000000000d59f
- (_Bool)_deleteAndResetDB:(id)arg1;	// IMP=0x001000000000d374
- (_Bool)_validateDBLocaleAndResetIfNecessary;	// IMP=0x001000000000cff8
- (void)dealloc;	// IMP=0x001000000000cf83
- (id)initWithCacheFilePath:(id)arg1 schedulingDelegate:(id)arg2 manifestInfoProvider:(id)arg3;	// IMP=0x001000000000cb34

@end

