//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface APSMessageStore : NSObject
{
    _Bool _databaseOpen;	// 8 = 0x8
    _Bool _pendingDatabaseClose;	// 9 = 0x9
}

+ (id)sharedInstance;	// IMP=0x0040000000089f4a
- (id)_onQueueSubscribedChannelsForRecords:(struct __CFArray *)arg1;	// IMP=0x002000000008d545
- (id)_onQueueSubscribedChannelsForRecord:(struct _APSChannelRecordStruct *)arg1;	// IMP=0x001000000008d4a8
- (id)allRegisteredChannels;	// IMP=0x001000000008d2fb
- (id)allRegisteredChannelsForEnvironment:(id)arg1 tokenName:(id)arg2;	// IMP=0x001000000008d0bd
- (id)allRegisteredChannelsForTopic:(id)arg1 environment:(id)arg2 tokenName:(id)arg3;	// IMP=0x001000000008cd20
- (id)lookupChannelWithChannelID:(id)arg1 andPushTopic:(id)arg2 environment:(id)arg3 tokenName:(id)arg4;	// IMP=0x001000000008c914
- (void)updateChannel:(id)arg1;	// IMP=0x001000000008c812
- (void)deleteChannelID:(id)arg1 forTopic:(id)arg2 environment:(id)arg3 tokenName:(id)arg4;	// IMP=0x001000000008c61c
- (void)storeChannel:(id)arg1;	// IMP=0x001000000008c3b3
- (void)markAllOutgoingMessagesAsUnsent;	// IMP=0x001000000008c390
- (void)markMessageWithGUID:(id)arg1 asSent:(_Bool)arg2;	// IMP=0x001000000008c1e6
- (void)deleteOutgoingMessageWithGUID:(id)arg1;	// IMP=0x001000000008c0c0
- (id)storeOutgoingMessage:(id)arg1 environment:(id)arg2;	// IMP=0x001000000008bccc
- (id)incomingHighPriorityMessagesForEnvironment:(id)arg1 pushTokens:(id)arg2;	// IMP=0x001000000008bcad
- (id)incomingMessagesForTopic:(id)arg1 priority:(long long)arg2 environment:(id)arg3 pushTokens:(id)arg4;	// IMP=0x001000000008b857
- (id)_onQueueIncomingMessagesFromRecords:(struct __CFArray *)arg1;	// IMP=0x001000000008b38e
- (id)pendingLowPriorityIncomingMessageTopicsForEnvironment:(id)arg1 pushTokens:(id)arg2;	// IMP=0x001000000008b071
- (void)deleteStaleIncomingLowPriorityMessagesForEnvironment:(id)arg1;	// IMP=0x001000000008af69
- (void)deleteLowPriorityIncomingMessagesForTopic:(id)arg1 environment:(id)arg2 pushTokens:(id)arg3;	// IMP=0x001000000008ae5d
- (void)_onQueueDeleteLowPriorityIncomingMessagesForTopic:(id)arg1 environment:(id)arg2 pushTokens:(id)arg3;	// IMP=0x001000000008ac21
- (void)deleteIncomingMessageWithGUID:(id)arg1;	// IMP=0x001000000008ab87
- (void)storeIncomingMessage:(id)arg1 environment:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x001000000008a6e3
- (void)performBlock:(CDUnknownBlockType)arg1 waitUntilDone:(_Bool)arg2;	// IMP=0x001000000008a5c9
- (void)performBlock:(CDUnknownBlockType)arg1 afterDelay:(double)arg2;	// IMP=0x001000000008a4b0
- (void)performBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000008a39f
- (void)openDatabase;	// IMP=0x001000000008a309
- (void)closeDatabase;	// IMP=0x001000000008a284
- (void)_setDatabaseCloseTimer;	// IMP=0x001000000008a23a
- (void)_clearDatabaseCloseTimer;	// IMP=0x001000000008a1ff
- (void)__closeDatabase;	// IMP=0x001000000008a0ec
- (id)init;	// IMP=0x0010000000089f9f

@end

