//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class MISSING_TYPE, NSMutableArray;

@interface PSChannelSubscriptionsRequestPayload : PBCodable
{
    unsigned long long _sequenceNumber;	// 8 = 0x8
    NSMutableArray *_appChannelSubscriptions;	// 16 = 0x10
    int _subscriptionsType;	// 24 = 0x18
    int _version;	// 28 = 0x1c
    struct {
        unsigned int sequenceNumber:1;
        unsigned int subscriptionsType:1;
        unsigned int version:1;
    } _has;	// 32 = 0x20
}

+ (Class)appChannelSubscriptionsType;	// IMP=0x0010000000043971
+ (id)createPayloadForSubscriptionChannels:(id)arg1 unsubscriptionChannels:(id)arg2 subscriptionType:(int)arg3;	// IMP=0x0010000000018c1b
- (void).cxx_destruct;	// IMP=0x0020000000044b75
@property(nonatomic) unsigned long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(retain, nonatomic) NSMutableArray *appChannelSubscriptions; // @synthesize appChannelSubscriptions=_appChannelSubscriptions;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000044975
- (unsigned long long)hash;	// IMP=0x00100000000448e3
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000447ca
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000004458e
- (void)copyTo:(id)arg1;	// IMP=0x0010000000044470
- (MISSING_TYPE *)writeTo: /* Error: Ran out of types for this method. */;	// IMP=0x00100000000442c1
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000442b4
- (id)dictionaryRepresentation;	// IMP=0x0010000000043b96
- (id)description;	// IMP=0x0010000000043ae7
@property(nonatomic) _Bool hasSequenceNumber;
- (int)StringAsSubscriptionsType:(id)arg1;	// IMP=0x0010000000043a3f
- (id)subscriptionsTypeAsString:(int)arg1;	// IMP=0x00100000000439ea
@property(nonatomic) _Bool hasSubscriptionsType;
@property(nonatomic) int subscriptionsType; // @synthesize subscriptionsType=_subscriptionsType;
- (id)appChannelSubscriptionsAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000043954
- (unsigned long long)appChannelSubscriptionsCount;	// IMP=0x0010000000043937
- (void)addAppChannelSubscriptions:(id)arg1;	// IMP=0x00100000000438cd
- (void)clearAppChannelSubscriptions;	// IMP=0x00100000000438b0
- (int)StringAsVersion:(id)arg1;	// IMP=0x001000000004388e
- (id)versionAsString:(int)arg1;	// IMP=0x0010000000043849
@property(nonatomic) _Bool hasVersion;
@property(nonatomic) int version; // @synthesize version=_version;

@end

