//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray;

@interface PSChannelSubscriptionsResponsePayload : PBCodable
{
    NSMutableArray *_appChannelSubscriptionResponses;	// 8 = 0x8
}

+ (Class)appChannelSubscriptionResponseType;	// IMP=0x002000000000d54b
- (void).cxx_destruct;	// IMP=0x002000000000dfd9
@property(retain, nonatomic) NSMutableArray *appChannelSubscriptionResponses; // @synthesize appChannelSubscriptionResponses=_appChannelSubscriptionResponses;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000000de7f
- (unsigned long long)hash;	// IMP=0x001000000000de62
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000ddc8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000dc05
- (void)copyTo:(id)arg1;	// IMP=0x001000000000db3e
- (void)writeTo:(id)arg1;	// IMP=0x001000000000da0e
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000000da01
- (id)dictionaryRepresentation;	// IMP=0x001000000000d60b
- (id)description;	// IMP=0x001000000000d55c
- (id)appChannelSubscriptionResponseAtIndex:(unsigned long long)arg1;	// IMP=0x001000000000d52e
- (unsigned long long)appChannelSubscriptionResponsesCount;	// IMP=0x001000000000d511
- (void)addAppChannelSubscriptionResponse:(id)arg1;	// IMP=0x001000000000d4a7
- (void)clearAppChannelSubscriptionResponses;	// IMP=0x001000000000d48a

@end

