//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface TASKNotifyAck : PBCodable
{
}

- (void)mergeFrom:(id)arg1;	// IMP=0x0040000000071f70
- (unsigned long long)hash;	// IMP=0x0010000000071f68
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000071f23
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000071eea
- (void)copyTo:(id)arg1;	// IMP=0x0010000000071ee4
- (void)writeTo:(id)arg1;	// IMP=0x0010000000071ede
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000071ed1
- (id)dictionaryRepresentation;	// IMP=0x0010000000071db3
- (id)description;	// IMP=0x0010000000071d04

@end

