//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class TASKResponse;

@interface TASKControlResponse : PBCodable
{
    TASKResponse *_create;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000089f37
@property(retain, nonatomic) TASKResponse *create; // @synthesize create=_create;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000089eb5
- (unsigned long long)hash;	// IMP=0x0010000000089e98
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000089dfe
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000089d86
- (void)copyTo:(id)arg1;	// IMP=0x0010000000089d5c
- (void)writeTo:(id)arg1;	// IMP=0x0010000000089d38
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000089d2b
- (id)dictionaryRepresentation;	// IMP=0x0010000000089ae7
- (id)description;	// IMP=0x0010000000089a38
@property(readonly, nonatomic) _Bool hasCreate;

@end

