//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, SQLiteConnection;

@interface InAppReceiptDatabaseSession : NSObject
{
    SQLiteConnection *_connection;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000003576e
@property(readonly) SQLiteConnection *connection; // @synthesize connection=_connection;
- (id)_latestTransactionReceiptForUnarchivedRenewalInfo:(id)arg1 subscriptionGroupID:(id)arg2 bundleID:(id)arg3 outProductID:(id *)arg4;	// IMP=0x00100000000353d7
- (id)_statusesForRenewalInfoBlob:(id)arg1 subscriptionGroupID:(id)arg2 bundleID:(id)arg3;	// IMP=0x0010000000035080
- (id)_propertyForKey:(id)arg1 bundleID:(id)arg2;	// IMP=0x0010000000034e21
- (id)_inAppPendingTransactionsPropertyForKey:(id)arg1 bundleID:(id)arg2;	// IMP=0x0010000000034bc2
- (id)pendingLegacyTransactionsLastUpdatedForBundleID:(id)arg1;	// IMP=0x0010000000034ba3
- (id)pendingLegacyTransactionsAccountTokenForBundleID:(id)arg1;	// IMP=0x0010000000034b84
- (id)pendingLegacyTransactionsForBundleID:(id)arg1 logKey:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000034404
- (id)transactionForID:(id)arg1 bundleID:(id)arg2;	// IMP=0x001000000003417a
- (id)subscriptionStatusForSubscriptionGroupID:(id)arg1 bundleID:(id)arg2;	// IMP=0x0010000000033bd0
- (id)lastUpdatedForBundleID:(id)arg1;	// IMP=0x0010000000033bb1
- (_Bool)isTransactionFinishedForID:(id)arg1 bundleID:(id)arg2;	// IMP=0x0010000000033b64
- (void)enumerateUnfinishedTransactionReceiptsForBundleID:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000033842
- (void)enumerateReceiptsForSubscriptionsInGracePeriodForBundleID:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000032ea8
- (void)enumerateReceiptsForProductID:(id)arg1 bundleID:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000032b53
- (void)enumerateCurrentReceiptsForProductID:(id)arg1 bundleID:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000032070
- (id)currentRevisionForBundleID:(id)arg1;	// IMP=0x0010000000032051
- (id)appTransactionForBundleID:(id)arg1 bundleVersion:(id)arg2 accountToken:(id)arg3;	// IMP=0x0010000000031cc8
- (id)accountTokenForBundleID:(id)arg1;	// IMP=0x0010000000031ca9
- (id)initWithConnection:(id)arg1;	// IMP=0x0010000000031c3e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

