//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, SQLiteConnection;

@interface SQLiteStatement : NSObject
{
    SQLiteConnection *_connection;	// 8 = 0x8
    struct sqlite3_stmt *_statement;	// 16 = 0x10
    SQLiteStatement *_strongSelf;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000881d7
@property(readonly, nonatomic) struct sqlite3_stmt *sqlite3_stmt; // @synthesize sqlite3_stmt=_statement;
@property(readonly, nonatomic) SQLiteConnection *connection; // @synthesize connection=_connection;
- (int)clearBindings;	// IMP=0x00100000000881a9
- (void)bindURL:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000088155
- (void)bindUUID:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000088101
- (void)bindStringCopy:(id)arg1 atPosition:(int)arg2;	// IMP=0x001000000008808d
- (void)bindString:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087f84
- (void)bindNumber:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087e97
- (void)bindNullAtPosition:(int)arg1;	// IMP=0x0010000000087e5a
- (void)bindInt64:(long long)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087e1d
- (void)bindInt:(int)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087de0
- (void)bindFloat:(float)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087d9f
- (void)bindDouble:(double)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087d62
- (void)bindDictionary:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087d05
- (void)bindDate:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087cc5
- (void)bindDataCopy:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087c14
- (void)bindData:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087b67
- (void)bindArray:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000087b0a
- (int)step;	// IMP=0x0010000000087ac9
@property(readonly, copy, nonatomic) NSString *SQL;
- (int)reset;	// IMP=0x0010000000087a45
@property(readonly, nonatomic, getter=isReadOnly) _Bool readOnly;
- (int)finalizeStatement;	// IMP=0x00100000000879c6
@property(readonly, copy, nonatomic) NSDictionary *columnIndexByName;
- (id)initWithStatement:(struct sqlite3_stmt *)arg1 onConnection:(id)arg2;	// IMP=0x00100000000877f7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

