//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIApplication.h>

@interface AXUIServerApplication : UIApplication
{
}

- (id)_accessibilityIsolatedWindows;	// IMP=0x00400000000015d0
- (struct CGRect)accessibilityFrame;	// IMP=0x0010000000001540
- (long long)_accessibilityOrientationForCompareGeometry;	// IMP=0x0010000000001510
- (_Bool)_accessibilityUseWindowBoundsForOutOfBoundsChecking;	// IMP=0x00100000000014f0
- (_Bool)_accessibilityIsAccessibilityUIServer;	// IMP=0x00100000000014d0
- (_Bool)_accessibilityIsLaunchAngel;	// IMP=0x00100000000014b0
- (_Bool)_shouldAllowKeyboardArbiter;	// IMP=0x0010000000001490
- (id)accessibilityLabel;	// IMP=0x0010000000001470
- (void)sendEvent:(id)arg1;	// IMP=0x00100000000013b0
- (id)init;	// IMP=0x00100000000012a0

@end

