//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE, NSArray;

@interface _TtC22HomeCaptiveViewService25TwoUpColumnViewController : UIViewController
{
    MISSING_TYPE *accessoryViewController;	// 8 = 0x8
    MISSING_TYPE *dialogueViewController;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00400000000081f0
- (void)viewDidLoad;	// IMP=0x00100000000079c0
@property(nonatomic, readonly) NSArray *preferredFocusEnvironments;
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000078e0
- (id)init;	// IMP=0x0010000000007890
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000007840

@end

