//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface AKPostInstallService : NSObject
{
}

+ (id)sharedService;	// IMP=0x0040000000029fa3
- (void)_performPostInstallWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x004000000002a329
- (void)start;	// IMP=0x0010000000029ff8

@end

