//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ADRapportLinkDiscoveryOptions, NSString;

@interface _ADRapportLinkDiscoveryOptionsMutation : NSObject
{
    ADRapportLinkDiscoveryOptions *_base;	// 8 = 0x8
    long long _includesFamily;	// 16 = 0x10
    long long _includesHome;	// 24 = 0x18
    long long _includesRemoraDevices;	// 32 = 0x20
    struct _mutationFlags {
        unsigned int isDirty:1;
        unsigned int hasIncludesFamily:1;
        unsigned int hasIncludesHome:1;
        unsigned int hasIncludesRemoraDevices:1;
    } _mutationFlags;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000000fac18
- (void)setIncludesRemoraDevices:(long long)arg1;	// IMP=0x00100000000fac0a
- (long long)getIncludesRemoraDevices;	// IMP=0x00100000000fabe8
- (void)setIncludesHome:(long long)arg1;	// IMP=0x00100000000fabda
- (long long)getIncludesHome;	// IMP=0x00100000000fabb8
- (void)setIncludesFamily:(long long)arg1;	// IMP=0x00100000000fabaa
- (long long)getIncludesFamily;	// IMP=0x00100000000fab88
- (_Bool)isDirty;	// IMP=0x00100000000fab7d
- (id)initWithBase:(id)arg1;	// IMP=0x00100000000fab12

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

