//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface ADCommunalDeviceUserAttributes : NSObject
{
    NSMutableArray *_attributes;	// 8 = 0x8
}

+ (id)saCopy:(id)arg1;	// IMP=0x00400000001b5f4e
- (void).cxx_destruct;	// IMP=0x00200000001b6165
- (id)attributes;	// IMP=0x00100000001b5f30
- (void)deleteAttribute:(unsigned long long)arg1;	// IMP=0x00100000001b5edc
- (void)addAttribute:(unsigned long long)arg1;	// IMP=0x00100000001b5e88
- (id)initWithAttribute:(unsigned long long)arg1;	// IMP=0x00100000001b5ddb

@end

