//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ADClientLiteListener, ADExternalRequestListener, ADPeerLocationRemote, ADSiriConnectionRemote, ADSiriTetherListener, AFInstanceContext, MISSING_TYPE, NSCountedSet, NSMutableSet, NSString, NSXPCListener;
@protocol OS_dispatch_queue, OS_xpc_object;

@interface ADDaemon : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSXPCListener *_analyticsListener;	// 16 = 0x10
    NSXPCListener *_analyticsObservationListener;	// 24 = 0x18
    NSXPCListener *_clientListener;	// 32 = 0x20
    NSXPCListener *_dictationListener;	// 40 = 0x28
    NSXPCListener *_settingsListener;	// 48 = 0x30
    NSXPCListener *_synapseSyncListener;	// 56 = 0x38
    NSXPCListener *_managedStorageListener;	// 64 = 0x40
    NSXPCListener *_securityListener;	// 72 = 0x48
    NSXPCListener *_notificationServiceListener;	// 80 = 0x50
    NSXPCListener *_audioSessionAssertionServiceListener;	// 88 = 0x58
    NSObject<OS_xpc_object> *_syncListener;	// 96 = 0x60
    ADExternalRequestListener *_externalRequestListener;	// 104 = 0x68
    ADClientLiteListener *_clientLiteListener;	// 112 = 0x70
    ADSiriTetherListener *_siriTetherListener;	// 120 = 0x78
    unsigned long long _lastSyncRequested;	// 128 = 0x80
    NSMutableSet *_syncReasonsQueued;	// 136 = 0x88
    _Bool _syncActivityRegistered;	// 144 = 0x90
    _Bool _syncUrgentActivityRegistered;	// 145 = 0x91
    ADSiriConnectionRemote *_proxyRemote;	// 152 = 0x98
    ADPeerLocationRemote *_peerLocationManagerRemote;	// 160 = 0xa0
    _Bool _unlockedWorkQueueIsSuspended;	// 168 = 0xa8
    NSObject<OS_dispatch_queue> *_unlockedWorkQueue;	// 176 = 0xb0
    NSObject<OS_dispatch_queue> *_dictationListenerQueue;	// 184 = 0xb8
    NSCountedSet *_dictationPidSet;	// 192 = 0xc0
    NSObject<OS_dispatch_queue> *_trialExperimentsQueue;	// 200 = 0xc8
    struct MGNotificationTokenStruct *_mg_notification_token;	// 208 = 0xd0
    AFInstanceContext *_instanceContext;	// 216 = 0xd8
}

+ (unsigned long long)processLaunchMachTime;	// IMP=0x00200000000b8736
+ (double)processLaunchTime;	// IMP=0x00100000000b8728
+ (id)sharedDaemon;	// IMP=0x00100000000b867d
- (void).cxx_destruct;	// IMP=0x00200000000bea90
- (void)_setupOfflineDictationStatusObserver;	// IMP=0x00100000000bea6e
- (void)scheduleUnlockedWork:(CDUnknownBlockType)arg1;	// IMP=0x00100000000be93c
- (void)scheduleValidationRefreshForInterval:(double)arg1;	// IMP=0x00100000000be932
- (void)unscheduleDestroyJob;	// IMP=0x00100000000be928
- (void)scheduleDestroyJob;	// IMP=0x00100000000be91e
- (void)_syncForReason:(id)arg1 withCoalescing:(_Bool)arg2;	// IMP=0x00100000000be6da
- (void)syncForReason:(id)arg1 withCoalescing:(_Bool)arg2;	// IMP=0x00100000000be622
- (void)_syncCoalesced;	// IMP=0x00100000000be42a
- (void)_syncUrgently:(id)arg1;	// IMP=0x00100000000be1e4
- (void)_setupSessionLanguage;	// IMP=0x00100000000be1a0
- (void)_daemonWillShutdown;	// IMP=0x00100000000be0a7
- (void)_daemonDidLaunchWithContext:(id)arg1;	// IMP=0x00100000000bd951
- (void)_setupAudioSessionAssertionAcquisitionService;	// IMP=0x00100000000bd8e9
- (void)_setupCacheDelete;	// IMP=0x00100000000bd25f
- (void)_setupNanoPreferences;	// IMP=0x00100000000bd259
- (void)_setupWirelessCoexManagerSubscription;	// IMP=0x00100000000bd253
- (void)_setupMemoryPressureObservation;	// IMP=0x00100000000bd24d
- (MISSING_TYPE *)_setupMultiUserCloudSyncer;	// IMP=0x00100000000bd247
- (void)_setupCloudKit;	// IMP=0x00100000000bd241
- (void)_setupHomeKit;	// IMP=0x00100000000bd21f
- (void)_setupPairedSync;	// IMP=0x00100000000bd219
- (void)_setupClientLiteListener;	// IMP=0x00100000000bd1df
- (void)_setupExternalRequestListener;	// IMP=0x00100000000bd1a0
- (void)_setupTetherListener;	// IMP=0x00100000000bd166
- (void)_registerForSyncNotifications;	// IMP=0x00100000000bd02b
- (void)_meDeviceChanged:(id)arg1;	// IMP=0x00100000000bcf53
- (void)_enabledBitsChanged:(id)arg1;	// IMP=0x00100000000bcf0a
- (void)_setupSyncListener;	// IMP=0x00100000000bccce
- (void)_setupMobileGestaltNotificationHandlers;	// IMP=0x00100000000bcbc0
- (void)_setupDistributedNotificationHandlers;	// IMP=0x00100000000bc988
- (void)_setupNotifyHandlers;	// IMP=0x00100000000bc1f6
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00100000000bc0fa
- (void)_setupAnnouncementSpeakingStatePublisher;	// IMP=0x00100000000bc0d8
- (_Bool)_audioSessionAssertionServiceListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000bbcac
- (void)_setupAudioSessionAssertionServiceListener;	// IMP=0x00100000000bbc45
- (_Bool)_notificationServiceListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000bb8a9
- (void)_setupNotificationServiceListener;	// IMP=0x00100000000bb82a
- (_Bool)_securityListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000bb4ed
- (void)_setupSecurityListener;	// IMP=0x00100000000bb486
- (_Bool)_analyticsObservationListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000bb10d
- (void)_setupAnalyticsObservationListener;	// IMP=0x00100000000bb0a6
- (_Bool)_analyticsListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000bac0a
- (void)_setupAnalyticsListener;	// IMP=0x00100000000bab21
- (void)_setupSiriAnalyticsListener;	// IMP=0x00100000000baadd
- (void)_setupContextListener;	// IMP=0x00100000000baad3
- (_Bool)_managedStorageListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000ba854
- (void)_setupManagedStorageListener;	// IMP=0x00100000000ba7ed
- (_Bool)_synapseSyncListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000ba3b0
- (id)_synapseAppBundleIDFromPossibleDeamonBundleID:(id)arg1;	// IMP=0x00100000000ba365
- (void)_bundleID:(id *)arg1 andPath:(id *)arg2 forXPCConnection:(id)arg3;	// IMP=0x00100000000ba11d
- (void)_setupSynapseSyncListener;	// IMP=0x00100000000ba0b6
- (void)_setupSettingsListener;	// IMP=0x00100000000ba00a
- (_Bool)_settingsListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000b9c70
- (void)_setupDictationListener;	// IMP=0x00100000000b9b70
- (_Bool)_dictationListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000b9613
- (void)startUISpeechRequest;	// IMP=0x00100000000b95ea
- (void)startUIRequestWithInfo:(id)arg1;	// IMP=0x00100000000b9535
- (_Bool)_clientListenerShouldAcceptNewConnection:(id)arg1;	// IMP=0x00100000000b8ece
- (void)_setupClientListener;	// IMP=0x00100000000b8dc5
- (id)_peerLocationService;	// IMP=0x00100000000b8cfb
- (id)_proxyService;	// IMP=0x00100000000b8c31
- (void)_setupIDSServices;	// IMP=0x00100000000b8b3d
- (void)_setupRapportServices;	// IMP=0x00100000000b8b37
- (void)_setupInternal;	// IMP=0x00100000000b8a68
- (void)keepAlive;	// IMP=0x00100000000b8965
- (void)shutdown;	// IMP=0x00100000000b894d
- (void)runWithLaunchContext:(id)arg1;	// IMP=0x00100000000b88c1
- (void)dealloc;	// IMP=0x00100000000b8802
- (id)init;	// IMP=0x00100000000b8743

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

