//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ADDeviceSyncSnapshot;

@interface ADDeviceSyncCommandPullSnapshotResponse : NSObject
{
    ADDeviceSyncSnapshot *_snapshot;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000211438
+ (id)newWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x00100000002111c9
- (void).cxx_destruct;	// IMP=0x00100000002114fa
@property(readonly, copy, nonatomic) ADDeviceSyncSnapshot *snapshot; // @synthesize snapshot=_snapshot;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000002114cd
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000211440
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000021142d
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000021138a
- (unsigned long long)hash;	// IMP=0x0010000000211374
- (id)_descriptionWithIndent:(unsigned long long)arg1;	// IMP=0x00100000002112ee
- (id)description;	// IMP=0x00100000002112da
- (id)initWithSnapshot:(id)arg1;	// IMP=0x001000000021122a
- (id)init;	// IMP=0x0010000000211216
- (id)initWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x00100000002110d5
- (id)mutatedCopyWithMutator:(CDUnknownBlockType)arg1;	// IMP=0x0010000000211600

@end

