//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface ADDeviceSyncCommandPushGenerationsRequest : NSObject
{
    NSDictionary *_generationsByDataType;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000001b57e9
+ (id)newWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x00100000001b557a
- (void).cxx_destruct;	// IMP=0x00100000001b58fe
@property(readonly, copy, nonatomic) NSDictionary *generationsByDataType; // @synthesize generationsByDataType=_generationsByDataType;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000001b58d1
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000001b57f1
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000001b57de
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001b573b
- (unsigned long long)hash;	// IMP=0x00100000001b5725
- (id)_descriptionWithIndent:(unsigned long long)arg1;	// IMP=0x00100000001b569f
- (id)description;	// IMP=0x00100000001b568b
- (id)initWithGenerationsByDataType:(id)arg1;	// IMP=0x00100000001b55db
- (id)init;	// IMP=0x00100000001b55c7
- (id)initWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x00100000001b5486
- (id)mutatedCopyWithMutator:(CDUnknownBlockType)arg1;	// IMP=0x00100000001b5a04

@end

