//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable;
@protocol AFAnnouncementRequestCapabilityProviding, OS_dispatch_queue;

@interface AFSiriUserNotificationRequestCapabilityManager : NSObject
{
    NSHashTable *_observers;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    id <AFAnnouncementRequestCapabilityProviding> _capabilityProvider;	// 24 = 0x18
    long long _platform;	// 32 = 0x20
}

+ (_Bool)supportedByApplicationWithBundleID:(id)arg1;	// IMP=0x00200000001c6c21
+ (Class)_classForPlatform:(long long)arg1;	// IMP=0x00100000001c6b88
+ (id)sharedManager;	// IMP=0x00100000001c69ca
- (void).cxx_destruct;	// IMP=0x00200000001c78f9
- (void)provider:(id)arg1 availableAnnouncementRequestTypesChanged:(unsigned long long)arg2;	// IMP=0x00100000001c78ac
- (void)provider:(id)arg1 eligibleAnnouncementRequestTypesChanged:(unsigned long long)arg2;	// IMP=0x00100000001c785f
- (void)notifyObserversOfCurrentRequestCanBeHandledState:(_Bool)arg1 onPlatform:(long long)arg2;	// IMP=0x00100000001c769a
- (void)notifyObserversOfCurrentEligibleSetupState:(_Bool)arg1 onPlatform:(long long)arg2;	// IMP=0x00100000001c750b
- (void)removeObserver:(id)arg1;	// IMP=0x00100000001c74f5
- (void)addObserver:(id)arg1;	// IMP=0x00100000001c74df
- (_Bool)requestCanBeHandled;	// IMP=0x00100000001c7265
- (void)fetchRequestCanBeHandledStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001c714f
- (_Bool)hasEligibleSetup;	// IMP=0x00100000001c6e05
- (void)fetchEligibleSetupStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001c6cef
- (id)_initWithPlatform:(long long)arg1;	// IMP=0x00100000001c6a6c

@end

