//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SADialog.h>

@interface SADialog (ADUIService)
- (void)_adui_notifyOthersOfArrival;	// IMP=0x00100000001f7831
- (_Bool)_adui_shouldNotifyOthersOfArrival;	// IMP=0x00100000001f7815
@end

