//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC13callservicesd31CallHistoryNotificationProvider : NSObject
{
    MISSING_TYPE *queue;	// 8 = 0x8
    MISSING_TYPE *callInteractionManager;	// 16 = 0x10
    MISSING_TYPE *callHistoryDataSource;	// 24 = 0x18
    MISSING_TYPE *callProviderManager;	// 64 = 0x40
    MISSING_TYPE *pendingCallIdentifiers;	// 72 = 0x48
    MISSING_TYPE *supportedMediaTypes;	// 80 = 0x50
    MISSING_TYPE *supportedProviders;	// 88 = 0x58
    MISSING_TYPE *mostRecentCallDate;	// 0 = 0x0
    MISSING_TYPE *supportsDisplayingFaceTimeAudioCalls;	// 16 = 0x10
    MISSING_TYPE *openURL;	// 3912148 = 0x3bb1d4
    MISSING_TYPE *dialRecentCall;	// 0 = 0x0
    MISSING_TYPE *findConversationLink;	// 0 = 0x0
    MISSING_TYPE *featureFlags;	// 0 = 0x0
    MISSING_TYPE *notificationType;	// 2004049759 = 0x77735f5f
    MISSING_TYPE *add;	// 1953391967 = 0x746e655f
    MISSING_TYPE *replace;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *removeNotification;	// 0 = 0x0
    MISSING_TYPE *updateBadgeValue;	// 3912164 = 0x3bb1e4
}

- (void).cxx_destruct;	// IMP=0x004000000027e530
- (id)init;	// IMP=0x00100000002791d0

@end

