//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ASCLockupDisplayContext, NSString;

@interface ASCLockupFeatureDisplayContext : NSObject
{
    ASCLockupDisplayContext *_displayContext;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000000ed36
- (void).cxx_destruct;	// IMP=0x002000000000f07d
@property(readonly, copy, nonatomic) ASCLockupDisplayContext *displayContext; // @synthesize displayContext=_displayContext;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000eeca
@property(readonly) unsigned long long hash;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000ee44
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000000edcb
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000000ed3e
- (id)initWithDisplayContext:(id)arg1;	// IMP=0x001000000000ecc3

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

