//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface ASCMobileGestalt : NSObject
{
}

+ (_Bool)hasCapabilities:(id)arg1;	// IMP=0x0020000000015a4a
+ (_Bool)isAppleSiliconMac;	// IMP=0x0010000000015a42
+ (id)activePairedSystemVersion;	// IMP=0x0010000000015a3a
+ (_Bool)isStandaloneWatch;	// IMP=0x0010000000015a32
+ (_Bool)isPad;	// IMP=0x0010000000015a15
+ (struct CGSize)mainScreenPointSize;	// IMP=0x0010000000015990
+ (double)mainScreenCornerRadius;	// IMP=0x0010000000015972
+ (double)mainScreenScale;	// IMP=0x0010000000015954
+ (struct CGSize)mainScreenSize;	// IMP=0x00100000000158a8
+ (_Bool)hasHEVCDecoding;	// IMP=0x0010000000015897
+ (id)productType;	// IMP=0x0010000000015870
+ (id)deviceClass;	// IMP=0x0010000000015849
+ (_Bool)wapiCapability;	// IMP=0x0010000000015838
+ (_Bool)hasVenice;	// IMP=0x0010000000015827
+ (_Bool)hasSystemTelephonyOfAnyKind;	// IMP=0x0010000000015816

@end

