//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SiriUI/SiriUIContentCollectionViewCell.h>

@class NSString, SiriUITextContainerView;

@interface SRGuideDetailSectionHeaderCollectionViewCell : SiriUIContentCollectionViewCell
{
    SiriUITextContainerView *_textContainerView;	// 8 = 0x8
}

+ (double)_trailingHorizontalOffsetWithLayoutMargins:(struct UIEdgeInsets)arg1;	// IMP=0x004000000000455d
+ (double)_leadingHorizontalOffsetWithLayoutMargins:(struct UIEdgeInsets)arg1;	// IMP=0x001000000000453f
+ (id)_font;	// IMP=0x001000000000447e
+ (struct CGSize)sizeThatFits:(struct CGSize)arg1 text:(id)arg2;	// IMP=0x0010000000003f41
- (void).cxx_destruct;	// IMP=0x0020000000004579
@property(copy, nonatomic) NSString *text;
- (void)prepareForReuse;	// IMP=0x00100000000043f9
- (void)layoutSubviews;	// IMP=0x0010000000004280
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000004089

@end

