//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SRLocalSnippetManager : NSObject
{
}

+ (void)_logRFSnippetRenderingContextWithEvent:(long long)arg1;	// IMP=0x0020000000068b17
+ (id)transcriptItemForObject:(id)arg1;	// IMP=0x001000000006888d
+ (id)visualResponseProvider;	// IMP=0x0010000000068838

@end

