//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, UILabel;

@interface SRStarkEmergencyCallConfirmationSnippetView
{
    UILabel *_titleLabel;	// 8 = 0x8
    UILabel *_subtitleLabel;	// 16 = 0x10
    UILabel *_countdownLabel;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000001197c
@property(readonly, nonatomic) UILabel *countdownLabel; // @synthesize countdownLabel=_countdownLabel;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
- (id)_countdownStringFromTime:(long long)arg1;	// IMP=0x001000000001188c
- (id)accessibilityIdentifier;	// IMP=0x0010000000011878
- (void)updateCountdownSeconds:(long long)arg1;	// IMP=0x00100000000117ed
- (MISSING_TYPE *)layoutSubviews;	// IMP=0x0010000000010ae0
- (id)initWithFrame:(struct CGRect)arg1 confirmationButtons:(id)arg2 totalCountdownSeconds:(long long)arg3 currentTurnContext:(id)arg4;	// IMP=0x00100000000105b4

@end

