//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary, NSString;

@interface PBMutableSystemOverlayDismissalRequest
{
}

- (void)_setClientInitiated:(_Bool)arg1;	// IMP=0x002000000015ec0d
@property(copy, nonatomic) NSDictionary *clientOptions; // @dynamic clientOptions;
@property(nonatomic, getter=isAnimated) _Bool animated; // @dynamic animated;
@property(copy, nonatomic) NSString *identifier; // @dynamic identifier;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000015eb79
- (id)init;	// IMP=0x001000000015eb4a

@end

