//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PBPIPSwapReduceMotionAnimationTransaction
{
}

+ (id)_crossfadeTransactionForLayer:(id)arg1;	// IMP=0x0040000000185b02
+ (id)_crossfadeAnimation;	// IMP=0x0010000000185aa2
- (void)_addChildCrossfadeAnimationTransactionForView:(id)arg1;	// IMP=0x0040000000185b90
- (void)_begin;	// IMP=0x001000000018591e

@end

