//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BSCompoundAssertion, TVSObserverSet;
@protocol OS_dispatch_source;

@interface PBSceneShroudController : NSObject
{
    TVSObserverSet *_agents;	// 8 = 0x8
    BSCompoundAssertion *_compoundAssertion;	// 16 = 0x10
    NSObject<OS_dispatch_source> *_debounceSource;	// 24 = 0x18
}

+ (id)allBundleIDsSet;	// IMP=0x0040000000105e50
- (void).cxx_destruct;	// IMP=0x00200000001071c5
@property(readonly, nonatomic) NSObject<OS_dispatch_source> *debounceSource; // @synthesize debounceSource=_debounceSource;
@property(readonly, nonatomic) BSCompoundAssertion *compoundAssertion; // @synthesize compoundAssertion=_compoundAssertion;
@property(readonly, nonatomic) TVSObserverSet *agents; // @synthesize agents=_agents;
- (id)_contextForBundleID:(id)arg1;	// IMP=0x0010000000106fe9
- (id)_contextsByBundleIDDictionaryWithDefaultContext:(out id *)arg1;	// IMP=0x0010000000106bcd
- (void)_mainQueue_updateAgent:(id)arg1 withUserInfo:(id)arg2 usingContext:(id)arg3 animated:(_Bool)arg4;	// IMP=0x0010000000106a11
- (void)_mainQueue_handleStateChange;	// IMP=0x00100000001066c4
- (id)registerAgent:(id)arg1 withClientProcessBundleIdentifier:(id)arg2;	// IMP=0x0010000000106448
- (id)shroudApplicationsWithBundleIDs:(id)arg1 style:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001061f4
- (void)dealloc;	// IMP=0x0010000000106176
- (id)init;	// IMP=0x0010000000105f34

@end

