//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "TVSTransactionManagerObserver-Protocol.h"

@class BSTransaction;
@protocol TVSTransactionManaging;

@protocol TVSSerialTransactionManagerObserver <TVSTransactionManagerObserver>

@optional
- (void)transactionManager:(id <TVSTransactionManaging>)arg1 didInterruptTransaction:(BSTransaction *)arg2 forTransaction:(BSTransaction *)arg3;
- (void)transactionManager:(id <TVSTransactionManaging>)arg1 willInterruptTransaction:(BSTransaction *)arg2 forTransaction:(BSTransaction *)arg3;
@end

