//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MRDBrowsableContentAPICoordinator, NSMutableArray, NSMutableDictionary, NSString;

@interface MRDBrowsableContentServer : NSObject
{
    NSMutableArray *_queuedInitiatePlaybackMessages;	// 8 = 0x8
    NSMutableArray *_queuedRelayableMessages;	// 16 = 0x10
    NSMutableDictionary *_queuedBeginLoadingBlocks;	// 24 = 0x18
    MRDBrowsableContentAPICoordinator *_apiCoordinator;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000000034f4a
@property(readonly, nonatomic) MRDBrowsableContentAPICoordinator *apiCoordinator; // @synthesize apiCoordinator=_apiCoordinator;
- (_Bool)_messageRequiresMediaServerBlessing:(id)arg1;	// IMP=0x0010000000034f1b
- (_Bool)_messageCanLaunchApp:(id)arg1;	// IMP=0x0010000000034ef6
- (void)_scheduleEndProcessAssertionForClient:(id)arg1;	// IMP=0x0010000000034e7a
- (_Bool)_takeProcessAssertionForClient:(id)arg1 withReason:(id)arg2;	// IMP=0x0010000000034c67
- (void)_handleSupportedAPIsDidChangeForClient:(id)arg1;	// IMP=0x001000000003473b
- (void)_handleBrowsableContentDidFinishLoadingFromClient:(id)arg1 indexPath:(CDStruct_3716a28a)arg2 withError:(id)arg3;	// IMP=0x0010000000034492
- (void)_sendInitiatePlaybackMessage:(id)arg1;	// IMP=0x00100000000341a7
- (void)_relayMessage:(id)arg1 toClientWithBundleIDAndReply:(id)arg2;	// IMP=0x0010000000033c98
- (void)_handleGetAppsSupportingBrowsableContentAPIsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000033bee
- (void)_handleSetSupportedBrowsableContentAPIsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000033b37
- (void)_handleGetSupportedBrowsableContentAPIsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000033ab8
- (void)_handleRequestPlaybackInitializationMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000337b1
- (void)_clientDidUnregisterCanBeNowPlaying:(id)arg1;	// IMP=0x00100000000336ea
- (void)_clientDidRegisterCanBeNowPlaying:(id)arg1;	// IMP=0x0010000000033623
- (void)_clearQueuedBeginLoadingMessagesForApp:(id)arg1;	// IMP=0x0010000000033535
- (void)_sendQueuedBeginLoadingMessagesForAvailableApp:(id)arg1;	// IMP=0x0010000000033381
- (void)_enqueueCompletion:(CDUnknownBlockType)arg1 forUnavailableDestinationApp:(id)arg2;	// IMP=0x0010000000033272
- (void)_handleBeginLoadingBrowsableContentMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000032d34
- (void)collectDiagnostic:(id)arg1;	// IMP=0x0010000000032d18
- (void)handleXPCMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000032bfd
- (id)init;	// IMP=0x0010000000032ab8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

