//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, MRDDeviceInfoDataSource, MRDElectedPlayerController, MRDLockScreenController, MRDNowPlayingClient, MRDNowPlayingOriginClient, MRDNowPlayingPlaybackQueueServer, MRDNowPlayingPlayerClient, MRDProximityController, MRPlayerPath, NSArray, NSHashTable, NSMutableArray, NSMutableDictionary, NSSet, NSString;
@protocol OS_dispatch_queue;

@interface MRDNowPlayingServer : NSObject
{
    NSObject<OS_dispatch_queue> *_serialQueue;	// 8 = 0x8
    NSMutableArray *_originClients;	// 16 = 0x10
    NSMutableDictionary *_nowPlayingApplicationIsPlayingStates;	// 24 = 0x18
    MRDNowPlayingPlaybackQueueServer *_playbackQueueServer;	// 32 = 0x20
    NSHashTable *_originForwarders;	// 40 = 0x28
    MRDDeviceInfoDataSource *_deviceInfoDataSource;	// 48 = 0x30
    MRDElectedPlayerController *_electedPlayerController;	// 56 = 0x38
    MRDLockScreenController *_lockScreenController;	// 64 = 0x40
    MRDProximityController *_proximityController;	// 72 = 0x48
    MRDNowPlayingOriginClient *_activeOriginClient;	// 80 = 0x50
    MRDNowPlayingOriginClient *_localOriginClient;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x00200000000b1c2f
@property(retain, nonatomic) MRDNowPlayingOriginClient *localOriginClient; // @synthesize localOriginClient=_localOriginClient;
@property(retain, nonatomic) MRDNowPlayingOriginClient *activeOriginClient; // @synthesize activeOriginClient=_activeOriginClient;
@property(readonly, nonatomic) MRDProximityController *proximityController; // @synthesize proximityController=_proximityController;
@property(readonly, nonatomic) MRDLockScreenController *lockScreenController; // @synthesize lockScreenController=_lockScreenController;
@property(readonly, nonatomic) MRDElectedPlayerController *electedPlayerController; // @synthesize electedPlayerController=_electedPlayerController;
- (id)_onQueue_originClientForGroupLeaderOfDeviceUID:(id)arg1;	// IMP=0x00100000000b184b
- (id)_onQueue_originClientForDeviceUID:(id)arg1;	// IMP=0x00100000000b155e
- (id)_onQueue_originClientForOrigin:(id)arg1;	// IMP=0x00100000000b134e
- (id)_onQueue_restoredActiveOrigin;	// IMP=0x00100000000b12b8
- (void)_onQueue_savePersistentActiveOrigin:(id)arg1;	// IMP=0x00100000000b1189
- (void)_onQueue_setActiveOrigin:(id)arg1 saveState:(_Bool)arg2;	// IMP=0x00100000000b0fd4
- (void)setActiveOrigin:(id)arg1;	// IMP=0x00100000000b0f25
- (id)overrideClient;	// IMP=0x00100000000b0ed5
- (void)setOverrideClient:(id)arg1;	// IMP=0x00100000000b0e63
- (void)_removeNowPlayingClient:(id)arg1 forOrigin:(id)arg2;	// IMP=0x00100000000b0deb
- (void)_removeOrigin:(id)arg1;	// IMP=0x00100000000b09d8
- (void)_addOrigin:(id)arg1 withDeviceInfo:(id)arg2 emitNotification:(_Bool)arg3;	// IMP=0x00100000000b051c
- (_Bool)_hasForwarderForOrigin:(id)arg1;	// IMP=0x00100000000b0375
- (void)unregisterOriginForwarder:(id)arg1;	// IMP=0x00100000000b02ca
- (void)registerOriginForwarder:(id)arg1;	// IMP=0x00100000000b01dc
- (id)augmentedUserInfoForPlayerPath:(id)arg1;	// IMP=0x00100000000affac
- (void)maybePostDistributedNotifications;	// IMP=0x00100000000af813
- (void)postLockScreenControlsDidChangeDistributedNotification;	// IMP=0x00100000000af755
- (void)postLockScreenPlayerPathDidChange:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000af330
- (void)postLockScreenActiveDidChange:(_Bool)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000af251
- (void)postLockScreenVisibleDidChange:(_Bool)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000af172
- (void)postElectedPlayerDidChange:(id)arg1 change:(long long)arg2 event:(long long)arg3 reason:(id)arg4 handler:(CDUnknownBlockType)arg5;	// IMP=0x00100000000aef9e
- (void)postPlayerDidUnregisterWithPlaybackState:(unsigned int)arg1 canBeNowPlaying:(_Bool)arg2 forPlayerPath:(id)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000aee26
- (void)postPlayerDidRegisterForPlayerPath:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000aed59
- (void)postPlaybackQueueCapabilitiesDidChange:(unsigned long long)arg1 forPlayerPath:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000aec3d
- (void)postPlaybackQueueContentItemsArtworkDidChange:(id)arg1 forPlayerPath:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ae874
- (void)postPlaybackQueueContentItemsDidChange:(id)arg1 forPlayerPath:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ae40b
- (void)postPlaybackQueueDidChange:(id)arg1 nowPlayingItemDidChange:(_Bool)arg2 forPlayerPath:(id)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000adf57
- (void)postSupportedCommandsDidChange:(id)arg1 forPlayerPath:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000addba
- (void)postNowPlayingPlayerStateDidChange:(id)arg1 forPlayerPath:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000adced
- (void)postPlaybackStateDidChange:(unsigned int)arg1 forPlayerPath:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000adba2
- (void)postAudioFormatContentInfoDidChangeForOrigin:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ada8b
- (void)postActivePlayerPathsDidChangeForOrigin:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ad974
- (void)postPictureInPictureDidChange:(_Bool)arg1 forPlayerPath:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ad85a
- (void)postIsPlayingDidChange:(_Bool)arg1 lastPlayingTimestamp:(double)arg2 forPlayerPath:(id)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000ad6fa
- (void)postActivePlayerDidChangeForPlayerPath:(id)arg1 withPlaybackState:(unsigned int)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ad5e0
- (void)postNowPlayingClientStateDidChange:(id)arg1 forPlayerPath:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ad513
- (void)postClientDidUnregisterForPlayerPath:(id)arg1 hasDefaultSupportedCommands:(_Bool)arg2 canBeNowPlaying:(_Bool)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000ad3b7
- (void)postClientDidRegisterForPlayerPath:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ad2ea
- (void)postPlayerDidUnregisterCanBeNowPlayingForPlayerPath:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ad21d
- (void)postPlayerDidRegisterCanBeNowPlayingForPlayerPath:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ad150
- (void)postClientDidUnregisterCanBeNowPlayingForPlayerPath:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ad083
- (void)postClientDidRegisterCanBeNowPlayingForPlayerPath:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000acf86
- (void)postNowPlayingApplicationDidChangeForPlayerPath:(id)arg1 withPlaybackState:(unsigned int)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000acde4
- (MISSING_TYPE *)postIsMutedDidChange:isMuted:handler: /* Error: Ran out of types for this method. */;	// IMP=0x00100000000accca
- (void)postVolumeCapabilitiesDidChange:(id)arg1 capabilities:(unsigned int)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000acb6e
- (void)postVolumeDidChange:(id)arg1 volume:(float)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000aca57
- (void)postDeviceInfoDidChange:(id)arg1 previousDeviceInfo:(id)arg2 forOrigin:(id)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000ac8f9
- (void)postOriginDidUnRegister:(id)arg1 deviceInfo:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ac7c4
- (void)postOriginDidRegister:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ac6b4
- (void)postActiveOriginDidChange:(id)arg1 withPlaybackState:(unsigned int)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ac59a
- (void)collectDiagnostic:(id)arg1;	// IMP=0x00100000000ac0d7
@property(readonly, nonatomic) _Bool lockScreenPlatterActive;
- (void)lockScreenController:(id)arg1 playerPathDidChange:(id)arg2;	// IMP=0x00100000000ac07c
- (void)lockScreenController:(id)arg1 lockScreenWidgetVisibleDidChange:(_Bool)arg2;	// IMP=0x00100000000ac066
- (void)lockScreenController:(id)arg1 lockScreenWidgetActiveDidChange:(_Bool)arg2;	// IMP=0x00100000000ac050
- (void)electedPlayerController:(id)arg1 electedPlayerDidChange:(id)arg2 change:(long long)arg3 event:(long long)arg4 reason:(id)arg5;	// IMP=0x00100000000ac01d
- (void)nowPlayingServer:(id)arg1 activeOriginDidChangeFromOriginClient:(id)arg2 toOriginClient:(id)arg3;	// IMP=0x00100000000abf4b
- (void)nowPlayingOriginClientDidChangeAudioFormatContentInfo:(id)arg1;	// IMP=0x00100000000abefa
- (void)nowPlayingOriginClientPlaybackDidTimeout:(id)arg1;	// IMP=0x00100000000abddb
- (void)nowPlayingOriginClient:(id)arg1 activePlayerClientsDidChange:(id)arg2;	// IMP=0x00100000000abd8a
- (void)nowPlayingOriginClient:(id)arg1 currentRouteIsMutedDidChange:(_Bool)arg2;	// IMP=0x00100000000abd33
- (void)nowPlayingOriginClient:(id)arg1 currentRouteVolumeDidChange:(float)arg2;	// IMP=0x00100000000abcd8
- (void)nowPlayingOriginClient:(id)arg1 currentRouteVolumeControlCapabilitiesDidChange:(unsigned int)arg2;	// IMP=0x00100000000abc81
- (void)nowPlayingOriginClient:(id)arg1 clientDidUnregister:(id)arg2;	// IMP=0x00100000000abae9
- (void)nowPlayingOriginClient:(id)arg1 clientDidRegister:(id)arg2;	// IMP=0x00100000000aba98
- (void)nowPlayingOriginClient:(id)arg1 deviceInfoDidChange:(id)arg2 previousDeviceInfo:(id)arg3;	// IMP=0x00100000000ab965
- (void)nowPlayingOriginClient:(id)arg1 applicationActivityStatusDidChange:(id)arg2;	// IMP=0x00100000000ab87d
- (void)nowPlayingOriginClient:(id)arg1 applicationActivityDidEnd:(id)arg2;	// IMP=0x00100000000ab795
- (void)nowPlayingOriginClient:(id)arg1 applicationActivityDidBegin:(id)arg2;	// IMP=0x00100000000ab6ad
- (void)nowPlayingOriginClient:(id)arg1 activePlayerPathDidChange:(id)arg2 withPlaybackState:(unsigned int)arg3;	// IMP=0x00100000000ab676
- (void)nowPlayingClient:(id)arg1 applicationDidForeground:(_Bool)arg2;	// IMP=0x00100000000ab515
- (void)nowPlayingPlayerClient:(id)arg1 clientCanBeNowPlayingDidChange:(_Bool)arg2;	// IMP=0x00100000000ab4b1
- (void)nowPlayingClient:(id)arg1 playerDidUnregister:(id)arg2;	// IMP=0x00100000000ab413
- (void)nowPlayingClient:(id)arg1 playerDidRegister:(id)arg2;	// IMP=0x00100000000ab3c2
- (void)nowPlayingClient:(id)arg1 clientStateDidChange:(id)arg2;	// IMP=0x00100000000ab347
- (void)nowPlayingClient:(id)arg1 activePlayerDidChangeFromPlayerClient:(id)arg2 toPlayerClient:(id)arg3;	// IMP=0x00100000000ab281
- (void)nowPlayingPlayerClient:(id)arg1 playerCanBeNowPlayingDidChange:(_Bool)arg2;	// IMP=0x00100000000ab21d
- (void)nowPlayingPlayerClient:(id)arg1 pictureInPictureEnabledDidChange:(_Bool)arg2;	// IMP=0x00100000000ab1b7
- (void)nowPlayingPlayerClient:(id)arg1 playbackQueueArtworkContentItemsDidChange:(id)arg2;	// IMP=0x00100000000ab13c
- (void)nowPlayingPlayerClient:(id)arg1 playbackQueueContentItemsDidChange:(id)arg2;	// IMP=0x00100000000ab0c1
- (void)nowPlayingPlayerClient:(id)arg1 playbackQueueCapabilitiesDidChange:(unsigned long long)arg2;	// IMP=0x00100000000ab06a
- (void)nowPlayingPlayerClient:(id)arg1 playbackQueueDidChange:(id)arg2 nowPlayingItemDidChange:(_Bool)arg3;	// IMP=0x00100000000aafea
- (void)nowPlayingPlayerClient:(id)arg1 supportedCommandsDidChange:(id)arg2;	// IMP=0x00100000000aaf6f
- (void)nowPlayingPlayerClient:(id)arg1 playbackStateDidChange:(unsigned int)arg2;	// IMP=0x00100000000aaf18
- (void)nowPlayingPlayerClient:(id)arg1 isPlayingDidChange:(_Bool)arg2;	// IMP=0x00100000000aae3d
- (void)nowPlayingPlayerClient:(id)arg1 playerStateDidChange:(id)arg2;	// IMP=0x00100000000aadc2
- (void)_handleGetAudioFormatContentInfoForOriginMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000aac40
- (void)_handleRegisterForWakingNowPlayingNotifications:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000aab06
- (void)_handleSetOriginClientPropertiesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000aa98c
- (void)_handleSetPlayerClientPropertiesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000aa7d5
- (void)_handleGetLastPlayingDateMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000aa4ed
- (void)_handleSetDefaultSupportedCommandsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000aa160
- (void)_handleSetSupportedCommandsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a9fa8
- (void)_handleGetSupportedCommandsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a9212
- (void)_handlePlaybackSessionRequest:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a9098
- (void)_handleGetElectedPlayerPathMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a8fec
- (void)_handleGetDeviceInfo:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a8e59
- (void)_handleContentItemArtworkChangedMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a8d69
- (void)_handleContentItemChangedMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a8c3a
- (void)_handleSetPlayerPictureInPictureEnabledMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a8b77
- (void)_handleGetPlayerPictureInPictureEnabledMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a8a28
- (void)_handleGetActivePlayerPathsForLocalOriginMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a88e6
- (void)_handleRemoveNowPlayingPlayerMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a87f1
- (void)_handleGetNowPlayingPlayerMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a86b8
- (void)_handleSetNowPlayingPlayerMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a84fa
- (void)_handleGetNowPlayingPlayersMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a81d7
- (void)_handleRemoveNowPlayingClientMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a80df
- (void)_handleGetNowPlayingClientMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a7fa6
- (void)_handleSetNowPlayingClientMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a7ca1
- (void)_handleGetNowPlayingClientsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a7756
- (void)_handleResolvePlayerPath:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a7540
- (void)_handleSendLyricsEvent:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a72aa
- (void)_handleRequestAudioAmplitudeSamplesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a7011
- (void)_handleRequestVideoThumbnailsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a6d78
- (void)_handleGetAnyAppIsPlayingMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a6cc4
- (void)_handleSetPlaybackStateMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a6acc
- (void)_handleGetPlaybackStateMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a6976
- (void)_handleUpdatePlayerPropertiesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a67bf
- (void)_handleSetPlayerPropertiesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a662a
- (void)_handleGetPlayerPropertiesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a64ca
- (void)_handleUpdateClientPropertiesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a6317
- (void)_handleSetClientPropertiesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a6163
- (void)_handleGetClientPropertiesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a6003
- (void)_handleResetPlaybackQueueRequests:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a5edc
- (void)_handleSetHardwareRemoteBehaviorMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a5dc9
- (void)_handleSetPlaybackQueueCapabilties:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a5d0e
- (void)_handleRequestPlaybackQueueCapabilties:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a5bc2
- (void)_handleSetPlaybackQueue:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a5954
- (void)_handleEndApplicationActivityMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a58cf
- (void)_handleGetApplicationActivityMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a57e9
- (void)_handleBeginApplicationActivityMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a56e6
- (void)_handleSetCanBeNowPlayingPlayerMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a54d6
- (void)_handleSetCanBeNowPlayingAppMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a5316
- (void)_handleSetOverriddenNowPlayingAppMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a4f0d
- (void)_handleSetNowPlayingAppOverrideMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a4b79
- (void)updateDeviceInfo:(id)arg1 origin:(id)arg2;	// IMP=0x00100000000a4b01
- (void)unregisterOrigin:(id)arg1;	// IMP=0x00100000000a4aef
- (void)reregisterOrigin:(id)arg1 deviceInfo:(id)arg2;	// IMP=0x00100000000a46d5
- (void)registerOrigin:(id)arg1 deviceInfo:(id)arg2;	// IMP=0x00100000000a46bd
- (void)_handleGetActiveOriginMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a45d7
- (void)_handleSetActiveOriginMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a44eb
- (void)_handleGetAvailableOriginsMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a4271
- (void)restoreClientState:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a2750
- (void)restoreDeviceInfoToClient:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000a2556
- (void)clearNowPlayingClientForXPCClient:(id)arg1;	// IMP=0x00100000000a212c
- (id)originClientForGroupLeaderOfDeviceUID:(id)arg1;	// IMP=0x00100000000a1fef
- (id)originClientForDeviceUID:(id)arg1;	// IMP=0x00100000000a1eb2
- (id)originClientForOrigin:(id)arg1;	// IMP=0x00100000000a1d5f
- (id)localPlayersForXpcClient:(id)arg1;	// IMP=0x00100000000a1c7e
- (id)xpcClientForPlayerPath:(id)arg1;	// IMP=0x00100000000a1a38
- (id)_onQueue_queryPlayerPath:(id)arg1;	// IMP=0x00100000000a162a
- (id)queryPlayerPath:(id)arg1;	// IMP=0x00100000000a14d7
- (id)resolveExistingPlayerPath:(id)arg1;	// IMP=0x00100000000a1055
- (id)resolvePlayerPath:(id)arg1 fromClient:(id)arg2 useDefaultPlayerIfNoneSpecified:(_Bool)arg3;	// IMP=0x00100000000a08d0
- (id)resolvePlayerPath:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a08b8
- (id)queryExistingPlayerPathForXPCMessage:(id)arg1 forClient:(id)arg2;	// IMP=0x00100000000a0734
- (id)queryPlayerPathForXPCMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000000a068d
@property(readonly, nonatomic) NSArray *originClients;
- (id)_onQueue_allNowPlayingInfoClientsForOrigin:(id)arg1;	// IMP=0x00100000000a03bb
@property(readonly, nonatomic) NSSet *allLocalNowPlayingInfoClients;
- (id)_onQueue_allNowPlayingInfoClients;	// IMP=0x00100000000a0005
@property(readonly, nonatomic) NSSet *allNowPlayingInfoClients;
@property(readonly, nonatomic) MRPlayerPath *localActivePlayerPath;
@property(readonly, nonatomic) MRPlayerPath *activePlayerPath;
- (id)_onQueue_companionOriginClient;	// IMP=0x001000000009fca6
- (id)_onQueue_activeOriginClient;	// IMP=0x001000000009fc5c
@property(readonly, nonatomic) MRDNowPlayingOriginClient *companionOriginClient;
@property(readonly, nonatomic) MRDNowPlayingClient *localActiveNowPlayingClient;
@property(readonly, nonatomic) MRDNowPlayingClient *activeNowPlayingClient;
@property(readonly, nonatomic) MRDNowPlayingPlayerClient *localActivePlayerClient;
@property(readonly, nonatomic) MRDNowPlayingPlayerClient *activePlayerClient;
@property(readonly, nonatomic) unsigned int localActivePlayerPlaybackState;
@property(readonly, nonatomic) unsigned int activePlayerPlaybackState;
@property(readonly, nonatomic) _Bool localActivePlayerIsPlaying;
@property(readonly, nonatomic) _Bool activePlayerIsPlaying;
@property(readonly, nonatomic) NSString *localActiveClientBundleIdentifier;
@property(readonly, nonatomic) NSString *activeClientBundleIdentifier;
@property(readonly, nonatomic) int localActiveClientPID;
@property(readonly, nonatomic) int activeClientPID;
- (void)handleXPCMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x001000000009edec
- (void)dealloc;	// IMP=0x001000000009ed77
- (id)init;	// IMP=0x001000000009eb54

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

