//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface VOTElementUniqueIdentification : NSObject
{
    NSString *hashKey;	// 8 = 0x8
}

+ (id)identificationFromElement:(id)arg1;	// IMP=0x0020000000114ff4
+ (id)identificationFromKey:(id)arg1;	// IMP=0x0010000000114f8d
- (void).cxx_destruct;	// IMP=0x002000000011550c
@property(copy, nonatomic) NSString *hashKey; // @synthesize hashKey;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000115445
- (id)description;	// IMP=0x0010000000115396
- (unsigned long long)hash;	// IMP=0x0010000000115352
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000114f1f

@end

