//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CloudPhotoLibrary/CPLFaceCropChange.h>

@class MISSING_TYPE;

@interface CPLFaceCropChange (CPLCloudKitImplementation)
+ (MISSING_TYPE *)ckValueForRelatedRecord: /* Error: Ran out of types for this method. */;	// IMP=0x00200000001115dc
+ (id)ckPropertyForRelatedIdentifier;	// IMP=0x00100000001115cf
+ (id)ckAssetProperties;	// IMP=0x001000000011148a
- (void)fillMissingCKAssetProperties:(id)arg1 withCKRecord:(id)arg2;	// IMP=0x00200000001114f6
- (void)fillWithCKRecord:(id)arg1;	// IMP=0x00100000001151dc
- (void)fillCKRecordBuilder:(id)arg1;	// IMP=0x0010000000118af8
@end

