//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray;

@interface CPLRemappedBy : PBCodable
{
    NSMutableArray *_remappedBys;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000b6023
- (unsigned long long)hash;	// IMP=0x00100000000b5fed
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000b5f53
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000b5db6
- (void)writeTo:(id)arg1;	// IMP=0x00100000000b5c86
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000b5c79
- (id)dictionaryRepresentation;	// IMP=0x00100000000b5893
- (id)description;	// IMP=0x00100000000b57e4

@end

