//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MIBundleContainer, MIDataContainer, MIExecutableBundle, NSArray, NSMutableDictionary, NSString, NSURL;

@interface MIInstallableBundle
{
    _Bool _isPlaceholderInstall;	// 8 = 0x8
    _Bool _xpcServiceBundlesEnabled;	// 9 = 0x9
    _Bool _validatedByFreeProfile;	// 10 = 0xa
    MIBundleContainer *_existingBundleContainer;	// 16 = 0x10
    MIBundleContainer *_bundleContainer;	// 24 = 0x18
    MIDataContainer *_dataContainer;	// 32 = 0x20
    NSArray *_appExtensionBundles;	// 40 = 0x28
    NSArray *_appExtensionDataContainers;	// 48 = 0x30
    NSArray *_frameworkBundles;	// 56 = 0x38
    NSArray *_xpcServiceBundles;	// 64 = 0x40
    NSURL *_upgradingBuiltInAppAtURL;	// 72 = 0x48
    NSMutableDictionary *_identifiersMap;	// 80 = 0x50
    NSString *_appIdentifier;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x002000000002f1f3
@property(retain, nonatomic) NSString *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
@property(nonatomic) _Bool validatedByFreeProfile; // @synthesize validatedByFreeProfile=_validatedByFreeProfile;
@property(nonatomic) _Bool xpcServiceBundlesEnabled; // @synthesize xpcServiceBundlesEnabled=_xpcServiceBundlesEnabled;
@property(retain, nonatomic) NSMutableDictionary *identifiersMap; // @synthesize identifiersMap=_identifiersMap;
@property(retain, nonatomic) NSURL *upgradingBuiltInAppAtURL; // @synthesize upgradingBuiltInAppAtURL=_upgradingBuiltInAppAtURL;
@property(retain, nonatomic) NSArray *xpcServiceBundles; // @synthesize xpcServiceBundles=_xpcServiceBundles;
@property(retain, nonatomic) NSArray *frameworkBundles; // @synthesize frameworkBundles=_frameworkBundles;
@property(retain, nonatomic) NSArray *appExtensionDataContainers; // @synthesize appExtensionDataContainers=_appExtensionDataContainers;
@property(retain, nonatomic) NSArray *appExtensionBundles; // @synthesize appExtensionBundles=_appExtensionBundles;
@property(retain, nonatomic) MIDataContainer *dataContainer; // @synthesize dataContainer=_dataContainer;
@property(retain, nonatomic) MIBundleContainer *bundleContainer; // @synthesize bundleContainer=_bundleContainer;
@property(readonly, nonatomic) MIBundleContainer *existingBundleContainer; // @synthesize existingBundleContainer=_existingBundleContainer;
@property(readonly, nonatomic) _Bool isPlaceholderInstall; // @synthesize isPlaceholderInstall=_isPlaceholderInstall;
- (id)launchServicesBundleRecordsWithError:(id *)arg1;	// IMP=0x001000000002eb40
- (_Bool)finalizeInstallationWithError:(id *)arg1;	// IMP=0x001000000002d371
- (_Bool)_refreshUUIDForContainer:(id)arg1 withError:(id *)arg2;	// IMP=0x001000000002d1f8
- (_Bool)postFlightInstallationWithError:(id *)arg1;	// IMP=0x001000000002cdce
- (_Bool)_postFlightAppExtensionsWithError:(id *)arg1;	// IMP=0x001000000002c850
- (_Bool)performInstallationWithError:(id *)arg1;	// IMP=0x001000000002c24a
- (_Bool)_handleStashOptionWithError:(id *)arg1;	// IMP=0x001000000002bfaf
- (_Bool)_linkToParentApplication:(id *)arg1;	// IMP=0x001000000002be0f
- (_Bool)_handleStashMode:(unsigned long long)arg1 withError:(id *)arg2;	// IMP=0x001000000002bbca
- (_Bool)_setBundleMetadataWithError:(id *)arg1;	// IMP=0x001000000002b528
- (_Bool)_setLinkageInBundleMetadata:(id)arg1 error:(id *)arg2;	// IMP=0x001000000002afc6
- (_Bool)_validateSinfsWithError:(id *)arg1;	// IMP=0x001000000002aced
- (_Bool)_captureDataFromStagingRootOrBundle:(id)arg1 toContainer:(id)arg2 withError:(id *)arg3;	// IMP=0x001000000002abf7
- (_Bool)_writeOptionsDataToBundle:(id)arg1 orContainer:(id)arg2 error:(id *)arg3;	// IMP=0x001000000002a3e1
- (_Bool)performVerificationWithError:(id *)arg1;	// IMP=0x001000000002770a
- (_Bool)_performAppClipSpecificValidationForEntitlements:(id)arg1 isAppClip:(_Bool *)arg2 withError:(id *)arg3;	// IMP=0x0010000000027603
- (_Bool)_performLocallySignedAppValidation:(id)arg1 withError:(id *)arg2;	// IMP=0x0010000000026ef0
- (_Bool)_validateApplicationIdentifierForNewBundleSigningInfo:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000026ee8
- (id)_validateBundle:(id)arg1 validatingResources:(_Bool)arg2 performingOnlineAuthorization:(_Bool)arg3 checkingTrustCacheIfApplicable:(_Bool)arg4 allowingFreeProfileValidation:(_Bool)arg5 skippingProfileIDValidation:(_Bool)arg6 error:(id *)arg7;	// IMP=0x0010000000026c35
- (_Bool)performPreflightWithError:(id *)arg1;	// IMP=0x0010000000025a72
- (_Bool)_validateITunesMetadataOptionWithError:(id *)arg1;	// IMP=0x00100000000254d0
- (_Bool)_checkCanInstallWithError:(id *)arg1;	// IMP=0x0010000000024be2
- (_Bool)_installEmbeddedProfilesWithError:(id *)arg1;	// IMP=0x00100000000244a0
- (_Bool)_verifyBundleMetadataWithError:(id *)arg1;	// IMP=0x00100000000242b1
- (void)dealloc;	// IMP=0x0010000000023ff4
- (id)initWithBundle:(id)arg1 inStagingRoot:(id)arg2 packageFormat:(unsigned char)arg3 domain:(unsigned long long)arg4 userOptions:(id)arg5 existingBundleContainer:(id)arg6 error:(id *)arg7;	// IMP=0x0010000000023e93

// Remaining properties
@property(retain, nonatomic) MIExecutableBundle *bundle; // @dynamic bundle;

@end

