//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSURLCredentialStorage.h>

@class NSMutableDictionary, NSObject, NSString;
@protocol NDCredentialStorageDelegate, OS_dispatch_queue;

@interface NDCredentialStorage : NSURLCredentialStorage
{
    NSMutableDictionary *_cachedCredentials;	// 16 = 0x10
    NSMutableDictionary *_cachedDefaultCredentialUsers;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
    id <NDCredentialStorageDelegate> _delegate;	// 40 = 0x28
    NSString *_bundleID;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000003a7f0
@property(copy) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property __weak id <NDCredentialStorageDelegate> delegate; // @synthesize delegate=_delegate;
- (void)reset;	// IMP=0x001000000003a74a
- (void)setDefaultCredential:(id)arg1 forProtectionSpace:(id)arg2;	// IMP=0x001000000003a5f7
- (id)defaultCredentialForProtectionSpace:(id)arg1;	// IMP=0x001000000003a3e0
- (void)removeCredential:(id)arg1 forProtectionSpace:(id)arg2;	// IMP=0x001000000003a28d
- (void)setCredential:(id)arg1 forProtectionSpace:(id)arg2;	// IMP=0x000000000003a13a
- (id)allCredentials;	// IMP=0x0010000000039f94
- (id)credentialsForProtectionSpace:(id)arg1;	// IMP=0x0010000000039d7d
- (void)populateWithInitialCredentials;	// IMP=0x0010000000039cc1
- (id)initWithDelegate:(id)arg1 forBundleID:(id)arg2;	// IMP=0x0010000000039b2e

@end

