//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class PDURLSessionProxyError, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyTaskWillBeRetried : PBCodable
{
    PDURLSessionProxyError *_error;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000495b7
@property(retain, nonatomic) PDURLSessionProxyError *error; // @synthesize error=_error;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000494d6
- (unsigned long long)hash;	// IMP=0x0010000000049489
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000493c1
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000049323
- (void)copyTo:(id)arg1;	// IMP=0x00100000000492c0
- (void)writeTo:(id)arg1;	// IMP=0x0010000000049263
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000049076
- (id)dictionaryRepresentation;	// IMP=0x0010000000048fa1
- (id)description;	// IMP=0x0010000000048ef2
@property(readonly, nonatomic) _Bool hasError;
@property(readonly, nonatomic) _Bool hasTask;

@end

