//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class PDURLSessionProxyAuthChallenge, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyDidReceiveChallenge : PBCodable
{
    PDURLSessionProxyAuthChallenge *_challenge;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000003f510
@property(retain, nonatomic) PDURLSessionProxyAuthChallenge *challenge; // @synthesize challenge=_challenge;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000003f42f
- (unsigned long long)hash;	// IMP=0x001000000003f3e2
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000003f31a
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000003f27c
- (void)copyTo:(id)arg1;	// IMP=0x001000000003f219
- (void)writeTo:(id)arg1;	// IMP=0x001000000003f1bc
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000003efcf
- (id)dictionaryRepresentation;	// IMP=0x001000000003eefa
- (id)description;	// IMP=0x001000000003ee4b
@property(readonly, nonatomic) _Bool hasChallenge;
@property(readonly, nonatomic) _Bool hasTask;

@end

