//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, NSUUID;

@interface AppInstallLogKey : NSObject
{
    NSString *_logKey;	// 8 = 0x8
    NSString *_batchLogKey;	// 16 = 0x10
    NSString *_bundleID;	// 24 = 0x18
    NSUUID *_externalID;	// 32 = 0x20
    NSNumber *_itemID;	// 40 = 0x28
    NSString *_logCode;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000041e70
- (id)description;	// IMP=0x0010000000041e66

@end

