//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, SQLiteConnection;

@interface AppUpdatesDatabaseTransaction
{
}

+ (void)_logState:(long long)arg1 forBundleID:(id)arg2 logKey:(id)arg3;	// IMP=0x0020000000158948
- (_Bool)_setUpdateState:(long long)arg1 forBundleID:(id)arg2 itemID:(id)arg3 withPurchaseID:(id)arg4 isUserInitiated:(_Bool)arg5 logKey:(id)arg6;	// IMP=0x0020000000158a38
- (_Bool)setUpdateState:(long long)arg1 usingPurchaseInfo:(id)arg2;	// IMP=0x0010000000158824
- (_Bool)setUpdateState:(long long)arg1 forBundleID:(id)arg2 evid:(id)arg3;	// IMP=0x0010000000158579
- (_Bool)recordUpdateDownloadStartTime:(id)arg1 andEndTime:(id)arg2 forBundleID:(id)arg3;	// IMP=0x00100000001582f4
- (id)processUpdate:(id)arg1 existingUpdate:(id)arg2 expectedCodeSignatureUpdateEvidForItemID:(id)arg3 isMigration:(_Bool)arg4 isModernUpdate:(_Bool)arg5;	// IMP=0x0010000000157d28
- (_Bool)mergeAvailableUpdates:(id)arg1 withReason:(long long)arg2 updatableApps:(id)arg3 expectedCodeSignatureUpdateEvidForItemID:(id)arg4 availableCount:(long long *)arg5 notifyChanges:(_Bool *)arg6 bundleIDs:(id *)arg7;	// IMP=0x0010000000157491
- (id)mergeAvailableUpdates:(id)arg1 isMigration:(_Bool)arg2 expectedCodeSignatureUpdateEvidForItemID:(id)arg3;	// IMP=0x0010000000156c97
- (_Bool)handleAppsUninstalled:(id)arg1;	// IMP=0x0010000000156b87
- (_Bool)deleteEntities:(id)arg1;	// IMP=0x00100000001567d0
- (_Bool)deleteUpdatesInstalledBefore:(double)arg1;	// IMP=0x00100000001566e8
- (_Bool)deleteUnusedUpdateData:(_Bool)arg1;	// IMP=0x001000000015655e

// Remaining properties
@property(readonly) SQLiteConnection *connection;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

