//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class XPCServiceBroker;

@interface RunLoop : NSObject
{
    XPCServiceBroker *_serviceBroker;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000096116
- (_Bool)performStartup;	// IMP=0x001000000009610e

@end

