//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;

@interface SQLiteMemoryEntity : NSObject
{
    long long _databaseID;	// 8 = 0x8
    NSMutableDictionary *_propertyValues;	// 16 = 0x10
    NSMutableDictionary *_externalPropertyValues;	// 24 = 0x18
}

+ (id)defaultProperties;	// IMP=0x002000000007757b
+ (Class)databaseEntityClass;	// IMP=0x001000000007756a
+ (id)queryOnConnection:(id)arg1 predicate:(id)arg2 orderingProperties:(id)arg3;	// IMP=0x00100000000fa983
+ (id)queryOnConnection:(id)arg1 predicate:(id)arg2;	// IMP=0x00100000000fa96e
+ (id)anyOnConnection:(id)arg1 predicate:(id)arg2;	// IMP=0x00100000000fa80c
- (void).cxx_destruct;	// IMP=0x0010000000077b1e
@property(readonly, copy, nonatomic) NSDictionary *externalPropertyValues; // @synthesize externalPropertyValues=_externalPropertyValues;
@property(readonly, copy, nonatomic) NSDictionary *propertyValues; // @synthesize propertyValues=_propertyValues;
@property(nonatomic) long long databaseID; // @synthesize databaseID=_databaseID;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000077a82
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000077945
- (unsigned long long)hash;	// IMP=0x001000000007792f
- (id)description;	// IMP=0x00100000000778a9
- (id)valueForExternalProperty:(id)arg1;	// IMP=0x0010000000077893
- (id)valueForProperty:(id)arg1;	// IMP=0x001000000007787d
- (void)setValues:(id *)arg1 forExternalProperties:(const id *)arg2 count:(long long)arg3;	// IMP=0x0010000000077800
- (void)setValue:(id)arg1 forExternalProperty:(id)arg2;	// IMP=0x0010000000077774
- (void)setValuesWithDictionary:(id)arg1;	// IMP=0x001000000007775e
- (void)setValues:(id *)arg1 forProperties:(const id *)arg2 count:(long long)arg3;	// IMP=0x00100000000776e1
- (void)setValue:(id)arg1 forProperty:(id)arg2;	// IMP=0x0010000000077655
- (void)setExternalValuesWithDictionary:(id)arg1;	// IMP=0x001000000007763f
- (void)reloadFromDatabaseEntity:(id)arg1 properties:(id)arg2;	// IMP=0x0010000000077588
- (id)initWithPropertyValues:(id)arg1;	// IMP=0x0010000000077518
- (id)initWithDatabaseEntity:(id)arg1 properties:(id)arg2;	// IMP=0x0010000000077477
- (id)init;	// IMP=0x0010000000077402
- (id)dictValueForProperty:(id)arg1;	// IMP=0x0010000000077dd8
- (id)arrayValueForProperty:(id)arg1;	// IMP=0x0010000000077d81
- (id)urlValueForProperty:(id)arg1;	// IMP=0x0010000000077d2a
- (id)uuidValueForProperty:(id)arg1;	// IMP=0x0010000000077cd3
- (id)stringValueForProperty:(id)arg1;	// IMP=0x0010000000077c7c
- (id)numberValueForProperty:(id)arg1;	// IMP=0x0010000000077c25
- (long long)integerValueForProperty:(id)arg1;	// IMP=0x0010000000077be1
- (id)dateValueForProperty:(id)arg1;	// IMP=0x0010000000077b8a
- (_Bool)boolValueForProperty:(id)arg1;	// IMP=0x0010000000077b46

@end

