//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SQLiteComparisonPredicate
{
    long long _comparisonType;	// 16 = 0x10
    id _value;	// 24 = 0x18
}

+ (id)predicateWithProperty:(id)arg1 value:(id)arg2 comparisonType:(long long)arg3;	// IMP=0x002000000013af76
+ (id)predicateWithProperty:(id)arg1 equalToValue:(id)arg2;	// IMP=0x001000000013af5e
+ (id)predicateWithProperty:(id)arg1 equalToLongLong:(long long)arg2;	// IMP=0x001000000013aece
- (void).cxx_destruct;	// IMP=0x002000000013b422
@property(readonly, nonatomic) id value; // @synthesize value=_value;
@property(readonly, nonatomic) long long comparisonType; // @synthesize comparisonType=_comparisonType;
- (id)_comparisonTypeString;	// IMP=0x001000000013b3d3
- (id)SQLForEntityClass:(Class)arg1;	// IMP=0x001000000013b312
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000013b1d6
- (unsigned long long)hash;	// IMP=0x001000000013b149
- (void)applyBinding:(id)arg1 atIndex:(inout int *)arg2;	// IMP=0x001000000013b074
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000013b069

@end

