//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ACAccount, AMSBagValue, ApplicationProxy, NSString;

@interface SwitchAppOwnerTask
{
    ACAccount *_account;	// 8 = 0x8
    NSString *_fromUserName;	// 16 = 0x10
    NSString *_logKey;	// 24 = 0x18
    ApplicationProxy *_proxy;	// 32 = 0x20
    AMSBagValue *_swithUserBagUrl;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000001c5909
- (_Bool)_refreshReceiptForAppProxyForMacOS;	// IMP=0x00100000001c5901
- (_Bool)_swithUserForMacOS;	// IMP=0x00100000001c58f9
- (_Bool)_repairReceiptForAppProxyIOS:(id)arg1 receiptData:(id)arg2;	// IMP=0x00100000001c58f1
- (_Bool)_repairSINFUsingContentRestore;	// IMP=0x00100000001c58e9
- (id)_performRequestWithError:(id *)arg1;	// IMP=0x00100000001c5641
- (id)_newBaseRequestBodyDictionary;	// IMP=0x00100000001c54ee
- (id)_getSinf;	// IMP=0x00100000001c54e6
- (id)_getReceipt;	// IMP=0x00100000001c54de
- (void)main;	// IMP=0x00100000001c51f2
- (id)initWithAccount:(id)arg1 fromUserName:(id)arg2 proxy:(id)arg3;	// IMP=0x00100000001c50d7

@end

