//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface UpdatesManager : NSObject
{
}

+ (_Bool)_shouldUseModernUpdates;	// IMP=0x004000000013653a
+ (_Bool)isTVProviderApp:(long long)arg1;	// IMP=0x0010000000136532
+ (_Bool)shouldUseModernUpdates;	// IMP=0x001000000013640e
+ (id)sharedManager;	// IMP=0x00100000001363c4

@end

