//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AMSProcessInfo, AMSSnapshotBag, NSDate, NSString;
@protocol AMSBagProtocol;

@interface URLBag : NSObject
{
    id <AMSBagProtocol> _bag;	// 8 = 0x8
    id _snapshotBagChangedObserver;	// 16 = 0x10
    struct os_unfair_lock_s _lock;	// 24 = 0x18
    AMSSnapshotBag *_locked_snapshotBag;	// 32 = 0x20
    _Bool expired;	// 40 = 0x28
    NSDate *expirationDate;	// 48 = 0x30
    NSString *profile;	// 56 = 0x38
    NSString *profileVersion;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0020000000107238
@property(readonly, nonatomic, getter=isExpired) _Bool expired; // @synthesize expired;
@property(readonly, nonatomic) NSDate *expirationDate; // @synthesize expirationDate;
- (id)URLForKey:(id)arg1;	// IMP=0x001000000010715b
- (id)stringForKey:(id)arg1;	// IMP=0x0010000000107145
- (id)integerForKey:(id)arg1;	// IMP=0x001000000010712f
- (id)doubleForKey:(id)arg1;	// IMP=0x0010000000107119
- (id)dictionaryForKey:(id)arg1;	// IMP=0x0010000000106f04
- (id)boolForKey:(id)arg1;	// IMP=0x0010000000106eee
- (id)arrayForKey:(id)arg1;	// IMP=0x0010000000106ed8
- (void)createSnapshotWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000106ec2
@property(readonly, copy, nonatomic) NSString *profileVersion; // @synthesize profileVersion;
@property(readonly, copy, nonatomic) NSString *profile; // @synthesize profile;
- (void)dealloc;	// IMP=0x00100000001057ce
- (id)init;	// IMP=0x00100000001057c2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) AMSProcessInfo *processInfo;
@property(readonly) Class superclass;

@end

