//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface XDCProgress : PBCodable
{
    long long _completedUnitCount;	// 8 = 0x8
    long long _totalUnitCount;	// 16 = 0x10
    NSString *_bundleID;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000c253e
- (unsigned long long)hash;	// IMP=0x00100000000c24f0
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000c2438
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000c23a2
- (void)writeTo:(id)arg1;	// IMP=0x00100000000c232b
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000c231e
- (id)dictionaryRepresentation;	// IMP=0x00100000000c1f87
- (id)description;	// IMP=0x00100000000c1ed8

@end

