//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol CMFSyncAgentDataStore;

@interface CommunicationsFilterBlockListStore : NSObject
{
    id <CMFSyncAgentDataStore> _dataStore;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x0040000000001e6b
@property(readonly, nonatomic) id <CMFSyncAgentDataStore> dataStore; // @synthesize dataStore=_dataStore;
- (void)handleNSUbiquitousKeyValueStoreDidChangeExternallyNotification:(id)arg1;	// IMP=0x00100000000034ff
- (void)_updateStore:(id)arg1 revision:(unsigned long long)arg2 updateKVS:(_Bool)arg3 updateLocal:(_Bool)arg4 itemsNeedConversion:(_Bool)arg5;	// IMP=0x001000000000301d
- (_Bool)isItemInList:(id)arg1;	// IMP=0x0010000000002f42
- (id)_isItemInList:(id)arg1 blockList:(id)arg2;	// IMP=0x0010000000002e1a
- (id)_copyItems:(_Bool)arg1;	// IMP=0x0010000000002d60
- (id)copyAllItems;	// IMP=0x0010000000002d4c
- (id)copyAllItemsAsDictionaries;	// IMP=0x0010000000002d35
- (_Bool)removeItemForAllServices:(id)arg1;	// IMP=0x0010000000002c13
- (_Bool)addItemForAllServices:(id)arg1;	// IMP=0x00100000000023b9
- (void)_storeDidChangeExternally;	// IMP=0x001000000000234f
- (void)updateDataStore;	// IMP=0x00100000000021d0
- (void)synchronizeDataStore;	// IMP=0x0010000000002137
- (void)migrateLegacyDataStoreIfNeeded;	// IMP=0x0010000000001fb4
- (void)dealloc;	// IMP=0x0010000000001f79
- (id)init;	// IMP=0x0010000000001eb0

@end

