//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Photos/PHAssetResourceManager.h>

@interface PHAssetResourceManager (FileBasedDownload)
+ (void)vcp_flushFileCache;	// IMP=0x0010000000013932
+ (void)vcp_flushResourceURL:(id)arg1;	// IMP=0x001000000001373a
+ (int)vcp_requestFileURLForAssetResource:(id)arg1 taskID:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000012e41
+ (void)vcp_createFileCacheDirectoryIfNeeded;	// IMP=0x0010000000012af1
+ (id)vcp_fileCacheDirectoryPath;	// IMP=0x0010000000012aa3
@end

