//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BMSyncDevicePeerMetadata, NSString;

@interface BMSyncDevicePeer : NSObject
{
    NSString *_deviceIdentifier;	// 8 = 0x8
    BMSyncDevicePeerMetadata *_metadata;	// 16 = 0x10
    unsigned long long _protocolVersion;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00100000000075fe
@property(nonatomic) unsigned long long protocolVersion; // @synthesize protocolVersion=_protocolVersion;
@property(readonly, nonatomic) BMSyncDevicePeerMetadata *metadata; // @synthesize metadata=_metadata;
@property(readonly, copy, nonatomic) NSString *deviceIdentifier; // @synthesize deviceIdentifier=_deviceIdentifier;
- (id)dictionaryRepresentation;	// IMP=0x00100000000074d7
- (id)initFromDictionary:(id)arg1;	// IMP=0x00100000000073c9
- (unsigned long long)hash;	// IMP=0x0010000000007343
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000007231
- (id)initWithDeviceIdentifier:(id)arg1 metadata:(id)arg2 protocolVersion:(unsigned long long)arg3;	// IMP=0x001000000000718c
- (id)initWithFMResultSet:(id)arg1;	// IMP=0x0010000000005eba

@end

