//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface ALCLStairClimbingModel : PBCodable
{
    float _machineFrequency;	// 8 = 0x8
}

@property(nonatomic) float machineFrequency; // @synthesize machineFrequency=_machineFrequency;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000003bdfbc
- (unsigned long long)hash;	// IMP=0x00100000003bdecc
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000003bde80
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000003bde2b
- (void)copyTo:(id)arg1;	// IMP=0x00100000003bde14
- (void)writeTo:(id)arg1;	// IMP=0x00100000003bddf6
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000003bdde9
- (id)dictionaryRepresentation;	// IMP=0x00100000003bdbe3
- (id)description;	// IMP=0x00100000003bdb6c

@end

