//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface CLAvengerReconciler : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
}

- (id)attemptReconciliationWithAddress:(id)arg1 advertisementData:(id)arg2;	// IMP=0x0020000000a7bc39
- (void)dealloc;	// IMP=0x0010000000a7bc0a
- (id)initWithQueue:(id)arg1;	// IMP=0x0010000000a7bbf6

@end

