//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class CLAvengerScannerClient, NSString;
@protocol CLAvengerScannerServiceProtocol;

@interface CLAvengerObservationReporterService : CLIntersiloService
{
    struct CLAvengerObservationReporterServiceStateContext _currentContext;	// 8 = 0x8
    long long _currentState;	// 16 = 0x10
    id <CLAvengerScannerServiceProtocol> _avengerScannerProxy;	// 24 = 0x18
    struct unique_ptr<CLAppMonitor_Type::Client, std::default_delete<CLAppMonitor_Type::Client>> _appMonitorClient;	// 32 = 0x20
    CLAvengerScannerClient *_scannerClient;	// 40 = 0x28
}

+ (_Bool)isSupported;	// IMP=0x002000000067eac2
+ (id)getSilo;	// IMP=0x001000000067ea66
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000067ea4d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x001000000067e9f0
- (id).cxx_construct;	// IMP=0x002000000067f6bc
- (void).cxx_destruct;	// IMP=0x001000000067f694
- (void)onAppMonitorNotification:(int)arg1 data:(struct NotificationData)arg2;	// IMP=0x001000000067f366
- (void)unregisterForAppMonitorNotification;	// IMP=0x001000000067f2b6
- (void)registerForAppMonitorNotification;	// IMP=0x001000000067f130
- (void)onAvengerAdvertisement:(id)arg1 address:(id)arg2 advertisementData:(id)arg3 status:(unsigned char)arg4 rssi:(long long)arg5 reserved:(id)arg6 channel:(id)arg7 reconciledInformation:(id)arg8;	// IMP=0x001000000067f113
- (void)onAggressiveScanStarted;	// IMP=0x001000000067f10d
- (void)onAggressiveScanEnded;	// IMP=0x001000000067f107
- (void)onAdvertisementBufferEmptied;	// IMP=0x001000000067f101
- (void)unregisterForAvengerScanner;	// IMP=0x001000000067eff8
- (void)registerForAvengerScanner;	// IMP=0x001000000067ee14
- (id)clientIdentifier;	// IMP=0x001000000067ee07
- (long long)determineStateWithContext:(struct CLAvengerObservationReporterServiceStateContext)arg1;	// IMP=0x001000000067edf9
- (void)updateContext:(struct CLAvengerObservationReporterServiceStateContext)arg1;	// IMP=0x001000000067ecce
- (void)endService;	// IMP=0x001000000067eca0
- (void)beginService;	// IMP=0x001000000067ebb5
- (id)init;	// IMP=0x001000000067eb78

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

