//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class NSObject, NSString;
@protocol OS_dispatch_source;

@interface CLCardioChangeService : CLIntersiloService
{
    struct shared_ptr<CLCardioChangeHistoryDb> fOutputDb;	// 8 = 0x8
    struct unique_ptr<CLActivityAggregator<CLCardioChange::EstimateResult>, std::default_delete<CLActivityAggregator<CLCardioChange::EstimateResult>>> fChangeAggregator;	// 24 = 0x18
    NSObject<OS_dispatch_source> *fAggregationTimer;	// 32 = 0x20
    struct Stats fStats;	// 40 = 0x28
    struct unique_ptr<CLNatalimetryNotifier_Type::Client, std::default_delete<CLNatalimetryNotifier_Type::Client>> fNatalimetryClient;	// 88 = 0x58
    struct unique_ptr<CLCardioChangeEstimator, std::default_delete<CLCardioChangeEstimator>> fCardioChangeEstimator;	// 96 = 0x60
}

+ (_Bool)isSupported;	// IMP=0x00200000009aa355
+ (id)getSilo;	// IMP=0x00100000009aa2bc
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000009aa2a3
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000009aa246
- (id).cxx_construct;	// IMP=0x00200000009ac781
- (void).cxx_destruct;	// IMP=0x00100000009ac723
- (void)sendAnalytics;	// IMP=0x00100000009ac01b
- (void)logAnalytics:(struct EstimateResult *)arg1;	// IMP=0x00100000009abc8f
- (void)markXpcActivityDone:(id)arg1;	// IMP=0x00100000009abb8c
- (void)resetCardioChangeEstimationActivity:(id)arg1 withDelay:(long long)arg2;	// IMP=0x00100000009aba22
- (void)executeCardioChangeEstimation:(id)arg1;	// IMP=0x00100000009ab95c
- (void)scheduleChangeEstimation;	// IMP=0x00100000009ab273
- (void)onChangeEstimationActivity:(id)arg1;	// IMP=0x00100000009aaffe
- (void)onNatalimetryNotification:(const int *)arg1 data:(const union NotificationData *)arg2;	// IMP=0x00100000009aae80
- (void)setUpAggregationOnTimer;	// IMP=0x00100000009aa7ba
- (void)endService;	// IMP=0x00100000009aa711
- (void)beginService;	// IMP=0x00100000009aa39b
- (id)init;	// IMP=0x00100000009aa318

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
// Error: Property attributes should begin with the type ('T') attribute, property name: superclass
// Property attributes: (null)

@property(nonatomic) _Bool valid;

@end

