//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CLRunningPowerHealthKitWriter
{
}

- (void)writeToHealthRunningPower:(double)arg1 startDate:(id)arg2 endDate:(id)arg3;	// IMP=0x0040000000362d92
- (void)dealloc;	// IMP=0x0010000000362d63
- (id)init;	// IMP=0x0010000000362d34

@end

