//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CMStrideCalibrationElevationBuffer : NSObject
{
    struct deque<CLElevationChangeEntry, std::allocator<CLElevationChangeEntry>> fElevationWindow;	// 8 = 0x8
}

- (id).cxx_construct;	// IMP=0x002000000093efb7
- (void).cxx_destruct;	// IMP=0x001000000093efa9
- (void)updateGradient:(id)arg1;	// IMP=0x001000000093eb13
- (void)feedElevationData:(const union NotificationData *)arg1;	// IMP=0x001000000093e8f1
- (void)ageOutElevationArray;	// IMP=0x001000000093e86e

@end

