//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC10TVSettings28TVSettingsUserErrorPresenter : NSObject
{
}

- (id)init;	// IMP=0x00400000000f18c0
- (id)repairUserFailedAlertForError:(id)arg1 copyStyle:(long long)arg2;	// IMP=0x00100000000f1670
- (id)signInServiceFailedAlertForError:(id)arg1;	// IMP=0x00100000000f15f0
- (id)addUserFailedAlertForError:(id)arg1;	// IMP=0x00100000000f15d0

@end

