//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <IMCore/IMAccountController.h>

@class NSArray;

@interface IMAccountController (FaceTime)
@property(readonly, nonatomic) NSArray *tvs_faceTimeAccounts;
@end

