//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PineBoardServices/PBSDisplayManager.h>

@interface PBSDisplayManager (TVSettings)
+ (id)refreshRateFormatter;	// IMP=0x001000000007bc59
+ (id)marketNameDisplayResolutionFormatterWithRefreshRate:(_Bool)arg1;	// IMP=0x001000000007b8db
+ (id)displayResolutionFormatter;	// IMP=0x001000000007b8c2
+ (id)dynamicRangeColorFormatter;	// IMP=0x001000000007b695
+ (id)SDRChromaFormatter;	// IMP=0x001000000007b67e
+ (id)HDR10ChromaFormatter;	// IMP=0x001000000007b667
+ (id)_chromaFormatterForDynamicRange:(long long)arg1;	// IMP=0x001000000007b43b
+ (id)SDRColorMappingFormatter;	// IMP=0x001000000007b23c
@end

