//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSBundle, NSString, TVSettingsContainerizedPreferencesFacade;

@interface TVSettingsItemFactory : NSObject
{
    NSBundle *_bundle;	// 8 = 0x8
    NSString *_stringsTable;	// 16 = 0x10
    NSString *_appIdentifier;	// 24 = 0x18
    TVSettingsContainerizedPreferencesFacade *_preferencesFacade;	// 32 = 0x20
}

+ (long long)_autocapitalizationTypeFromString:(id)arg1;	// IMP=0x0040000000043243
+ (long long)_autocorrectionTypeFromString:(id)arg1;	// IMP=0x00100000000431da
+ (long long)_keyboardTypeFromString:(id)arg1;	// IMP=0x0010000000043135
+ (_Bool)_specifierSupported:(id)arg1;	// IMP=0x00100000000430d3
- (void).cxx_destruct;	// IMP=0x0020000000043331
@property(retain, nonatomic) TVSettingsContainerizedPreferencesFacade *preferencesFacade; // @synthesize preferencesFacade=_preferencesFacade;
@property(copy, nonatomic) NSString *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
@property(copy, nonatomic) NSString *stringsTable; // @synthesize stringsTable=_stringsTable;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
- (id)privacyItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0010000000043026
- (id)titleItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0010000000042ca2
- (id)toggleItemFromSpecifierDictionary:(id)arg1;	// IMP=0x00100000000428a5
- (id)longTextItemFromSpecifierDictionary:(id)arg1;	// IMP=0x0010000000042604
- (id)textItemFromSpecifierDictionary:(id)arg1;	// IMP=0x00100000000422ff
- (id)sliderItemFromSpecifierDictionary:(id)arg1;	// IMP=0x00100000000422be
- (id)radioGroupFromSpecifierDictionary:(id)arg1;	// IMP=0x0010000000041e53
- (id)multiValueItemFromSpecifierDictionary:(id)arg1;	// IMP=0x00100000000418cc
- (id)groupFromSpecifierDictionary:(id)arg1 withItems:(id)arg2;	// IMP=0x00100000000416bf
- (id)childPaneItemFromSpecifierDictionary:(id)arg1;	// IMP=0x00100000000412ae
- (id)initWithBundle:(id)arg1 appIdentifier:(id)arg2 containerPath:(id)arg3;	// IMP=0x00100000000411b7

@end

