//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@class TSKSettingItem;

@interface TVSettingsSecureWiFiViewController : TSKViewController
{
    TSKSettingItem *_secureWiFiItem;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000071b74
@property(retain, nonatomic) TSKSettingItem *secureWiFiItem; // @synthesize secureWiFiItem=_secureWiFiItem;
- (void)_secureWiFiProfileLoaded:(id)arg1 error:(id)arg2;	// IMP=0x0010000000071651
- (void)_loadSecureWiFiProfile:(id)arg1;	// IMP=0x0010000000071324
- (_Bool)_isSecureWiFiProfileLoaded;	// IMP=0x001000000007114b
- (void)_updateStatus;	// IMP=0x0010000000071139
- (id)loadSettingGroups;	// IMP=0x0010000000070cb7

@end

