//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsNotificationsViewController : TSKViewController
{
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x004000000001bca6
- (id)loadSettingGroups;	// IMP=0x001000000001bb06
- (void)dealloc;	// IMP=0x001000000001ba83
- (id)initWithStyle:(long long)arg1;	// IMP=0x001000000001b9f2

@end

