//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsCertificateTrustViewController : TSKViewController
{
}

- (void)_toggleTrust:(id)arg1;	// IMP=0x00400000000cb793
- (id)loadSettingGroups;	// IMP=0x00100000000cb478

@end

