//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TVSettingsUtilities : NSObject
{
}

+ (int)pidForApplication:(id)arg1;	// IMP=0x0040000000056871
+ (id)deviceManagementBundlePath;	// IMP=0x0010000000056850
+ (id)screenSaverStyleFormatter;	// IMP=0x00100000000564e1
+ (id)_defaultAttributedStringForString:(id)arg1 withFont:(id)arg2;	// IMP=0x0010000000056455
+ (id)_defaultAttributesForFont:(id)arg1;	// IMP=0x0010000000056392
+ (id)_attributedStringWithString:(id)arg1 font:(id)arg2 color:(id)arg3 kerning:(id)arg4;	// IMP=0x00100000000562f8
+ (id)_attributedStringWithString:(id)arg1 attributes:(id)arg2;	// IMP=0x001000000005627d
+ (id)_attributesWithFont:(id)arg1 color:(id)arg2 kerning:(id)arg3;	// IMP=0x0010000000056196
+ (id)capitalizeFirstPartOfCountry:(id)arg1;	// IMP=0x0010000000055ffb
+ (id)localeNameFormatterWithIdentifiers:(id)arg1;	// IMP=0x001000000005577a
+ (id)languageImage;	// IMP=0x0010000000055701
+ (id)imageForSignalStrength:(float)arg1;	// IMP=0x00100000000556c4

@end

