//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableView.h>

@interface UITableView (TVSettingsAdditions)
- (void)tv_updateSectionsWithChanges:(id)arg1;	// IMP=0x001000000001c3bf
- (void)tv_updateItemsInSection:(unsigned long long)arg1 withChanges:(id)arg2;	// IMP=0x001000000001c287
- (void)tv_updateSectionsWithChange:(id)arg1;	// IMP=0x001000000001c14c
- (void)tv_updateItemsInSection:(unsigned long long)arg1 withChange:(id)arg2;	// IMP=0x001000000001bef5
- (id)tv_indexPathsForIndexSet:(id)arg1 withOptions:(unsigned long long)arg2 prefix:(id)arg3;	// IMP=0x001000000001bd92
@end

