//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKFirstBootDetector;

@interface BKBootUIOverlayVendor : NSObject
{
    BKFirstBootDetector *_firstBootDetector;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x004000000006bfba
- (void).cxx_destruct;	// IMP=0x002000000006bfaa
- (id)currentOverlayWithLevel:(float)arg1;	// IMP=0x001000000006bdcf
- (id)initWithFirstBootDetector:(id)arg1;	// IMP=0x001000000006bd64

@end

