//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIApplication.h>

@class HFItemManager;

@interface TVSystemHomeUIServiceApplication : UIApplication
{
    HFItemManager *_cameraItemManager;	// 8 = 0x8
}

+ (id)sharedApplication;	// IMP=0x0040000000009440
- (void).cxx_destruct;	// IMP=0x0020000000009990
@property(readonly, nonatomic) HFItemManager *cameraItemManager; // @synthesize cameraItemManager=_cameraItemManager;
- (void)_fetchInitialCameraItemsWithHome:(id)arg1;	// IMP=0x0010000000009800
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00100000000096f0
- (void)refreshItemManager;	// IMP=0x0010000000009600
- (void)dealloc;	// IMP=0x0010000000009570
- (id)init;	// IMP=0x0010000000009480

@end

