//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSError.h>

@interface GTError_replayer : NSError
{
}

- (id)dy_errorSignature;	// IMP=0x0040000000021a4b
- (id)localizedDescription;	// IMP=0x0010000000021998

@end

