//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMapTable, NSMutableDictionary, NSString, PBSystemOverlayController, PBSystemServiceConnection;
@protocol PBSBulletinServiceDelegate, PBSBulletinServiceInteractionDelegate;

@interface PBBulletinService : NSObject
{
    PBSystemServiceConnection *_remoteConnection;	// 8 = 0x8
    NSMapTable *_viewControllersByBulletin;	// 16 = 0x10
    NSMapTable *_bulletinInfoByBulletin;	// 24 = 0x18
    NSMutableDictionary *_pendingBulletinsByRequestID;	// 32 = 0x20
    id <PBSBulletinServiceDelegate> _delegateProxy;	// 40 = 0x28
    id <PBSBulletinServiceInteractionDelegate> _interactionDelegateProxy;	// 48 = 0x30
    PBSystemOverlayController *_overlayController;	// 56 = 0x38
}

+ (void)_setBulletinService:(id)arg1 forViewController:(id)arg2;	// IMP=0x00200000000c07af
+ (id)_bulletinServiceForViewController:(id)arg1;	// IMP=0x00100000000c06ef
+ (double)_timeoutForBulletin:(id)arg1;	// IMP=0x00100000000bf51d
+ (void)applicationTerminateBulletinViewController:(id)arg1;	// IMP=0x00100000000bc7db
+ (void)applicationRetireBulletinViewController:(id)arg1;	// IMP=0x00100000000bc6ef
+ (_Bool)applicationDismissBulletinViewController:(id)arg1;	// IMP=0x00100000000bc5fb
+ (void)applicationDeactivateBulletinViewController:(id)arg1;	// IMP=0x00100000000bc512
+ (void)applicationBulletinHandleMenuButtonForViewController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000bc40d
+ (void)applicationToggleBulletinViewControllerSize:(id)arg1;	// IMP=0x00100000000bc3a2
+ (unsigned long long)applicationActivateBulletinViewController:(id)arg1;	// IMP=0x00100000000bc277
+ (_Bool)applicationShouldActivateBulletinViewController:(id)arg1 forAction:(unsigned long long)arg2;	// IMP=0x00100000000bc251
+ (unsigned long long)applicationActivationActionsForBulletinViewController:(id)arg1;	// IMP=0x00100000000bc0b4
+ (id)_bulletinServicesByViewController;	// IMP=0x00100000000bb5c6
- (void).cxx_destruct;	// IMP=0x00200000000c0a1e
@property(readonly, nonatomic) PBSystemOverlayController *overlayController; // @synthesize overlayController=_overlayController;
@property(retain) id <PBSBulletinServiceInteractionDelegate> interactionDelegateProxy; // @synthesize interactionDelegateProxy=_interactionDelegateProxy;
@property(retain) id <PBSBulletinServiceDelegate> delegateProxy; // @synthesize delegateProxy=_delegateProxy;
@property(readonly, nonatomic) NSMutableDictionary *pendingBulletinsByRequestID; // @synthesize pendingBulletinsByRequestID=_pendingBulletinsByRequestID;
@property(readonly, nonatomic) NSMapTable *bulletinInfoByBulletin; // @synthesize bulletinInfoByBulletin=_bulletinInfoByBulletin;
@property(readonly, nonatomic) NSMapTable *viewControllersByBulletin; // @synthesize viewControllersByBulletin=_viewControllersByBulletin;
@property(readonly, nonatomic) __weak PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void)_setBulletinInfo:(id)arg1 forBulletin:(id)arg2;	// IMP=0x00100000000c04bb
- (id)_bulletinInfoForBulletin:(id)arg1;	// IMP=0x00100000000c03fb
- (id)_bulletinForBulletinInfo:(id)arg1;	// IMP=0x00100000000c01db
- (void)_setViewController:(id)arg1 forBulletin:(id)arg2;	// IMP=0x00100000000bffa7
- (id)_viewControllerForBulletin:(id)arg1;	// IMP=0x00100000000bfee7
- (id)_bulletinForViewController:(id)arg1;	// IMP=0x00100000000bfcc7
- (_Bool)_shouldBeginUserInteractionOnActivationForViewController:(id)arg1;	// IMP=0x00100000000bfc12
- (_Bool)_bulletinIsPending:(id)arg1;	// IMP=0x00100000000bfb3e
- (void)_updateRequestForBulletin:(id)arg1 withBulletin:(id)arg2;	// IMP=0x00100000000bf8e2
- (id)_bulletinForRequestID:(unsigned long long)arg1;	// IMP=0x00100000000bf809
- (void)_setBulletin:(id)arg1 forRequestID:(unsigned long long)arg2;	// IMP=0x00100000000bf6e2
- (void)_updateVideoBulletinViewController:(id)arg1 withBulletin:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000bf1f8
- (void)toggleBulletinSizeForViewController:(id)arg1;	// IMP=0x00100000000bf192
- (void)_setUserInteractionEnabled:(_Bool)arg1 forViewController:(id)arg2;	// IMP=0x00100000000bf127
- (void)_handleMenuButtonForViewController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000bf0a9
- (void)_prepareToPresentViewController:(id)arg1;	// IMP=0x00100000000bf011
- (void)_handleApplicationDismissalForViewController:(id)arg1 withReason:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000bebef
- (void)_handleApplicationDismissalForViewController:(id)arg1 withReason:(unsigned long long)arg2;	// IMP=0x00100000000bebd9
- (void)_handleApplicationDismissalForBulletin:(id)arg1 withReason:(unsigned long long)arg2;	// IMP=0x00100000000be985
- (void)_completeWithBulletin:(id)arg1 success:(_Bool)arg2 error:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000000be797
- (id)_reserveTableSpaceForBulletin:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000be633
- (void)remoteBulletinViewController:(id)arg1 didReceiveBulletinResponse:(id)arg2;	// IMP=0x00100000000be267
- (void)setInteractionDelegate:(id)arg1;	// IMP=0x00100000000be254
- (void)setDelegate:(id)arg1;	// IMP=0x00100000000be241
- (void)dismissBulletin:(id)arg1;	// IMP=0x00100000000bdf06
- (id)updateBulletin:(id)arg1 withMessage:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000bdab9
- (void)xpcUpdateBulletin:(id)arg1 withMessage:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000bd785
- (void)_presentBulletin:(id)arg1 prepared:(CDUnknownBlockType)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000bc8df
- (void)presentBulletin:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000bc8c7
- (void)bulletinManager:(id)arg1 willPresentBulletinViewController:(id)arg2 withActivationActions:(unsigned long long)arg3;	// IMP=0x00100000000bbfc0
- (void)invalidate;	// IMP=0x00100000000bb7e0
- (void)dealloc;	// IMP=0x00100000000bb76b
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x00100000000bb645
- (id)init;	// IMP=0x00100000000bb637

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

