//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SplashBoard/XBSnapshotDataProviderContext.h>

@class NSString;

@interface PBDefaultLaunchImageDataProviderContext : XBSnapshotDataProviderContext
{
    NSString *_bundleIdentifier;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000012651f
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;

@end

