//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIRootWindowScenePresentationBinder.h>

@class NSString, UIRootSceneWindow;

@interface PBMainDisplayRootWindowScenePresentationBinder : UIRootWindowScenePresentationBinder
{
    UIRootSceneWindow *_rootWindow;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x00200000000e6f5d
+ (id)dependencyDescription;	// IMP=0x00100000000e6ece
- (void).cxx_destruct;	// IMP=0x00200000000e70e0
@property(readonly, nonatomic) UIRootSceneWindow *rootWindow; // @synthesize rootWindow=_rootWindow;
- (id)init;	// IMP=0x00100000000e6fb4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

