//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSArray, PBOverlayLayoutController, PBSOverlayLayoutTransitionContext;

@protocol PBOverlayLayoutControllerDelegate <NSObject>
- (void)layoutController:(PBOverlayLayoutController *)arg1 didUpdateHints:(NSArray *)arg2 withTransitionContext:(PBSOverlayLayoutTransitionContext *)arg3;
@end

