//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PBSystemOverlayContext : NSObject
{
    long long _layoutLevel;	// 8 = 0x8
    unsigned long long _sceneDeactivationReasons;	// 16 = 0x10
}

@property(readonly, nonatomic) unsigned long long sceneDeactivationReasons;
@property(readonly, nonatomic) long long layoutLevel;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000158dfc
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000158df0
- (id)initWithContext:(id)arg1;	// IMP=0x0010000000158d6e

@end

