//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSOperation.h>

@class FBProcessManager, NSString, RBSProcessIdentity;

@interface PBTerminateApplicationOperation : NSOperation
{
    _Bool _executing;	// 8 = 0x8
    _Bool _finished;	// 9 = 0x9
    FBProcessManager *_processManager;	// 16 = 0x10
    RBSProcessIdentity *_applicationProcessIdentity;	// 24 = 0x18
    NSString *_reason;	// 32 = 0x20
    CDUnknownBlockType _terminateApplicationCompletionHandler;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000001e84fa
@property(copy, nonatomic) CDUnknownBlockType terminateApplicationCompletionHandler; // @synthesize terminateApplicationCompletionHandler=_terminateApplicationCompletionHandler;
@property(copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(readonly, nonatomic) RBSProcessIdentity *applicationProcessIdentity; // @synthesize applicationProcessIdentity=_applicationProcessIdentity;
@property(readonly, nonatomic) FBProcessManager *processManager; // @synthesize processManager=_processManager;
- (void)start;	// IMP=0x00100000001e7e3b
- (_Bool)isFinished;	// IMP=0x00100000001e7dff
- (_Bool)isExecuting;	// IMP=0x00100000001e7dc3
- (_Bool)isAsynchronous;	// IMP=0x00100000001e7dbb
- (id)initWithApplicationProcessIdentity:(id)arg1;	// IMP=0x00100000001e7d3a
- (id)initWithProcessManager:(id)arg1 applicationProcessIdentity:(id)arg2;	// IMP=0x00100000001e7b74

@end

