//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSystemUI/TVSUIWallpaper.h>

@interface TVSUIWallpaper (PineBoardAdditions)
+ (id)pb_wallpaperViewForVariant:(long long)arg1 bundleIdentifier:(id)arg2;	// IMP=0x001000000014615f
@end

