//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSString, NSXPCInterface, NSXPCListener;
@protocol OS_dispatch_queue, RPMessageable;

@interface RPStatusDaemon : NSObject
{
    _Bool _invalidateCalled;	// 8 = 0x8
    _Bool _invalidateDone;	// 9 = 0x9
    NSXPCInterface *_xpcClientInterface;	// 16 = 0x10
    NSMutableSet *_xpcConnections;	// 24 = 0x18
    NSXPCListener *_xpcListener;	// 32 = 0x20
    NSXPCInterface *_xpcDaemonInterface;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 48 = 0x30
    id <RPMessageable> _messenger;	// 56 = 0x38
}

+ (id)sharedStatusDaemon;	// IMP=0x0020000000069d6a
- (void).cxx_destruct;	// IMP=0x002000000006ac9b
@property(retain, nonatomic) id <RPMessageable> messenger; // @synthesize messenger=_messenger;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void)_xpcConnectionInvalidated:(id)arg1;	// IMP=0x001000000006abf9
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000006a674
- (void)_update;	// IMP=0x001000000006a66e
- (_Bool)removeXPCMatchingToken:(unsigned long long)arg1;	// IMP=0x001000000006a666
- (_Bool)addXPCMatchingToken:(unsigned long long)arg1 event:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x001000000006a65e
- (void)prefsChanged;	// IMP=0x001000000006a64c
- (_Bool)diagnosticCommand:(id)arg1 params:(id)arg2;	// IMP=0x001000000006a63b
- (void)daemonInfoChanged:(unsigned long long)arg1;	// IMP=0x001000000006a635
- (void)_invalidated;	// IMP=0x001000000006a5c0
- (void)_invalidate;	// IMP=0x001000000006a510
- (void)invalidate;	// IMP=0x001000000006a4af
- (void)_activate;	// IMP=0x001000000006a273
- (void)activate;	// IMP=0x001000000006a212
- (id)descriptionWithLevel:(int)arg1;	// IMP=0x0010000000069e2f
- (id)init;	// IMP=0x0010000000069dbf

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

