//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary, TVProfileMappingViewController;

@protocol TVProfileMappingViewControllerDelegate
- (void)profileMappingViewController:(TVProfileMappingViewController *)arg1 didFinishWithMap:(NSDictionary *)arg2;
@end

