//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDActivationBudgetObserver
{
}

- (id)metadata;	// IMP=0x0040000000008e5c
- (void)invalidate;	// IMP=0x0010000000008e2d
- (id)evaluatePredicateWithError:(id *)arg1;	// IMP=0x0010000000008ddd
- (id)initWithDelegate:(id)arg1 uniqueIdentifier:(id)arg2 compositeBudgetPredicate:(id)arg3;	// IMP=0x0010000000008dae
- (id)initWithDelegate:(id)arg1 uniqueIdentifier:(id)arg2 budgetPredicate:(id)arg3;	// IMP=0x0010000000008d7f

@end

