//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDConfigurationRemoveOperation
{
}

- (void)endOperationMarkingPayloadMetadata:(id)arg1 failedWithError:(id)arg2;	// IMP=0x00400000000341d0
- (void)removalOperationDidFinish:(id)arg1 userInfo:(id)arg2;	// IMP=0x0010000000033da6
- (void)main;	// IMP=0x0010000000033230

@end

