//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class DMFConfigurationOrganization, NSArray, NSMutableDictionary, NSString;
@protocol DMDConfigurationOrganizationControllerDelegate;

@interface DMDConfigurationOrganizationController : NSObject
{
    NSString *_identifier;	// 8 = 0x8
    NSString *_displayName;	// 16 = 0x10
    NSString *_type;	// 24 = 0x18
    id <DMDConfigurationOrganizationControllerDelegate> _delegate;	// 32 = 0x20
    NSMutableDictionary *_persistentConfigurationSourceControllersByIdentifier;	// 40 = 0x28
    NSMutableDictionary *_ephemeralConfigurationSourceControllersByIdentifier;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00200000000328f2
@property(retain, nonatomic) NSMutableDictionary *ephemeralConfigurationSourceControllersByIdentifier; // @synthesize ephemeralConfigurationSourceControllersByIdentifier=_ephemeralConfigurationSourceControllersByIdentifier;
@property(retain, nonatomic) NSMutableDictionary *persistentConfigurationSourceControllersByIdentifier; // @synthesize persistentConfigurationSourceControllersByIdentifier=_persistentConfigurationSourceControllersByIdentifier;
@property(nonatomic) __weak id <DMDConfigurationOrganizationControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)resolveAssetWithContext:(id)arg1;	// IMP=0x0010000000032749
- (void)configurationSourceController:(id)arg1 fetchEventsWithCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000003258c
- (void)configurationSourceController:(id)arg1 fetchStatusUpdatesWithCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000323cf
- (void)unregisterConfigurationSource:(id)arg1;	// IMP=0x001000000003233f
- (id)registerConfigurationSource:(id)arg1;	// IMP=0x0010000000032157
- (id)configurationSourceWithIdentifier:(id)arg1;	// IMP=0x0010000000032087
@property(readonly, copy, nonatomic) NSArray *ephemeralConfigurationSources;
@property(readonly, copy, nonatomic) NSArray *persistentConfigurationSources;
@property(readonly, copy, nonatomic) NSArray *configurationSourceControllers;
@property(readonly, nonatomic) DMFConfigurationOrganization *organization;
@property(readonly, copy) NSString *description;
- (void)updateWithOrganization:(id)arg1;	// IMP=0x001000000003159c
- (id)initWithOrganization:(id)arg1 delegate:(id)arg2;	// IMP=0x00100000000314a6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

