//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDRemoveOSUpdateOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x004000000006527f
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000006524d
- (void)runWithRequest:(id)arg1;	// IMP=0x004000000006528c

@end

