//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreData/NSManagedObject.h>

@class NSData, NSSet;

@interface GKCDContactInfoList : NSManagedObject
{
}

+ (id)fetchRequest;	// IMP=0x001000000024dfe6

// Remaining properties
@property(retain, nonatomic) NSData *changeHistoryToken; // @dynamic changeHistoryToken;
@property(retain, nonatomic) NSSet *entries; // @dynamic entries;

@end

