//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString;
@protocol OS_dispatch_semaphore;

@interface GKResourceIdentifier : NSObject
{
    NSArray *_keys;	// 8 = 0x8
    NSObject<OS_dispatch_semaphore> *_semaphore;	// 16 = 0x10
    NSString *_queueName;	// 24 = 0x18
}

+ (id)resourceIdentifierForKeys:(id)arg1;	// IMP=0x00200000000a38c7
+ (id)resourceIdentifiersForBagKeys:(id)arg1;	// IMP=0x00100000000a37a9
- (void).cxx_destruct;	// IMP=0x00200000000a3b11
@property(readonly, nonatomic) NSString *queueName; // @synthesize queueName=_queueName;
@property(readonly, nonatomic) NSObject<OS_dispatch_semaphore> *semaphore; // @synthesize semaphore=_semaphore;
@property(retain, nonatomic) NSArray *keys; // @synthesize keys=_keys;
- (id)description;	// IMP=0x00100000000a3a5c
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000a3a05
- (unsigned long long)hash;	// IMP=0x00100000000a3914
- (void)signal;	// IMP=0x00100000000a379b
- (_Bool)wait:(double)arg1;	// IMP=0x00100000000a3750
- (id)initWithKeys:(id)arg1;	// IMP=0x00100000000a34b3
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000a347a

@end

