//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface GKServiceInterface : NSObject
{
}

+ (void)configureInterface:(id)arg1;	// IMP=0x004000000009bec3
+ (id)interfaceProtocol;	// IMP=0x001000000009bdaa
+ (id)interface;	// IMP=0x001000000009bd2b
+ (id)plistClasses;	// IMP=0x001000000009bbfb

@end

