//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKSpoofingClientProxy
{
}

- (id)externalVersion;	// IMP=0x004000000012e482
- (id)adamID;	// IMP=0x001000000012e42b
- (id)bundleShortVersion;	// IMP=0x001000000012e3d4
- (id)bundleVersion;	// IMP=0x001000000012e37d
- (id)bundleIdentifier;	// IMP=0x001000000012e326
- (id)transportWithCredential:(id)arg1;	// IMP=0x001000000012e29f

@end

