//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface BMRBiomeDSLRunner : NSObject
{
    NSDictionary *_dslAllowList;	// 8 = 0x8
}

+ (id)testingDSL1;	// IMP=0x004000000000485c
+ (double)roundToSigFigs:(double)arg1 sigFigs:(unsigned long long)arg2;	// IMP=0x00100000000047d4
+ (id)_testingAllowList;	// IMP=0x00100000000047c7
+ (id)_defaultAllowList;	// IMP=0x00100000000047ba
- (void).cxx_destruct;	// IMP=0x00200000000034ec
- (_Bool)_validateSQLTransform:(id)arg1 error:(id *)arg2;	// IMP=0x001000000000310c
- (_Bool)_validateStreamFieldAccess:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000002c2a
- (_Bool)_validateArgumentTransform:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000028ae
- (_Bool)_validateClassTransform:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000002712
- (_Bool)_validateStreamAccess:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000026df
- (id)_getFieldAllowListForStream:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000002406
- (_Bool)validateDSL:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000001df6
- (id)runDSL:(id)arg1 outputAllowList:(id)arg2 error:(id *)arg3;	// IMP=0x00100000000018b7
- (id)initWithDSLAllowList:(id)arg1;	// IMP=0x001000000000184c
- (id)init;	// IMP=0x00100000000017f1

@end

