//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class JSContext, NSDate, NSDictionary, NSError, NSFileHandle, NSString;
@protocol BMRDataSource;

@interface BMRJavascriptRunner : NSObject
{
    JSContext *_jsc;	// 8 = 0x8
    NSDictionary *_userData;	// 16 = 0x10
    id <BMRDataSource> _dataSource;	// 24 = 0x18
    NSString *_workingDir;	// 32 = 0x20
    NSFileHandle *_logFileHandle;	// 40 = 0x28
    NSFileHandle *_errorFileHandle;	// 48 = 0x30
    id _lastInput;	// 56 = 0x38
    NSDate *_startTime;	// 64 = 0x40
    unsigned long long _numMapInputs;	// 72 = 0x48
    unsigned long long _numMapOutputs;	// 80 = 0x50
    unsigned long long _numLocalReduceInputs;	// 88 = 0x58
    unsigned long long _numLocalReduceOutputs;	// 96 = 0x60
    NSString *_script;	// 104 = 0x68
    NSString *_logFilePath;	// 112 = 0x70
    NSString *_errorFilePath;	// 120 = 0x78
    double _taskTimeout;	// 128 = 0x80
    unsigned long long _mapOutputLimit;	// 136 = 0x88
    unsigned long long _localReduceOutputLimit;	// 144 = 0x90
    unsigned long long _status;	// 152 = 0x98
    NSError *_error;	// 160 = 0xa0
    double _duration;	// 168 = 0xa8
    NSDictionary *_statistics;	// 176 = 0xb0
}

+ (_Bool)validateConfig:(id)arg1 error:(id *)arg2;	// IMP=0x004000000000d1d3
- (void).cxx_destruct;	// IMP=0x002000000000c1f4
@property(readonly) NSDictionary *statistics; // @synthesize statistics=_statistics;
@property(readonly) double duration; // @synthesize duration=_duration;
@property(readonly) NSError *error; // @synthesize error=_error;
@property(readonly) unsigned long long status; // @synthesize status=_status;
@property(readonly) unsigned long long localReduceOutputLimit; // @synthesize localReduceOutputLimit=_localReduceOutputLimit;
@property(readonly) unsigned long long mapOutputLimit; // @synthesize mapOutputLimit=_mapOutputLimit;
@property(readonly) double taskTimeout; // @synthesize taskTimeout=_taskTimeout;
@property(readonly) NSString *errorFilePath; // @synthesize errorFilePath=_errorFilePath;
@property(readonly) NSString *logFilePath; // @synthesize logFilePath=_logFilePath;
@property(readonly) NSString *script; // @synthesize script=_script;
- (id)_runReduceWithMapResult:(id)arg1;	// IMP=0x001000000000bd17
- (id)_runMap;	// IMP=0x001000000000bb59
- (void)_checkTimeout;	// IMP=0x001000000000baac
- (id)_createDataSource;	// IMP=0x001000000000b39a
- (id)_createJSContext;	// IMP=0x001000000000b0e0
- (void)_killWithError:(id)arg1;	// IMP=0x001000000000aff8
- (void)_failWithError:(id)arg1;	// IMP=0x001000000000aef5
- (void)_closeFileHandles;	// IMP=0x001000000000aeb6
- (void)_openFileHandles;	// IMP=0x001000000000acd3
- (id)runMapReduce;	// IMP=0x001000000000a9a6
- (id)initWithScript:(id)arg1 userData:(id)arg2 config:(id)arg3 workingDir:(id)arg4 error:(id *)arg5;	// IMP=0x001000000000a70c

@end

