//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSPersistentContainer, NSString, NSURL;
@protocol OS_dispatch_queue;

@interface SYDCoreDataStore : NSObject
{
    _Bool _shouldLogValues;	// 8 = 0x8
    NSPersistentContainer *__persistentContainer;	// 16 = 0x10
    NSURL *_URL;	// 24 = 0x18
    NSString *_fileProtectionType;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_persistentContainerQueue;	// 40 = 0x28
    NSManagedObjectContext *_transactionContext;	// 48 = 0x30
}

+ (_Bool)isInvalidTokenError:(id)arg1;	// IMP=0x004000000002ea6c
+ (_Bool)isCorruptionError:(id)arg1;	// IMP=0x001000000002e5c1
+ (id)managedObjectModel;	// IMP=0x001000000002d796
- (void).cxx_destruct;	// IMP=0x002000000002ebd7
@property(retain, nonatomic) NSManagedObjectContext *transactionContext; // @synthesize transactionContext=_transactionContext;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *persistentContainerQueue; // @synthesize persistentContainerQueue=_persistentContainerQueue;
@property(nonatomic) _Bool shouldLogValues; // @synthesize shouldLogValues=_shouldLogValues;
@property(retain, nonatomic) NSString *fileProtectionType; // @synthesize fileProtectionType=_fileProtectionType;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(retain, nonatomic) NSPersistentContainer *_persistentContainer; // @synthesize _persistentContainer=__persistentContainer;
- (_Bool)_queue_handleCorruptionIfNecessaryFromError:(id)arg1 inPersistentStoreCoordinator:(id)arg2;	// IMP=0x001000000002e7e2
- (void)handleCorruptionIfNecessaryFromError:(id)arg1 inPersistentStoreCoordinator:(id)arg2;	// IMP=0x001000000002e49b
- (void)transactionStoreDidSave:(id)arg1;	// IMP=0x001000000002e495
- (_Bool)saveTransaction:(id *)arg1;	// IMP=0x001000000002e213
- (id)transactionalStoreWithError:(id *)arg1;	// IMP=0x001000000002e0d1
- (unsigned long long)fileSizeBytes;	// IMP=0x001000000002dc63
- (void)_queue_destroyPersistentStoreInPersistentStoreCoordinator:(id)arg1;	// IMP=0x001000000002dabf
- (void)destroyPersistentStore;	// IMP=0x001000000002d90d
- (id)persistentContainerWithError:(id *)arg1;	// IMP=0x001000000002cf12
- (_Bool)saveContext:(id)arg1 reason:(id)arg2 includingTransactionContext:(_Bool)arg3 error:(id *)arg4;	// IMP=0x001000000002cba3
- (id)_contextForStoreIdentifier:(id)arg1 persistentContainer:(id)arg2;	// IMP=0x001000000002cb29
- (id)contextForStoreIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000002ca1d
- (id)managedKeyValuesMatchingPredicate:(id)arg1 inContext:(id)arg2 error:(id *)arg3;	// IMP=0x001000000002c7ef
- (id)managedKeyValueWithRecordName:(id)arg1 inStoreWithIdentifier:(id)arg2 inContext:(id)arg3 error:(id *)arg4;	// IMP=0x001000000002c4b4
- (id)managedKeyValueWithKey:(id)arg1 inStoreWithIdentifier:(id)arg2 createIfNecessary:(_Bool)arg3 forceCreateNewRow:(_Bool)arg4 inContext:(id)arg5 error:(id *)arg6;	// IMP=0x001000000002beb7
- (id)managedKeyValueWithKey:(id)arg1 inStoreWithIdentifier:(id)arg2 createIfNecessary:(_Bool)arg3 inContext:(id)arg4 error:(id *)arg5;	// IMP=0x001000000002be96
- (id)managedStoreWithIdentifier:(id)arg1 createIfNecessary:(_Bool)arg2 inContext:(id)arg3 error:(id *)arg4;	// IMP=0x001000000002bb9e
- (id)managedDatabaseCreateIfNecessary:(_Bool)arg1 inContext:(id)arg2 error:(id *)arg3;	// IMP=0x001000000002b974
- (id)syncEngineMetadataWithError:(id *)arg1;	// IMP=0x001000000002b6e5
- (_Bool)saveSyncEngineMetadata:(id)arg1 error:(id *)arg2;	// IMP=0x001000000002b453
- (id)dictionaryRepresentationForStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000002aac9
- (short)failedMigrationCountWithError:(id *)arg1;	// IMP=0x001000000002a897
- (_Bool)setFailedMigrationCount:(short)arg1 error:(id *)arg2;	// IMP=0x001000000002a575
- (_Bool)didMigrateFromPlistsWithError:(id *)arg1;	// IMP=0x001000000002a347
- (_Bool)setDidMigrateFromPlists:(_Bool)arg1 error:(id *)arg2;	// IMP=0x001000000002a026
- (id)acAccountIdentifierWithError:(id *)arg1;	// IMP=0x0010000000029dd5
- (_Bool)setACAccountIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000029b05
- (_Bool)clearServerSystemFieldsRecordsForAllStoresWithError:(id *)arg1;	// IMP=0x0010000000029600
- (id)changedKeysForStoreIdentifier:(id)arg1 sinceChangeToken:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000027dfc
- (id)currentChangeTokenForStoreIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000278ff
- (unsigned long long)numberOfKeyValuesInStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000027572
- (_Bool)clearServerSystemFieldsRecordsForAllKeyValuesInStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000027018
- (id)allStoreIdentifiersWithError:(id *)arg1;	// IMP=0x0010000000026abe
- (id)allRecordNamesInStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000026570
- (_Bool)deleteDataForStoresMatchingPredicate:(id)arg1 context:(id)arg2 error:(id *)arg3;	// IMP=0x00100000000262b1
- (_Bool)deleteDataForAllStoresWithError:(id *)arg1;	// IMP=0x00100000000261ec
- (_Bool)deleteDataForStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000260d2
- (_Bool)saveServerSyncAnchorSystemFieldsRecordData:(id)arg1 forStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000025d60
- (id)serverSyncAnchorSystemFieldsRecordDataForStoreWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000025a21
- (_Bool)removeKeyValueForRecordName:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x00100000000255e4
- (_Bool)removeKeyValueForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x00100000000255cc
- (_Bool)removeKeyValueForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 excludeFromChangeTracking:(_Bool)arg3 error:(id *)arg4;	// IMP=0x0010000000025126
- (_Bool)saveKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x001000000002510e
- (_Bool)_saveKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2 excludeFromChangeTracking:(_Bool)arg3 enforceQuota:(_Bool)arg4 forceCreateNewRow:(_Bool)arg5 error:(id *)arg6;	// IMP=0x0010000000024614
- (_Bool)saveKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2 excludeFromChangeTracking:(_Bool)arg3 enforceQuota:(_Bool)arg4 error:(id *)arg5;	// IMP=0x00100000000245f8
- (_Bool)saveKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2 excludeFromChangeTracking:(_Bool)arg3 error:(id *)arg4;	// IMP=0x00100000000245d6
- (id)keyValueFromManagedKeyValue:(id)arg1 inStoreWithIdentifier:(id)arg2;	// IMP=0x00100000000241c0
- (id)keyValueForRecordName:(id)arg1 inStoreWithIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000023e3f
- (id)keyValueForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 createIfNecessary:(_Bool)arg3 error:(id *)arg4;	// IMP=0x0010000000023725
- (id)description;	// IMP=0x0010000000023683
- (void)dealloc;	// IMP=0x001000000002360e
- (id)initWithURL:(id)arg1 fileProtectionType:(id)arg2 persistentContainer:(id)arg3 isTransactional:(_Bool)arg4;	// IMP=0x001000000002337d
- (id)initWithURL:(id)arg1 fileProtectionType:(id)arg2;	// IMP=0x0010000000023365
- (id)initWithURL:(id)arg1;	// IMP=0x0010000000023349

@end

