//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SYDUserNotifications : NSObject
{
}

+ (id)queue;	// IMP=0x0040000000009fc0
+ (_Bool)shouldShowNotifications;	// IMP=0x0010000000009f94
+ (id)userNotificationCenter;	// IMP=0x0010000000009e87
+ (void)requestAuthorizationIfNecessary;	// IMP=0x0010000000009d07
+ (void)showNotificationWithTitle:(id)arg1 body:(id)arg2 threadIdentifier:(id)arg3;	// IMP=0x0010000000009a24
+ (void)showUserNotificationIfEnabledForStoreIdentifier:(id)arg1 format:(id)arg2;	// IMP=0x00100000000097d1

@end

