//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PAMediaConversionServiceDefaultImageMetadataPolicy
{
    float _lossyCompressionQuality;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x004000000000282b
+ (id)policyWithLossyCompressionQuality:(float)arg1;	// IMP=0x00100000000027f7
+ (id)standardPolicy;	// IMP=0x00100000000026fa
@property float lossyCompressionQuality; // @synthesize lossyCompressionQuality=_lossyCompressionQuality;
- (id)processMetadata:(id)arg1;	// IMP=0x001000000000232a
- (_Bool)metadataNeedsProcessing:(id)arg1;	// IMP=0x0010000000002322
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000000022cc
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000002246
- (id)initWithLossyCompressionQuality:(float)arg1;	// IMP=0x00100000000021f0
- (id)init;	// IMP=0x00100000000021d6

@end

