//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSDictionary;

@interface CKKSEgoManifest
{
    NSArray *_leafRecords;	// 104 = 0x68
}

+ (id)generateSignaturesWithHelper:(id)arg1 derData:(id)arg2 error:(id *)arg3;	// IMP=0x002000000012de7e
+ (id)tryFromDatabaseWhere:(id)arg1 error:(id *)arg2;	// IMP=0x001000000012dda1
+ (id)fromDatabaseWhere:(id)arg1 error:(id *)arg2;	// IMP=0x001000000012dcc4
+ (id)newManifestForZone:(id)arg1 withItems:(id)arg2 peerManifestIDs:(id)arg3 currentItems:(id)arg4 error:(id *)arg5 helper:(id)arg6;	// IMP=0x001000000012d90b
+ (id)newManifestForZone:(id)arg1 withItems:(id)arg2 peerManifestIDs:(id)arg3 currentItems:(id)arg4 error:(id *)arg5;	// IMP=0x001000000012d837
+ (id)newFakeManifestForZone:(id)arg1 withItemRecords:(id)arg2 currentItems:(id)arg3 signerID:(id)arg4 keyPair:(id)arg5 error:(id *)arg6;	// IMP=0x001000000012d6f8
+ (id)tryCurrentEgoManifestForZone:(id)arg1;	// IMP=0x001000000012d5ba
+ (id)leafRecordsForItems:(id)arg1 manifestName:(id)arg2 zone:(id)arg3;	// IMP=0x001000000012d29e
+ (id)egoHelper;	// IMP=0x001000000012d271
- (void).cxx_destruct;	// IMP=0x002000000012d25e
- (id)defaultHelperForSignerID:(id)arg1;	// IMP=0x001000000012d210
@property(retain, nonatomic) NSDictionary *signatures;
- (_Bool)saveToDatabase:(id *)arg1;	// IMP=0x001000000012cfce
- (id)allCKRecordsWithZoneID:(id)arg1;	// IMP=0x001000000012cdc4
- (id)leafRecords;	// IMP=0x001000000012cdaf
- (id)leafRecordForItemUUID:(id)arg1;	// IMP=0x001000000012ccf6
- (void)setCurrentItemUUID:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x001000000012cc9b
- (void)updateWithNewOrChangedRecords:(id)arg1 deletedRecordIDs:(id)arg2;	// IMP=0x001000000012c884
- (id)initWithDigestValue:(id)arg1 zone:(id)arg2 generationCount:(unsigned long long)arg3 leafRecords:(id)arg4 peerManifestIDs:(id)arg5 currentItems:(id)arg6 futureData:(id)arg7 signatures:(id)arg8 signerID:(id)arg9 schema:(id)arg10;	// IMP=0x001000000012c515
- (_Bool)loadLeafRecords:(id)arg1 error:(id *)arg2;	// IMP=0x001000000012c171

@end

