//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface MockAKSOptionalParameters : PBCodable
{
    NSData *_accessGroups;	// 8 = 0x8
    NSData *_acmHandle;	// 16 = 0x10
    NSData *_externalData;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000001052f
@property(retain, nonatomic) NSData *acmHandle; // @synthesize acmHandle=_acmHandle;
@property(retain, nonatomic) NSData *externalData; // @synthesize externalData=_externalData;
@property(retain, nonatomic) NSData *accessGroups; // @synthesize accessGroups=_accessGroups;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000001043d
- (unsigned long long)hash;	// IMP=0x00100000000103d0
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000102d8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000010214
- (void)copyTo:(id)arg1;	// IMP=0x0010000000010191
- (void)writeTo:(id)arg1;	// IMP=0x0010000000010117
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000000ffab
- (id)dictionaryRepresentation;	// IMP=0x001000000000ff01
- (id)description;	// IMP=0x001000000000fe52
@property(readonly, nonatomic) _Bool hasAcmHandle;
@property(readonly, nonatomic) _Bool hasExternalData;
@property(readonly, nonatomic) _Bool hasAccessGroups;

@end

