//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface IXOpaqueDataPromiseSeed
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000000f235
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x004000000000f23d
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000000f206
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000000f1d7

@end

