//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSURL;

@interface IXOwnedDataPromiseSeed
{
    NSURL *_stagingBaseDir;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000031e0e
- (void).cxx_destruct;	// IMP=0x0020000000031eb2
@property(retain, nonatomic) NSURL *stagingBaseDir; // @synthesize stagingBaseDir=_stagingBaseDir;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000031e16
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000031d73
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000031cd8

@end

