//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary;

@interface TVSMModuleDataSource : NSObject
{
    long long _type;	// 8 = 0x8
    NSArray *_availableModules;	// 16 = 0x10
    NSMutableDictionary *_modulesByInfo;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000002d020
@property(copy, nonatomic) NSMutableDictionary *modulesByInfo; // @synthesize modulesByInfo=_modulesByInfo;
@property(copy, nonatomic) NSArray *availableModules; // @synthesize availableModules=_availableModules;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
- (id)_moduleWithInfo:(id)arg1;	// IMP=0x001000000002ce20
- (void)_updateAvailableModules;	// IMP=0x001000000002c5a0
- (void)updateAvailableModules;	// IMP=0x001000000002c570
- (id)sortedModuleInfos:(id)arg1;	// IMP=0x001000000002c510
- (_Bool)shouldEnableModuleWithInfo:(id)arg1;	// IMP=0x001000000002c4c0
- (id)initWithModuleType:(long long)arg1 shouldUpdateAvailableModules:(_Bool)arg2;	// IMP=0x001000000002c3c0
- (id)initWithModuleType:(long long)arg1;	// IMP=0x001000000002c350
- (id)init;	// IMP=0x001000000002c2f0

@end

