//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UINavigationController.h>

@class PBSOverlayLayoutElementHandle;

@interface UINavigationController (TVSMButtonGridNavigationController)
@property(readonly, nonatomic, getter=tvsm_layoutElement) __weak PBSOverlayLayoutElementHandle *layoutElement;
@end

