//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableSet, SSXPCConnection;

@interface DistributedNotificationObserver : NSObject
{
    SSXPCConnection *_connection;	// 8 = 0x8
    NSMutableSet *_notificationNames;	// 16 = 0x10
}

- (void)removeObservedNotificationName:(id)arg1;	// IMP=0x002000000011e646
- (void)postNotificationName:(id)arg1 message:(id)arg2;	// IMP=0x001000000011e607
@property(readonly, nonatomic) NSArray *observedNotificationNames;
- (void)addObservedNotificationNames:(id)arg1;	// IMP=0x001000000011e5db
- (void)addObservedNotificationName:(id)arg1;	// IMP=0x001000000011e5c5
- (void)dealloc;	// IMP=0x001000000011e57b
- (id)initWithServiceName:(id)arg1;	// IMP=0x001000000011e505

@end

