//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSSet, NSString;

@interface DownloadManagerClient
{
    NSSet *_downloadKinds;	// 48 = 0x30
    _Bool _isDownloadsEntitled;	// 56 = 0x38
    NSString *_persistenceIdentifier;	// 64 = 0x40
    NSArray *_prefetchedDownloadExternalProperties;	// 72 = 0x48
    NSArray *_prefetchedDownloadProperties;	// 80 = 0x50
    _Bool _shouldFilterExternalDownloads;	// 88 = 0x58
}

- (_Bool)_supportsDownloadKind:(id)arg1;	// IMP=0x00200000000a504c
- (void)_sendCoalescableMessage:(long long)arg1 withDownloadIDs:(id)arg2;	// IMP=0x00100000000a4e46
- (_Bool)_isBackgroundApp;	// IMP=0x00100000000a4e19
- (id)_copyFilteredKindsForKinds:(id)arg1;	// IMP=0x00100000000a4b17
- (id)_copyPrivateDownloadKinds;	// IMP=0x00100000000a4a59
- (id)_copyDownloadKindsFromEntitlement;	// IMP=0x00100000000a49d9
- (id)_copyAllowedThirdPartyKinds;	// IMP=0x00100000000a495a
- (_Bool)hasEntitlements;	// IMP=0x00100000000a491c
- (_Bool)supportsDownloadKind:(id)arg1;	// IMP=0x00100000000a4850
@property _Bool shouldFilterExternalDownloads;
@property(copy) NSArray *prefetchedDownloadExternalProperties;
@property(copy) NSArray *prefetchedDownloadProperties;
@property(copy) NSString *persistenceIdentifier;
@property(copy) NSSet *downloadKinds;
- (void)setClientOptions:(id)arg1;	// IMP=0x00100000000a4354
- (void)sendDownloadsUpdatedWithIdentifiers:(id)arg1;	// IMP=0x00100000000a433a
- (void)sendDownloadStatesChangedWithIdentifiers:(id)arg1;	// IMP=0x00100000000a4320
- (void)sendDownloadStateChangedWithID:(long long)arg1 externalValues:(id)arg2 propertyValues:(id)arg3;	// IMP=0x00100000000a420f
- (void)sendDownloadsRemovedWithIdentifiers:(id)arg1;	// IMP=0x00100000000a41f5
- (void)sendDownloadKindsUsingNetwork:(id)arg1;	// IMP=0x00100000000a4144
- (void)sendChangeset:(id)arg1;	// IMP=0x00100000000a3e3b
- (_Bool)reloadPersistenceStateInDatabase:(id)arg1;	// IMP=0x00100000000a3724
- (id)persistentDownloadManagerInDatabase:(id)arg1;	// IMP=0x00100000000a3432
- (id)newDownloadWithClientXPCDownload:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000a2abd
- (id)downloadsQueryForMessage:(id)arg1 database:(id)arg2;	// IMP=0x00100000000a25e3
- (_Bool)canAccessDownload:(id)arg1;	// IMP=0x00100000000a23d1
- (_Bool)canAccessAsset:(id)arg1;	// IMP=0x00100000000a2320
- (void)addClientEntityToDatabase:(id)arg1;	// IMP=0x00100000000a2203
- (void)dealloc;	// IMP=0x00100000000a218f
- (id)initWithInputConnection:(id)arg1;	// IMP=0x00100000000a2102

@end

