//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface DownloadDataConsumer : NSObject
{
    _Bool _overrideProgress;	// 8 = 0x8
}

@property(nonatomic) _Bool overrideProgress; // @synthesize overrideProgress=_overrideProgress;
- (void)truncate;	// IMP=0x0010000000106de3
- (void)suspend;	// IMP=0x0010000000106ddd
@property(readonly, nonatomic) unsigned long long resumptionOffset;
- (void)reset;	// IMP=0x0010000000106dcf
@property(readonly, nonatomic) double percentComplete;
- (_Bool)finish:(id *)arg1;	// IMP=0x0010000000106dbe
@property(readonly, nonatomic) _Bool hasConsumedData;
@property(readonly, nonatomic) unsigned long long diskUsage;
- (_Bool)consumeData:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000106da6

@end

