//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <StoreServices/SSSQLiteEntity.h>

@interface MediaSocialContentItemEntity : SSSQLiteEntity
{
}

+ (id)newEntityValuesWithMediaSocialPostItem:(id)arg1;	// IMP=0x00400000000f4288
+ (id)databaseTable;	// IMP=0x00100000000f427b

@end

