//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesStore/ISOperation.h>

@class NSDictionary, SSRemoteNotification;

@interface PushNotificationDisplayOperation : ISOperation
{
    SSRemoteNotification *_notification;	// 96 = 0x60
}

+ (_Bool)_shouldUseBulletinBoardForNotification:(id)arg1;	// IMP=0x0040000000098b3c
- (void).cxx_destruct;	// IMP=0x0020000000098d05
- (_Bool)_URLHandlerExists;	// IMP=0x0010000000098c21
- (void)_performNotificationAction:(_Bool)arg1;	// IMP=0x00100000000978bc
- (void)_openNotificationURL;	// IMP=0x0010000000097792
- (long long)_notificationClass;	// IMP=0x0010000000097739
- (void)_loadNotificationDownloadManifest;	// IMP=0x00100000000975e0
- (void)_displayBadge;	// IMP=0x0010000000097524
- (void)_displayAlert;	// IMP=0x0010000000096dfd
- (id)_clientIdentifierForDownloadKinds:(id)arg1;	// IMP=0x0010000000096c51
- (_Bool)_clientExistsWithIdentifier:(id)arg1;	// IMP=0x0010000000096c04
- (void)run;	// IMP=0x001000000009641d
@property(readonly) _Bool requiresClientIdentifier;
@property(readonly) NSDictionary *notificationUserInfo;
- (id)initWithNotificationUserInfo:(id)arg1;	// IMP=0x00100000000962d0
- (id)init;	// IMP=0x00100000000962bc

@end

