//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ICConnectionConfiguration, ICUserIdentity, ICUserIdentityStore, ML3MusicLibrary;
@protocol ICDBackgroundTaskScheduling;

@interface BaseRequestHandler : NSObject
{
    ICUserIdentity *_userIdentity;	// 8 = 0x8
    ICUserIdentityStore *_userIdentityStore;	// 16 = 0x10
    ICConnectionConfiguration *_configuration;	// 24 = 0x18
    ML3MusicLibrary *_musicLibrary;	// 32 = 0x20
    id <ICDBackgroundTaskScheduling> _taskScheduler;	// 40 = 0x28
}

+ (id)accountlessHandler;	// IMP=0x002000000001f61b
+ (_Bool)supportsAccountlessHandling;	// IMP=0x001000000001f613
+ (id)managedConfigurations;	// IMP=0x001000000001f514
+ (id)deleteHandlerForConfiguration:(id)arg1;	// IMP=0x001000000001f3ca
+ (id)handlerForConfiguration:(id)arg1;	// IMP=0x001000000001f288
+ (id)handlers;	// IMP=0x001000000001f259
+ (id)globalSerialQueue;	// IMP=0x001000000001f1f6
- (void).cxx_destruct;	// IMP=0x002000000001f1a1
@property(retain, nonatomic) id <ICDBackgroundTaskScheduling> taskScheduler; // @synthesize taskScheduler=_taskScheduler;
@property(readonly, nonatomic) ML3MusicLibrary *musicLibrary; // @synthesize musicLibrary=_musicLibrary;
@property(readonly, nonatomic) ICConnectionConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) ICUserIdentityStore *userIdentityStore; // @synthesize userIdentityStore=_userIdentityStore;
@property(readonly, nonatomic) ICUserIdentity *userIdentity; // @synthesize userIdentity=_userIdentity;
- (void)updateLibraryWithReason:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000001f158
- (id)description;	// IMP=0x001000000001f073
- (void)cancelOperationsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000001f06d
- (void)increasePriorityForAllOperations;	// IMP=0x001000000001f067
- (void)decreasePriorityForAllOperations;	// IMP=0x001000000001f061
- (void)onCalloutQueue:(CDUnknownBlockType)arg1;	// IMP=0x001000000001efbe
- (void)cancellAllOperations;	// IMP=0x001000000001efb8
- (void)performInitialLibraryUpdate;	// IMP=0x001000000001efb2
- (void)becomeInactiveWithDeauthentication:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001efac
- (void)becomeActive;	// IMP=0x001000000001efa6
- (id)initWithConfiguration:(id)arg1;	// IMP=0x001000000001eebd
- (id)init;	// IMP=0x001000000001ee7b

@end

