//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMapTable;

@interface CloudBackgroundTaskManager : NSObject
{
    NSMapTable *_jobNameToSelectorMap;	// 8 = 0x8
}

+ (id)sharedTaskManager;	// IMP=0x00400000000e7dab
- (void).cxx_destruct;	// IMP=0x00200000000e758c
- (_Bool)_cellularDataAllowedForJaliscoMedia;	// IMP=0x00100000000e74fd
- (_Bool)_cellularDataAllowedForJaliscoApps;	// IMP=0x00100000000e74b3
- (id)_nextJaliscoAppsPollTimeKey;	// IMP=0x00100000000e74a6
- (id)_nextJaliscoMediaPollTimeKey;	// IMP=0x00100000000e7499
- (id)_nextEvaluateSyncRulesThrottleOperationTimeKey;	// IMP=0x00100000000e748c
- (id)_nextEvaluateSyncRulesOperationTimeKey;	// IMP=0x00100000000e747f
- (double)_throttledDeferredEvaluateKeepLocalTime;	// IMP=0x00100000000e73d4
- (id)_homeSharingPrefsNumberForKey:(id)arg1;	// IMP=0x00100000000e73b8
- (void)_setHomeSharingPrefsNumber:(id)arg1 forKey:(id)arg2;	// IMP=0x00100000000e738f
- (id)_baseBtaJobForPeriodicPollCellularDataAllowed:(_Bool)arg1;	// IMP=0x00100000000e7377
- (id)_baseBtaJobForDeferredPush;	// IMP=0x00100000000e735f
- (void)_handleJobNamed:(const char *)arg1 satisfied:(_Bool)arg2 invalid:(_Bool)arg3;	// IMP=0x00000000000e723f
- (void)_unscheduleJobNamed:(const char *)arg1;	// IMP=0x00100000000e7239
- (void)_scheduleJobNamed:(const char *)arg1 withStartTime:(id)arg2 baseBtaJob:(id)arg3;	// IMP=0x00100000000e7233
- (void)_initializeBTAHandlers;	// IMP=0x00100000000e722d
- (void)_handleJaliscoMediaDeferredPushUpdateJobSatisfied:(_Bool)arg1 invalidRequest:(_Bool)arg2;	// IMP=0x00100000000e6fda
- (void)_handleJaliscoMediaPeriodicPollJobSatisfied:(_Bool)arg1 invalidRequest:(_Bool)arg2;	// IMP=0x00100000000e6d4f
- (void)_handleSagaDeferredPushUpdateJobSatisfied:(_Bool)arg1 invalidRequest:(_Bool)arg2;	// IMP=0x00100000000e6afa
- (void)unscheduleJaliscoMediaDeferredPushUpate;	// IMP=0x00100000000e6af4
- (void)scheduleJaliscoMediaDeferredPushUpate;	// IMP=0x00100000000e6aee
- (void)unscheduleJaliscoMediaPeriodicPoll;	// IMP=0x00100000000e6ae8
- (void)scheduleJaliscoMediaPeriodicPoll;	// IMP=0x00100000000e6ae2
- (void)unscheduleSagaDeferredPushUpate;	// IMP=0x00100000000e6adc
- (void)scheduleSagaDeferredPushUpate;	// IMP=0x00100000000e6ad6
- (id)init;	// IMP=0x00100000000e6a8a

@end

